#
# A Makefile for XCOPY
# (c) osFree project,
# author, date
#

PROJ = xcopy
DESC = Extended COPY tool
#defines object file names in format objname.$(O)
srcfiles = $(p)kitten$(e) $(p)xcopy$(e) $(p)prf$(e)
# defines additional options for C compiler
STACKSIZE = 40000

!include $(%ROOT)/mk/appsdos.mk
