#
# A main Makefile for OS/3 boot sequence project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = exe dll lib implib regina

!include $(%ROOT)/mk/all.mk

TARGETS = subdirs
TARGET = all
