.TH regina-config 1
.SH Name
regina-config \- Developer Configuration for The Regina Rexx interpreter
.SH Syntax
.B regina-config
[
.I options
]

.SH Description
regina-config supplies configuration information to a developer
intending to use the Rexx SAA API for embedding Regina into
their application or writing Rexx external function packages.

.SH Options
.
.IP \-\-help
Displays usage.

.IP \-\-version
Displays installed version of Regina.

.IP \-\-prefix
Displays the installed prefix directory.

.IP \-\-multithreaded
Displays
.I yes
if the installed version for Regina is thread-safe or
.I no
if not thread-safe.

.IP \-\-cflags
Displays the pre-processor and compiler flags.

.IP \-\-libs
Displays the linker flags.

.SH Copyright
The Regina Rexx interpreter is distributed under the GNU Library
General Public License, see the file `COPYING-LIB' in the source code
distribution.

.SH Author
Anders Christensen, University of Trondheim, Norway
<anders@pvv.unit.no>.

Changes to Regina since 0.07a, Mark Hessling
<mark (at) rexx.org>

.SH See Also
There are several good reference books on Rexx. The most famous is
"The Rexx Language" by Mike Cowlishaw.
Visit http://www.rexxla.org (The Rexx Language Association) for any Rexx
related information.

