.TH RXSTACK "1" "June 2013" "Regina Rexx Interpreter" "User Commands"

.SH NAME
rxstack \- The Regina Rexx Interpreter stack daemon

.SH SYNOPSIS
.B rxstack
[\fB\-h\fR, \fB\-\-help\fR] [\fB\-D\fR, \fB\-\-debug\fR]
[\fB\-d\fR, \fB\-\-daemon\fR] [\fB\-k\fR, \fB\-\-kill\fR]
[\fB\-p\fR num, \fB\-\-port\fR num] [\fB\-w\fR, \fB\-\-world\fR]

.SH DESCRIPTION
.B rxstack
is a daemon that provides access to Regian Rexx external queues directly to
Regina Rexx programs or indirectly (via rxqueue) to any other program via
\fIstdin\fR and \fIstdout\fR.
.TP
Without any options, rxstack runs in the foreground.

.SH OPTIONS
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays short help.
.TP
\fB\-D\fR, \fB\-\-debug\fR
Turns debugging on
.TP
\fB\-d\fR, \fB\-\-daemon\fR
Starts rxstack as a daemon
.TP
\fB\-k\fR, \fB\-\-kill\fR
Kills the running rxstack process
.TP
\fB\-p\fR, \fB\-\-port\fR num
Specify the port on which \fBrxstack\fR listens. Overwrites the \fBRXSTACK\fR environment variable. Default is \fI5757\fR.
.TP
\fB\-w\fR, \fB\-\-world\fR
Accept connections from anywhere. By default \fBrxstack\fR only allows connections from the \fIlocalhost\fR.

.SH ENVIRONMENT
\fBrxstack\fR uses the following environment variables if set.

.IP RXDEBUG
Enables debugging. Same as specifying \-D or \-\-debug option.

.IP RXSTACK
The port number on which \fBrxstack\fR listens. By default this is \fI5757\fR. Same as specifying \-p or \-\-port option.

.IP RXQUEUE
The name of the default queue to be used if not specified by the client.
By default this is \fISESSION\fR.

.SH COPYRIGHT
The Regina Rexx interpreter is distributed under the GNU Library
General Public License, see the file `COPYING-LIB' in the source code
distribution.

.SH AUTHOR
Anders Christensen, University of Trondheim, Norway
<anders (at) pvv.unit.no>.

.SH MAINTAINER
Changes to Regina since 0.07a, Mark Hessling
<mark (at) rexx.org>
with significant assistance from Florian Grosse-Coosmann.

.SH SEE ALSO
.BR rxqueue (1)

There are several good reference books on Rexx. The most famous is
"The Rexx Language" by Mike Cowlishaw.
Visit http://www.rexxla.org (The Rexx Language Association) for any Rexx
related information.

