/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef somestio_idl
#define somestio_idl
#include <somos.idl>
#include <omgestio.idl>
module somStream
{
	interface StreamIO;
	interface MemoryStreamIO;
	interface Streamable;
	typedef sequence<octet> seq_octet;
	interface StreamIO :
		CosStream::StreamIO
	{
		enum object_tags {KeyData,RepeatRef,NilData,StringifiedRef};
		boolean already_streamed(
			in SOMObject obj,
			in SOMObject class_obj);
		void reset();
		void set_buffer(
			in seq_octet buffer);
		seq_octet get_buffer();
		void clear_buffer();
#ifdef __SOMIDL__
		implementation
		{
#ifdef __PRIVATE__
			functionprefix="somestio_StreamIO_";
#endif
			majorversion = 3;
			minorversion = 0;
			memory_management = corba;
			releaseorder : 
				private0,
				private1,
				private2,
				private3,
				private4,
				reset,
				get_buffer,
				set_buffer,
				clear_buffer,
				private9,
				already_streamed,
				private11;
			dllname = "somestrm.dll";
		};
#endif /* __SOMIDL__ */
	};
	interface MemoryStreamIO :
		StreamIO
	{
#ifdef __SOMIDL__
		implementation
		{
			majorversion = 3;
			minorversion = 0;
			memory_management = corba;
	#ifdef __PRIVATE__
			seq_octet stream_buffer;
			unsigned long stream_position;		
			functionprefix="somestio_MemoryStreamIO_";
			override : 
				read_short,
				write_short,
				read_long,
				write_long,
				read_unsigned_short,
				write_unsigned_short,
				read_unsigned_long,
				write_unsigned_long,
				read_float,
				write_float,
				read_double,
				write_double,
				read_boolean,
				write_boolean,
				read_char,
				write_char,
				read_octet,
				write_octet,
				read_string,
				write_string,
				reset,
				get_buffer,
				set_buffer,
				clear_buffer,
				read_object,
				write_object,
				somInit,
				somUninit;
	#endif
			dllname = "somestrm.dll";
		};
#endif /* __SOMIDL__ */
	};
	interface Streamable :
		somOS::ServiceBase,
		CosStream::Streamable
	{
#ifdef __SOMIDL__
		implementation
		{
#ifdef __PRIVATE__
			functionprefix="somestio_Streamable_";
#endif
			majorversion = 3;
			minorversion = 0;
			memory_management = corba;
			dllname = "somestrm.dll";
		};
#endif /* __SOMIDL__ */
	};
	const long GENERAL=54000;
	const long SEMAPHORE_CREATE=54001;
	const long SEMAPHORE_REQUEST=54002;
	const long SEMAPHORE_RELEASE=54003;
	const long FACTORY_FINDER_LOAD=54004;
	const long FACTORY_FINDER_NEW=54005;
	const long FACTORY_FINDER_CLASS=54006;
	const long FACTORY_FINDER_METHOD=54007;
	const long FIND_FACTORY=54008;
	const long NEW_NOT_STREAMABLE=54009;
	const long OBJ_NOT_STREAMABLE=54010;
	const long FACTORY_FINDER=54011;
	const long METHOD_IS_ABSTRACT=54012;
	const long OBJ_REPEAT_REF_MISMATCH=54013;
	const long UNABLE_TO_CREATE_STREAMIO=54014;
	const long STREAM_CREATE_WITH_TYPES=54015;
	const long UNABLE_TO_CREATE_STREAM=54016;
	const long INVALID_KEY_LENGTH=54017;
	const long ALREADY_STREAMED_PARMS=54018;
	const long BAD_BUFFER_PARAMETER=54019;
	const long ICONV_FAILURE=54020;
	const long READ_PASSED_END_OF_STREAM=54021;
	const long REPEAT_REF_NUMBER_NOT_FOUND=54022;
	const long OBJ_NIL_DATA_MISMATCH=54023;
	const long OBJ_STRINGIFIED_REF_MISMATCH=54024;
	const long FOUND_UNKNOWN_TAG=54025;
	const long UNABLE_TO_READ_SHORT=54026;
	const long UNABLE_TO_READ_LONG=54027;
	const long UNABLE_TO_READ_USHORT=54028;
	const long UNABLE_TO_READ_ULONG=54029;
	const long UNABLE_TO_READ_STRING=54030;
	const long UNABLE_TO_READ_CHAR=54031;
	const long UNABLE_TO_READ_FLOAT=54032;
	const long UNABLE_TO_READ_DOUBLE=54033;
	const long UNABLE_TO_READ_OCTET=54034;
	const long UNABLE_TO_READ_BOOLEAN=54035;
	const long UNABLE_TO_READ_OBJECT=54036;
	const long READ_FROM_EMPTY_STREAM=54037;
};
#endif /* somestio_idl */
