#
# A Makefile for ANSI
# (c) osFree project,
# author, date
#

PROJ = help
DESC = Show help info

!include $(%ROOT)/mk/dosapp.mk

TARGETS  = $(PROJ).bat

$(PROJ).bat: .SYMBOLIC
 @%null
