# $Id: makefile,v 1.3 2004/08/16 04:51:13 prokushev Exp $

PROJ = shralias
DESC = SHRALIAS.EXE
srcfiles = $(p)shralias$(e)
ADD_COPT = -i=..$(SEP)include -ox
STUB        = $(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)os2stub.exe

!include $(%ROOT)/mk/appsos2.mk
