#
# A Makefile for mkmsgf
# (c) osFree project,
# valerius, 2006/10/30
#
# $Id: makefile,v 1.1 2004/08/16 06:27:30 prokushev Exp $
#

PROJ = mkmsgf
TRGT = $(PROJ).exe
DESC = Make message file tool
DEST = os2tk45$(SEP)bin

!include $(%ROOT)/mk/toolspas.mk
