#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

# before build command line tools build "shared" libraries
DIRS=lib

!include $(%ROOT)/mk/all.mk

#TARGETS = subdirs
#TARGET = all
