/**************************************************************************
 *
 *  Copyright 2015, 2017, 2018, Yuri Prokushev
 *
 *  This file is part of osFree project
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */


#ifndef scmeta_idl
#define scmeta_idl

#include <scentry.idl>
interface SOMTClassEntryC;

interface SOMTMetaClassEntryC : SOMTEntryC
{
  readonly attribute string somtMetaFile;
  // Returns the name of the file containing the definition of the
  // meta class named in this entry.

  readonly attribute SOMTClassEntryC somtMetaClassDef;
  // Returns the class definition entry for the meta class named in
  // this entry.

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_somtMetaFile,_get_somtMetaClassDef;
  
    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = scmeta;
#ifdef _WIN32
    dllname = "some.dll";
#endif
    callstyle = oidl;
  
    //# Method Modifiers
    //somtSetSymbolsOnEntry: override;
    //somDumpSelfInt: override;
  
    //# Attribute Modifiers
    somtMetaFile: nodata;
    somtMetaClassDef: nodata;
  
  };
#endif /* __SOMIDL__ */
};


#endif  /* scmeta_idl */
