/**************************************************************************
 *
 *  Copyright 2015, 2017, 2018, Yuri Prokushev
 *
 *  This file is part of osFree project
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

#ifndef scunion_idl
#define scunion_idl

#include <scentry.idl>

interface SOMTDataEntryC;

interface SOMTUnionEntryC : SOMTEntryC
{
#if 0
  struct somtLabelList {
    string label;
    somtLabelList *nextLabel;
  };
  // Linked list of case labels.

  struct somtCaseEntry {
    somtLabelList *caseLabels;  // The labels for this case.
    SOMTEntryC memberType;       // The type of the member.
    SOMTDataEntryC memberDeclarator; // The declarator for the member.
  };
  // A case for the union.
#endif
  readonly attribute SOMTEntryC somtSwitchType;
  // The switch type of the union.

//  somtCaseEntry *somtGetFirstCaseEntry();
  // The first case for the union.

//  somtCaseEntry *somtGetNextCaseEntry();
  // The next case for the union, relative to the previous
  // call to this method or to somtGetFirstCaseEntry.

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_somtSwitchType, somtGetFirstCaseEntry, somtGetNextCaseEntry;
  
    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = scunion;
#ifdef _WIN32
    dllname = "some.dll";
#endif
    callstyle = oidl;
  
    //# Method Modifiers
//    somDumpSelfInt: override;
    //somtSetSymbolsOnEntry: override;
  
    //# Attribute Modifiers
    somtSwitchType: nodata;

    /* passthru C_h_before = "#include <scentry.h>"; */


  };
#endif /* __SOMIDL__ */
};


#endif  /* scunion*/
