#
# A main Makefile for OS/3 boot sequence project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = libmmap os2386 GBM GDLib JpegLib libflac libmad libogg libojpeg libtiff &
  libvorbis lpng PDCurses zlib xwphelpers acpitk lvmtk

!include $(%ROOT)/mk/all.mk

#TARGETS = subdirs
#TARGET = all
