#
# A Makefile for UNIAPI
# (c) osFree project,
#

DESCRIPTION = Unified Interfaces to C/C++ header files converter
TARGET_CLASS = APPLICATION
TARGET_LANG = pascal
TARGET_API = HOST
TARGET_BITS = 32

!include $(%ROOT)tools/mk/build.mk
