/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef iogma_idl
#define iogma_idl
#include <somp.idl>
#include <somobj.idl>
#include <somperrd.idl>
interface SOMPMediaInterfaceAbstract;
interface SOMPIOGroup;
interface SOMPPersistentId;
interface SOMPPersistentObject;
interface SOMPIOGroupMgrAbstract;
interface SOMPIOGroupMgrAbstract :
	SOMObject
{
	void sompNewMediaInterface(
		in string IOInfo)
			raises (SOMPError::sompException);
	SOMPMediaInterfaceAbstract sompGetMediaInterface();
	void sompFreeMediaInterface();
	SOMPMediaInterfaceAbstract sompInstantiateMediaInterface();
	boolean sompWriteGroup(
		in SOMPPersistentObject thisPo)
			raises (SOMPError::sompException);
	SOMPPersistentObject sompReadGroup(
		in SOMPPersistentId objectID)
			raises (SOMPError::sompException);
	void sompReadObjectData(
		in SOMPPersistentObject thisPo)
			raises (SOMPError::sompException);
	boolean sompGroupExists(
		in string IOInfo);
	boolean sompObjectInGroup(
		in SOMPPersistentId objectID)
			raises (SOMPError::sompException);
	boolean sompMediaFormatOk(
		in string mediaFormatName);
	void sompDeleteObjectFromGroup(
		in SOMPPersistentId objectID)
			raises (SOMPError::sompException);
#ifdef __SOMIDL__
	implementation
	{
		callstyle = idl;
		dllname = "somp.dll";
		releaseorder : 
			sompNewMediaInterface,
			sompGetMediaInterface,
			sompFreeMediaInterface,
			sompInstantiateMediaInterface,
			sompWriteGroup,
			sompReadGroup,
			sompReadObjectData,
			sompGroupExists,
			sompObjectInGroup,
			sompMediaFormatOk,
			sompDeleteObjectFromGroup;
		majorversion = 2;
		minorversion = 1;
		filestem = iogma;
#ifdef __PRIVATE__
		functionprefix = iogma_;
#endif
	};
#endif /* __SOMIDL__ */
};
#endif /* iogma_idl */
