/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef mia_idl
#define mia_idl
#include <somobj.idl>
#include <somp.idl>
#include <somperrd.idl>
interface SOMPMediaInterfaceAbstract;
interface SOMPMediaInterfaceAbstract :
	SOMObject
{
	void sompOpen()
			raises (SOMPError::sompException);
	void sompClose()
			raises (SOMPError::sompException);
#ifdef __SOMIDL__
	implementation
	{
		callstyle = idl;
		dllname = "somp.dll";
		majorversion = 2;
		minorversion = 1;
		releaseorder : sompOpen,sompClose;
		filestem = mia;
#ifdef __PRIVATE__
		functionprefix = mia_;
#endif
	};
#endif /* __SOMIDL__ */
};
#endif /* mia_idl */
