#
# A main Makefile for OS/3 boot sequence project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = bootsect mbr fatboot eltorito

!include $(%ROOT)/mk/loader.mk

# this implies do $(MAKE) $(MAKEOPT) TARGET=all subdirs
TARGETS      = subdirs
TARGET       = all
