# $Id: makefile,v 1.3 2004/08/16 04:51:12 prokushev Exp $
#

ADD_COPT = -i=$(MYDIR)..$(SEP)include -i=$(MYDIR)..$(SEP)..$(SEP)include
DEST     = none
UNI2H = 1

!include $(%ROOT)/mk/appsos2.mk

TARGETS = $(PATH)istring.$(O)
