# $Id: makefile,v 1.3 2004/08/21 14:49:22 prokushev Exp $
#
# Makefile for common shared libs

#

PROJ     = ow_dlfcn

!include $(%ROOT)/mk/appsos2.mk

$(PATH)$(PROJ).obj:

DEST     = none
TARGETS  = $(PATH)$(PROJ).obj # subdirs
