# $Id: makefile,v 1.3 2004/08/21 14:49:22 prokushev Exp $
#
# Makefile for common shared libs

#

PROJ     = ow_dlfcn
DEST     =

!include $(%ROOT)/mk/appsos2.mk

TARGETS  = $(PATH)$(PROJ).obj # subdirs
