#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

# before build command line tools build "shared" libraries
DIRS = test01 &
       test02 &
       test03 &
       test04 &
       test05 &
       test06 &
       test07 &
       test08 &
       test09 &
       test10 &
       test11 &
       test12 &
       test13 &
       test14 &
       test15 &
       test16 &
       test17 &
       test18 &
       test19 &
       test20 &
       test21 &
       test22 &
       test23 &
       test24 &
       test25 &
       test26 &
       test27 &
       test28 &
       test29 &
       test30 &
#       test31 &
       test32 &
       test33 &
       test34 &
       test35 &
       test36 &
       test37 &
       test38 &
       test39 &
       test40 &
       test41 &
       test42 &
       test43 &
       test44 &
       test45 &
#       test46 &
       test47 &
       test48 &
       test49 &
       test50 &
       test51 &
#       test52 &
       test53 &
       test54 &
       test55 &
       test56 &
       test57 &
       test58 &
       test59 &
       test60 &
       test61 &
#       test62 &
       test63 &
       test64 &
       test65 &
       test66 &
       test67 &
       test68 &
       test69 &
       test70 &
       test71 &
       test72 &
       test73 &
       test74 &
       test75 &
       test76 &
       test77 &
       test78 &
       test79 &
       test80 &
       test81 &
       test82 &
       test83 &
       test84 &
       test85 &
       test86 &
       test87 &
       test88 &
#       test89 &
       test90 &
       test91 &
       test92 &
       test93 &
       test94 &
       test95 &
       test96 &
       test97 &
       test98 &
       test99 &
       test101 &
       test102 &
       test103 &
       test104 &
       test105 &
#       test106 &
       test107 &
       test108 &
       test109 &
       test110 &
       test111 &
       test112 &
       test113 &
       test114 &
       test115 &
       test116 &
       test117 &
       test118 &
       test119 &
       test120 &
       test121 &
       test122 &
       test123 &
       test124 &
       test125 &
       test126 &
       test127 &
       test128 &
       test129 &
       test130 &
       test131 &
       test132 &
       test133 &
       test134 &
       test135 &
       test136 &
#       test137 &
#       test138 &
       test139 &
       test140 &
       test141 &
       test142 &
       test143 &
       test144 &
       test145 &
       test146 &
       test147 &
       test148 &
       test149 &
       test150 &
       test151 &
       test152 &
       test153 &
       test154 &
       test155 &
       test156 &
       test157 &
       test158 &
       test159 &
       test160 &
       test161 &
       test162 &
       test163 &
       test164 &
       test165 &
       test166 &
       test167 &
       test168 &
       test169 &
       test170 &
       test171 &
       test172 &
       test173 &
       test174 &
       test175 &
       test176 &
       test177 &
       test178 &
       test179 &
#       test180 &
#       test181 &
       test182 &
       test183 &
       test184 &
       test185 &
       test186 &
       test187 &
       test188 &
       test189 &
       test190 &
       test191 &
       test192 &
       test193 &
       test194 &
       test195 &
       test196 &
       test197 &
#       test198 &
       test199 &
       test311

!include $(%ROOT)/mk/all.mk

#TARGETS = subdirs
#TARGET = all
