#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

# before build command line tools build "shared" libraries
DIRS = test01 &
       test02 &
       test03 &
       test04 &
       test05 &
       test06 &
       test07 &
       test08 &
       test09 &
       test10 &
       test11 &
       test12 &
       test13 &
       test14 &
       test15 &
       test16 &
       test17 &
       test18 &
       test19 &
       test20 &
       test21 &
       test22 &
       test23 &
       test24 &
       test25 &
       test26 &
       test27 &
       test28 &
       test29 &
       test30 &
       test311

!include $(%ROOT)/mk/all.mk

#TARGETS = subdirs
#TARGET = all
