#
# A main Makefile for MM
# (c) osFree project,
#

DIRS = shared ampmxmcd audioif audiomcd audiosh fssh indeor31 midiio midimcd &
       mish mmbit mmio mmshd ssm waveproc

!include $(%ROOT)tools/mk/all.mk

#TARGETS = subdirs
#TARGET = all
