#!/bin/sh
#
#


if   [ ! -x preldr0 ]; then
   wmake preldr0
fi

if   [ ! -x iso9660.fsd ]; then
   wmake iso9660.fsd
fi

cd   ../bootsec/eltorito

if   [ ! -x eltorito.bin ]; then
   wmake eltorito.bin
fi

cd   ../../preldr/
cp ../bootsec/eltorito/eltorito.bin .
rexx mkboot.cmd eltorito.bin preldr0 iso9660.fsd bootblk
mv bootblk ../../../cd/boot
cp preldr0 ../../../cd/boot/freeldr
cp preldr.ini ../../../cd/boot/freeldr
cp *.fsd   ../../../cd/boot/freeldr/fsd
cp *.rel   ../../../cd/boot/freeldr/fsd
mv ../../../cd/boot/freeldr/fsd/preldr0.rel ../../../cd/boot/freeldr/
cp freeldr    ../../../cd/boot/freeldr
cp boot_linux ../../../cd/boot/freeldr
cd   ../../..
mkisofs -b boot/bootblk -c boot/bootcat.bin -no-emul-boot -boot-load-size 8 -boot-info-table -iso-level 3 -allow-lowercase -no-iso-translate -r -J -publisher "osFree (www.osfree.org)" -o osfree.iso cd
mv osfree.iso /mnt/i/data/vm/bochs/img
cd   osfree/bootseq/preldr
