# $Id: makefile,v 1.1 2000/04/21 10:57:52 ktk Exp $
#
#  JFS Makefile for the src directory.
#

allall: all

all dep clean:
    @cd jfs
    @echo Entering directory: .\src\jfs
    $(MAKE) /nologo $@
    @cd ..
    @echo Entering directory: .\src

