#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

srcfiles = $(p)framemgr$(e)
ADD_COPT = -i=$(MYDIR)..$(SEP)include

!include $(%ROOT)/mk/appsos2_fpm.mk

DEST = none
TARGETS = $(OBJS)
