#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

srcfiles = $(p)framemgr$(e)
ADD_COPT = -i=$(MYDIR)..$(SEP)include
DEST =

!include $(%ROOT)/mk/appsos2.mk

TARGETS = $(OBJS)
