/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

#ifndef SOM_Module_wpfsys_Source
#define SOM_Module_wpfsys_Source
#endif
#define WPFileSystem_Class_Source
#define M_WPFileSystem_Class_Source

#define INCL_PMWP
#include <os2.h>

#include "wpfsys.ih"


SOM_Scope BOOL  SOMLINK fs_wpSetRealName(WPFileSystem *somSelf, 
                                         PSZ pszName)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetRealName");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpSetType(WPFileSystem *somSelf, PSZ pszTypes, 
                                     PFEA2LIST pfeal)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetType");

    /* Return statement to be customized: */
    return;
}

SOM_Scope PSZ  SOMLINK fs_wpQueryType(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryType");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpSetAttr(WPFileSystem *somSelf, ULONG attrFile)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetAttr");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpQueryAttr(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryAttr");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpAddFile1Page(WPFileSystem *somSelf, 
                                           HWND hwndNotebook)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpAddFile1Page");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpAddFile2Page(WPFileSystem *somSelf, 
                                           HWND hwndNotebook)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpAddFile2Page");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpAddFile3Page(WPFileSystem *somSelf, 
                                           HWND hwndNotebook)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpAddFile3Page");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpAddFileMenuPage(WPFileSystem *somSelf, 
                                              HWND hwndNotebook)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpAddFileMenuPage");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpQueryCreation(WPFileSystem *somSelf, 
                                            FDATE* fdate, FTIME* ftime)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryCreation");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpQueryLastAccess(WPFileSystem *somSelf, 
                                              FDATE* fdate, FTIME* ftime)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryLastAccess");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpQueryLastWrite(WPFileSystem *somSelf, 
                                             FDATE* fdate, FTIME* ftime)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryLastWrite");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpQueryFileSize(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryFileSize");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpQueryEASize(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryEASize");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpSetDateInfo(WPFileSystem *somSelf, 
                                          FILEFINDBUF4* pstFileFindBuf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetDateInfo");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpSetFileSizeInfo(WPFileSystem *somSelf, 
                                              ULONG cbFileSize, 
                                              ULONG cbEASize)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetFileSizeInfo");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpRefresh(WPFileSystem *somSelf, ULONG ulView, 
                                     PVOID pReserved)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpRefresh");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpQueryRefreshFlags(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryRefreshFlags");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpSetRefreshFlags(WPFileSystem *somSelf, 
                                             ULONG ulRefreshFlags)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetRefreshFlags");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpPrintPlainTextFile(WPFileSystem *somSelf, 
                                                PPRINTDEST pPrintDest)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpPrintPlainTextFile");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpSetTitleAndRenameFile(WPFileSystem *somSelf, 
                                                   PSZ pszNewTitle, 
                                                   ULONG fConfirmations)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetTitleAndRenameFile");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpConfirmRenameFileWithExt(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpConfirmRenameFileWithExt");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpVerifyUpdateAccess(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpVerifyUpdateAccess");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpAddUserItemsToPopupMenu(WPFileSystem *somSelf, 
                                                     HWND hwndMenu, 
                                                     HWND hwndCnr, 
                                                     ULONG iPosition)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpAddUserItemsToPopupMenu");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpIsDiskSwapped(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpIsDiskSwapped");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpQueryRealName(WPFileSystem *somSelf, 
                                           PSZ pszFilename, PULONG pcb, 
                                           BOOL fQualified)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryRealName");

    /* Return statement to be customized: */
    return;
}

SOM_Scope PSZ  SOMLINK fs_wpQueryFilename(WPFileSystem *somSelf, 
                                          PSZ pszFilename, BOOL fQualified)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryFilename");

    /* Return statement to be customized: */
    return;
}

SOM_Scope WPFileSystem*  SOMLINK fs_wpQueryDisk(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryDisk");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpQueryDateInfo(WPFileSystem *somSelf, 
                                            FILEFINDBUF4* pstFileFindBuf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryDateInfo");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK fs_wpConfirmKeepAssoc(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpConfirmKeepAssoc");

    /* Return statement to be customized: */
    return;
}

SOM_Scope void  SOMLINK fs_wpQueryFileSizeL(WPFileSystem *somSelf, 
                                            PLONGLONG pllFileSize)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryFileSizeL");

}

SOM_Scope ULONG  SOMLINK fs_wpSetFileSizeL(WPFileSystem *somSelf, 
                                           PLONGLONG pllFileSize)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetFileSizeL");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpRefreshFSInfo(WPFileSystem *somSelf, 
                                           ULONG ulView, PVOID pReserved, 
                                           ULONG ulUnknown)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpRefreshFSInfo");

    /* Return statement to be customized: */
    return;
}

SOM_Scope PVOID  SOMLINK fs_wpQueryDriveData(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryDriveData");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpSetNewRealName(WPFileSystem *somSelf, 
                                            PSZ pszNewRealName)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetNewRealName");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK fs_wpAdoptNewRealName(WPFileSystem *somSelf, 
                                              BOOL fRecurse)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpAdoptNewRealName");

    /* Return statement to be customized: */
    return;
}

SOM_Scope void  SOMLINK fs_wpUnInitData(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpUnInitData");

    WPFileSystem_parent_WPObject_wpUnInitData(somSelf);
}

SOM_Scope HOBJECT  SOMLINK fs_wpQueryHandle(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryHandle");

    return (WPFileSystem_parent_WPObject_wpQueryHandle(somSelf));
}

SOM_Scope BOOL  SOMLINK fs_wpSaveImmediate(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSaveImmediate");

    return (WPFileSystem_parent_WPObject_wpSaveImmediate(somSelf));
}

SOM_Scope ULONG  SOMLINK fs_wpFilterPopupMenu(WPFileSystem *somSelf, 
                                              ULONG ulFlags, 
                                              HWND hwndCnr, BOOL fMultiSelect)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpFilterPopupMenu");

    return (WPFileSystem_parent_WPObject_wpFilterPopupMenu(somSelf, 
                                                           ulFlags, 
                                                           hwndCnr, 
                                                           fMultiSelect));
}

SOM_Scope BOOL  SOMLINK fs_wpSetTitle(WPFileSystem *somSelf, 
                                      PSZ pszNewTitle)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetTitle");

    return (WPFileSystem_parent_WPObject_wpSetTitle(somSelf, 
                                                    pszNewTitle));
}

SOM_Scope HWND  SOMLINK fs_wpViewObject(WPFileSystem *somSelf, 
                                        HWND hwndCnr, ULONG ulView, 
                                        ULONG param)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpViewObject");

    return (WPFileSystem_parent_WPObject_wpViewObject(somSelf, 
                                                      hwndCnr, 
                                                      ulView, 
                                                      param));
}

SOM_Scope BOOL  SOMLINK fs_wpSwitchTo(WPFileSystem *somSelf, 
                                      ULONG View)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSwitchTo");

    return (WPFileSystem_parent_WPObject_wpSwitchTo(somSelf, 
                                                    View));
}

SOM_Scope BOOL  SOMLINK fs_wpAddSettingsPages(WPFileSystem *somSelf, 
                                              HWND hwndNotebook)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpAddSettingsPages");

    return (WPFileSystem_parent_WPObject_wpAddSettingsPages(somSelf, 
                                                            hwndNotebook));
}

SOM_Scope WPObject*  SOMLINK fs_wpCopyObject(WPFileSystem *somSelf, 
                                             WPFolder* Folder, 
                                             BOOL fLock)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpCopyObject");

    return (WPFileSystem_parent_WPObject_wpCopyObject(somSelf, 
                                                      Folder, 
                                                      fLock));
}

SOM_Scope WPObject*  SOMLINK fs_wpCreateFromTemplate(WPFileSystem *somSelf, 
                                                     WPFolder* folder, 
                                                     BOOL fLock)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpCreateFromTemplate");

    return (WPFileSystem_parent_WPObject_wpCreateFromTemplate(somSelf, 
                                                              folder, 
                                                              fLock));
}

SOM_Scope BOOL  SOMLINK fs_wpMoveObject(WPFileSystem *somSelf, 
                                        WPFolder* Folder)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpMoveObject");

    return (WPFileSystem_parent_WPObject_wpMoveObject(somSelf, 
                                                      Folder));
}

SOM_Scope HPOINTER  SOMLINK fs_wpQueryIcon(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryIcon");

    return (WPFileSystem_parent_WPObject_wpQueryIcon(somSelf));
}

SOM_Scope ULONG  SOMLINK fs_wpQueryIconData(WPFileSystem *somSelf, 
                                            PICONINFO pIconInfo)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryIconData");

    return (WPFileSystem_parent_WPObject_wpQueryIconData(somSelf, 
                                                         pIconInfo));
}

SOM_Scope BOOL  SOMLINK fs_wpSetIconData(WPFileSystem *somSelf, 
                                         PICONINFO pIconInfo)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetIconData");

    return (WPFileSystem_parent_WPObject_wpSetIconData(somSelf, 
                                                       pIconInfo));
}

SOM_Scope ULONG  SOMLINK fs_wpQueryDetailsData(WPFileSystem *somSelf, 
                                               PVOID* ppDetailsData, 
                                               PULONG pcp)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryDetailsData");

    return (WPFileSystem_parent_WPObject_wpQueryDetailsData(somSelf, 
                                                            ppDetailsData, 
                                                            pcp));
}

SOM_Scope BOOL  SOMLINK fs_wpModifyPopupMenu(WPFileSystem *somSelf, 
                                             HWND hwndMenu, HWND hwndCnr, 
                                             ULONG iPosition)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpModifyPopupMenu");

    return (WPFileSystem_parent_WPObject_wpModifyPopupMenu(somSelf, 
                                                           hwndMenu, 
                                                           hwndCnr, 
                                                           iPosition));
}

SOM_Scope BOOL  SOMLINK fs_wpSaveState(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSaveState");

    return (WPFileSystem_parent_WPObject_wpSaveState(somSelf));
}

SOM_Scope BOOL  SOMLINK fs_wpRestoreState(WPFileSystem *somSelf, 
                                          ULONG ulReserved)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpRestoreState");

    return (WPFileSystem_parent_WPObject_wpRestoreState(somSelf, 
                                                        ulReserved));
}

SOM_Scope BOOL  SOMLINK fs_wpMenuItemSelected(WPFileSystem *somSelf, 
                                              HWND hwndFrame, 
                                              ULONG ulMenuId)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpMenuItemSelected");

    return (WPFileSystem_parent_WPObject_wpMenuItemSelected(somSelf, 
                                                            hwndFrame, 
                                                            ulMenuId));
}

SOM_Scope HWND  SOMLINK fs_wpOpen(WPFileSystem *somSelf, HWND hwndCnr, 
                                  ULONG ulView, ULONG param)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpOpen");

    return (WPFileSystem_parent_WPObject_wpOpen(somSelf, hwndCnr, 
                                                ulView, param));
}

SOM_Scope MRESULT  SOMLINK fs_wpDraggedOverObject(WPFileSystem *somSelf, 
                                                  WPObject* DraggedOverObject)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpDraggedOverObject");

    return (WPFileSystem_parent_WPObject_wpDraggedOverObject(somSelf, 
                                                             DraggedOverObject));
}

SOM_Scope BOOL  SOMLINK fs_wpDroppedOnObject(WPFileSystem *somSelf, 
                                             WPObject* DroppedOnObject)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpDroppedOnObject");

    return (WPFileSystem_parent_WPObject_wpDroppedOnObject(somSelf, 
                                                           DroppedOnObject));
}

SOM_Scope BOOL  SOMLINK fs_wpFormatDragItem(WPFileSystem *somSelf, 
                                            PDRAGITEM pdrgItem)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpFormatDragItem");

    return (WPFileSystem_parent_WPObject_wpFormatDragItem(somSelf, 
                                                          pdrgItem));
}

SOM_Scope ULONG  SOMLINK fs_wpQueryNameClashOptions(WPFileSystem *somSelf, 
                                                    ULONG menuID)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryNameClashOptions");

    return (WPFileSystem_parent_WPObject_wpQueryNameClashOptions(somSelf, 
                                                                 menuID));
}

SOM_Scope BOOL32  SOMLINK fs_wpAppendObject(WPFileSystem *somSelf, 
                                            WPObject* targetObject, 
                                            BOOL32 fMove)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpAppendObject");

    return (WPFileSystem_parent_WPObject_wpAppendObject(somSelf, 
                                                        targetObject, 
                                                        fMove));
}

SOM_Scope BOOL32  SOMLINK fs_wpReplaceObject(WPFileSystem *somSelf, 
                                             WPObject* targetObject, 
                                             BOOL32 fMove)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpReplaceObject");

    return (WPFileSystem_parent_WPObject_wpReplaceObject(somSelf, 
                                                         targetObject, 
                                                         fMove));
}

SOM_Scope ULONG  SOMLINK fs_wpQueryStyle(WPFileSystem *somSelf)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpQueryStyle");

    return (WPFileSystem_parent_WPObject_wpQueryStyle(somSelf));
}

SOM_Scope BOOL  SOMLINK fs_wpSetStyle(WPFileSystem *somSelf, 
                                      ULONG ulNewStyle)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpSetStyle");

    return (WPFileSystem_parent_WPObject_wpSetStyle(somSelf, 
                                                    ulNewStyle));
}

SOM_Scope BOOL  SOMLINK fs_wpDoesObjectMatch(WPFileSystem *somSelf, 
                                             PVOID pvoidExtendedCriteria)
{
    /* WPFileSystemData *somThis = WPFileSystemGetData(somSelf); */
    WPFileSystemMethodDebug("WPFileSystem","fs_wpDoesObjectMatch");

    return (WPFileSystem_parent_WPObject_wpDoesObjectMatch(somSelf, 
                                                           pvoidExtendedCriteria));
}

SOM_Scope void SOMLINK fs_somDefaultInit(WPFileSystem *somSelf, 
                                         somInitCtrl* ctrl)
{
    WPFileSystemData *somThis; /* set in BeginInitializer */
    somInitCtrl globalCtrl;
    somBooleanVector myMask;
    WPFileSystemMethodDebug("WPFileSystem","somDefaultInit");
    WPFileSystem_BeginInitializer_somDefaultInit;

    WPFileSystem_Init_WPObject_somDefaultInit(somSelf, ctrl);

    /*
     * local WPFileSystem initialization code added by programmer
     */
}


SOM_Scope void SOMLINK fs_somDestruct(WPFileSystem *somSelf, 
                                      octet doFree, somDestructCtrl* ctrl)
{
    WPFileSystemData *somThis; /* set in BeginDestructor */
    somDestructCtrl globalCtrl;
    somBooleanVector myMask;
    WPFileSystemMethodDebug("WPFileSystem","fs_somDestruct");
    WPFileSystem_BeginDestructor;

    /*
     * local WPFileSystem deinitialization code added by programmer
     */

    WPFileSystem_EndDestructor;
}



SOM_Scope WPObject*  SOMLINK fsM_wpclsQueryAwakeObject(M_WPFileSystem *somSelf, 
                                                       PSZ pszInputPath)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsQueryAwakeObject");

    /* Return statement to be customized: */
    return;
}

SOM_Scope WPObject*  SOMLINK fsM_wpclsFileSysExists(M_WPFileSystem *somSelf, 
                                                    WPFolder* Folder, 
                                                    PSZ pszFilename, 
                                                    ULONG attrFile)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsFileSysExists");

    /* Return statement to be customized: */
    return;
}

SOM_Scope WPObject*  SOMLINK fsM_wpclsQueryObjectFromPath(M_WPFileSystem *somSelf, 
                                                          PSZ pszFQPath)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsQueryObjectFromPath");

    /* Return statement to be customized: */
    return;
}

SOM_Scope PSZ  SOMLINK fsM_wpclsQueryInstanceType(M_WPFileSystem *somSelf)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsQueryInstanceType");

    /* Return statement to be customized: */
    return;
}

SOM_Scope PSZ  SOMLINK fsM_wpclsQueryInstanceFilter(M_WPFileSystem *somSelf)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsQueryInstanceFilter");

    /* Return statement to be customized: */
    return;
}

SOM_Scope void  SOMLINK fsM_wpclsInitData(M_WPFileSystem *somSelf)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsInitData");

    M_WPFileSystem_parent_M_WPObject_wpclsInitData(somSelf);
}

SOM_Scope PSZ  SOMLINK fsM_wpclsQueryTitle(M_WPFileSystem *somSelf)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsQueryTitle");

    return (M_WPFileSystem_parent_M_WPObject_wpclsQueryTitle(somSelf));
}

SOM_Scope ULONG  SOMLINK fsM_wpclsQueryDetailsInfo(M_WPFileSystem *somSelf, 
                                                   PCLASSFIELDINFO* ppClassFieldInfo, 
                                                   PULONG pSize)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsQueryDetailsInfo");

    return (M_WPFileSystem_parent_M_WPObject_wpclsQueryDetailsInfo(somSelf, 
                                                                   ppClassFieldInfo, 
                                                                   pSize));
}

SOM_Scope void  SOMLINK fsM_wpclsQuerySearchInfo(M_WPFileSystem *somSelf, 
                                                 M_WPObject** ClassExtended, 
                                                 M_WPObject** ClassCreate, 
                                                 PULONG pulClassCriteriaSize)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsQuerySearchInfo");

    M_WPFileSystem_parent_M_WPObject_wpclsQuerySearchInfo(somSelf, 
                                                          ClassExtended, 
                                                          ClassCreate, 
                                                          pulClassCriteriaSize);
}

SOM_Scope BOOL  SOMLINK fsM_wpclsQueryExtendedCriteria(M_WPFileSystem *somSelf, 
                                                       PSZ pszName, 
                                                       ULONG ulSearchType, 
                                                       PVOID pvoidExtendedCriteria)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsQueryExtendedCriteria");

    return (M_WPFileSystem_parent_M_WPObject_wpclsQueryExtendedCriteria(somSelf, 
                                                                        pszName, 
                                                                        ulSearchType, 
                                                                        pvoidExtendedCriteria));
}

SOM_Scope WPObject*  SOMLINK fsM_wpclsNew(M_WPFileSystem *somSelf, 
                                          PSZ pszTitle, PSZ pszSetupEnv, 
                                          WPFolder* Folder, BOOL fLock)
{
    /* M_WPFileSystemData *somThis = M_WPFileSystemGetData(somSelf); */
    M_WPFileSystemMethodDebug("M_WPFileSystem","fsM_wpclsNew");

    return (M_WPFileSystem_parent_M_WPObject_wpclsNew(somSelf, 
                                                      pszTitle, 
                                                      pszSetupEnv, 
                                                      Folder, 
                                                      fLock));
}

