/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

#ifndef SOM_Module_wpsound_Source
#define SOM_Module_wpsound_Source
#endif
#define WPSound_Class_Source
#define M_WPSound_Class_Source

#define INCL_PMWP
#include <os2.h>

#include "wpsound.ih"


SOM_Scope ULONG  SOMLINK sou_wpAddSoundWarningBeepPage(WPSound *somSelf, 
                                                       HWND hwndNotebook)
{
    /* WPSoundData *somThis = WPSoundGetData(somSelf); */
    WPSoundMethodDebug("WPSound","sou_wpAddSoundWarningBeepPage");

    /* Return statement to be customized: */
    return;
}

SOM_Scope ULONG  SOMLINK sou_wpAddSoundSchemePage(WPSound *somSelf, 
                                                  HWND hwndNotebook)
{
    /* WPSoundData *somThis = WPSoundGetData(somSelf); */
    WPSoundMethodDebug("WPSound","sou_wpAddSoundSchemePage");

    /* Return statement to be customized: */
    return;
}

SOM_Scope BOOL  SOMLINK sou_wpAddSettingsPages(WPSound *somSelf, 
                                               HWND hwndNotebook)
{
    /* WPSoundData *somThis = WPSoundGetData(somSelf); */
    WPSoundMethodDebug("WPSound","sou_wpAddSettingsPages");

    return (WPSound_parent_WPAbstract_wpAddSettingsPages(somSelf, 
                                                         hwndNotebook));
}

SOM_Scope ULONG  SOMLINK sou_wpAddObjectWindowPage(WPSound *somSelf, 
                                                   HWND hwndNotebook)
{
    /* WPSoundData *somThis = WPSoundGetData(somSelf); */
    WPSoundMethodDebug("WPSound","sou_wpAddObjectWindowPage");

    return (WPSound_parent_WPAbstract_wpAddObjectWindowPage(somSelf, 
                                                            hwndNotebook));
}

SOM_Scope BOOL  SOMLINK sou_wpFilterPopupMenu(WPSound *somSelf,  ULONG ulFlags,
                                                 HWND hwndCnr,
                                                 BOOL fMultiSelect)
{
    /* WPSoundData *somThis = WPSoundGetData(somSelf); */
    WPSoundMethodDebug("WPSound","sou_wpFilterPopupMenu");

    return (WPSound_parent_WPAbstract_wpFilterPopupMenu(somSelf,  ulFlags,
                                                 hwndCnr,
                                                 fMultiSelect));
}

SOM_Scope void SOMLINK sou_somDefaultInit(WPSound *somSelf, somInitCtrl* ctrl)
{
    WPSoundData *somThis; /* set in BeginInitializer */
    somInitCtrl globalCtrl;
    somBooleanVector myMask;
    WPSoundMethodDebug("WPSound","somDefaultInit");
    WPSound_BeginInitializer_somDefaultInit;

    WPSound_Init_WPAbstract_somDefaultInit(somSelf, ctrl);

    /*
     * local WPSound initialization code added by programmer
     */
}


SOM_Scope void SOMLINK sou_somDestruct(WPSound *somSelf, octet doFree, 
                                       somDestructCtrl* ctrl)
{
    WPSoundData *somThis; /* set in BeginDestructor */
    somDestructCtrl globalCtrl;
    somBooleanVector myMask;
    WPSoundMethodDebug("WPSound","sou_somDestruct");
    WPSound_BeginDestructor;

    /*
     * local WPSound deinitialization code added by programmer
     */

    WPSound_EndDestructor;
}



SOM_Scope PSZ  SOMLINK souM_wpclsQueryTitle(M_WPSound *somSelf)
{
    /* M_WPSoundData *somThis = M_WPSoundGetData(somSelf); */
    M_WPSoundMethodDebug("M_WPSound","souM_wpclsQueryTitle");

    return (M_WPSound_parent_M_WPAbstract_wpclsQueryTitle(somSelf));
}

SOM_Scope BOOL  SOMLINK souM_wpclsQueryDefaultHelp(M_WPSound *somSelf, 
                                                   PULONG pHelpPanelId, 
                                                   PSZ pszHelpLibrary)
{
    /* M_WPSoundData *somThis = M_WPSoundGetData(somSelf); */
    M_WPSoundMethodDebug("M_WPSound","souM_wpclsQueryDefaultHelp");

    return (M_WPSound_parent_M_WPAbstract_wpclsQueryDefaultHelp(somSelf, 
                                                                pHelpPanelId, 
                                                                pszHelpLibrary));
}

SOM_Scope ULONG  SOMLINK souM_wpclsQueryDefaultView(M_WPSound *somSelf)
{
    /* M_WPSoundData *somThis = M_WPSoundGetData(somSelf); */
    M_WPSoundMethodDebug("M_WPSound","souM_wpclsQueryDefaultView");

    return (M_WPSound_parent_M_WPAbstract_wpclsQueryDefaultView(somSelf));
}

SOM_Scope ULONG  SOMLINK souM_wpclsQueryStyle(M_WPSound *somSelf)
{
    /* M_WPSoundData *somThis = M_WPSoundGetData(somSelf); */
    M_WPSoundMethodDebug("M_WPSound","souM_wpclsQueryStyle");

    return (M_WPSound_parent_M_WPAbstract_wpclsQueryStyle(somSelf));
}

SOM_Scope ULONG  SOMLINK souM_wpclsQueryIconData(M_WPSound *somSelf, 
                                                 PICONINFO pIconInfo)
{
    /* M_WPSoundData *somThis = M_WPSoundGetData(somSelf); */
    M_WPSoundMethodDebug("M_WPSound","souM_wpclsQueryIconData");

    return (M_WPSound_parent_M_WPAbstract_wpclsQueryIconData(somSelf, 
                                                             pIconInfo));
}

