#  Makefile for shared objects
#
#  osFree project, 2007, prokushev

PROJ = stub
TRGT = $(PROJ).$(O)
DESC = The empty file for creating forwarder DLLs
srcfiles = $(p)stub$(e)
ADD_COPT=-bm -od -mf -sg -d2 -mf
#DEST = none

!include $(%ROOT)/mk/appsos2_cmd.mk

TARGETS = $(OBJS)
