#####################################################################
#
#  @(#)makefile	1.3 	3/22/95 11:54:59
#
#  Copyright (c) 1995, Willows Software Inc.  All rights reserved.
#
#####################################################################

include $(TWINDIR)/Makefile.config

project		= treeview
components	= TViewApp.o TVDialog.o TViewApp.res.o
libraries	= 
linklibs	= -lshell$(TWIN_APISIZE) -lcommctrl32
resource	= TViewApp
resource_depend = willows.ico

include $(TWINDIR)/makeinclude/makefile$(TWIN_APISIZE).inc

#####################################################################
# user makefile definitions for libraries are placed below
#####################################################################

clean-libs:

