DIRS = fat32 ifs

all: .SYMBOLIC 
 @for %d in ($(DIRS)) do if exist %d @cd %d && wmake -f makefile.wcc

clean: .symbolic
 @for %d in ($(DIRS)) do if exist %d @cd %d && wmake -f makefile.wcc clean
