#
# A Makefile for ANSI
# (c) osFree project,
# author, date
#

PROJ = more
DESC = Show stdin to stdout. One screen at one time.
#defines object file names in format objname.$(O)
srcfiles = $(p)more$(e)
# defines additional options for C compiler
ADD_COPT = -i=..\include
STUB=$(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)$(PROJ).exe

!include $(%ROOT)/mk/appsos2.mk
