# RegMath, math libraries for Regina
# Copyright 1998-2001 Patrick TJ McPhee
# Distributed under the terms of the Mozilla Public Licence
# You can obtain a copy of the licence at http://www.mozilla.org/MPL
# The Original Code is regmath
# The Initial Developer is Patrick TJ McPhee
# $Header: C:/ptjm/rexx/math/tmp/RCS/Makefile.nt 1.2 2001/11/04 19:34:33 ptjm Exp $

DEBUG=-Zi
DOPT=-Ox -G5
INCDIR=../Regina
LIBDIR=..\Regina
CFLAGS=$(OPT) $(DEBUG) -nologo -GF -I$(INCDIR) -MD
LDFLAGS=-LD $(OPT) $(DEBUG) -MD
LIBS=$(LIBDIR)\regina.lib
CC=cl

.SUFFIXES : .c .obj

all : rexxmath.dll rxmath.dll

dist :
	$(MAKE) $(MAKEFLAGS) OPT="$(DOPT)" DEBUG="" all


rexxmath.dll : rexxmath.obj rexxmath.def
	$(CC) $(LDFLAGS) rexxmath.obj $(LIBS) rexxmath.def -Fe$(LIBFILE)

rxmath.dll : rxmath.obj rxmath.def
	$(CC) $(LDFLAGS) rxmath.obj $(LIBS) rxmath.def -Fe$(LIBFILE)

.c.obj :
	$(CC) $(CFLAGS) -c $<


clean:
	-del *.obj *.dll

