# $Id: makefile,v 1.2 2004/08/16 04:51:11 prokushev Exp $

PROJ = cmdref
PROJ2 = external
DEST    = os2$(SEP)book

!include $(%ROOT)/mk/appsos2.mk

TARGETS = $(PATH)$(PROJ).inf $(PATH)$(PROJ2).inf
