#
# A Makefile for SUBST
# (c) osFree project,
# author, date
#

PROJ = subst
DESC = Substitute path to drive letter
#defines object file names in format objname.$(O)
srcfiles = $(p)subst$(e)
# defines additional options for C compiler
ADD_COPT=-i=..$(SEP)..$(SEP)include
ADD_LINKOPT = lib dos_shared.lib

!include $(%ROOT)/mk/dosapp.mk
