#
# A main Makefile for osFree OS/2 Personality Control Programming Interface
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = shared ansicall msg nls sesmgr kbdcalls moucalls quecalls viocalls &
       kal doscalls nampipes startlw bkscalls bmscalls bvscalls os2char

!include $(%ROOT)/mk/all.mk

TARGETS = subdirs
TARGET = all
