#####################################################################
#
#  @(#)makefile	1.1 	3/22/95 10:49:02
#
#  Copyright (c) 1995, Willows Software Inc.  All rights reserved.
#
#####################################################################

include $(TWINDIR)/Makefile.config

project		= windry
components	= windry.o windry.res.o
resource	= windry

include $(TWINDIR)/makeinclude/makefile$(TWIN_APISIZE).inc

clean-libs:

