# $Id: makefile,v 1.3 2004/08/16 04:51:12 prokushev Exp $
#

ROOT=..\..\..\..
ADD_COPT = -i=..\include
!include $(ROOT)\makefile.inc

all: istring.obj

# Clean all

clean: .symbolic
 -@del /q *.obj $(LOG)
 -@del /q *.err $(LOG)

