# Copyright 2002 Patrick TJ McPhee
# Distributed under the terms of the Mozilla Public Licence
# You can obtain a copy of the licence at http://www.mozilla.org/MPL
# The Original Code is regutil
# The Initial Developer is Patrick TJ McPhee
# $Header: /netlabs.cvs/osfree/src/REXX/libs/rexxutil/Makefile.doc,v 1.2 2004/08/21 14:48:37 prokushev Exp $

# this makefile produces the .pdf documentation. It requires pdflatex
# (v.14g or later). On win32 systems, you'll need rm to run the clean
# target 

PROJECT=regutil

doc : $(PROJECT).pdf


# need to do this three times to get congruence
$(PROJECT).pdf : $(PROJECT).tex
	-makeindex $(PROJECT)
	pdflatex $(PROJECT)
	makeindex $(PROJECT)
	pdflatex $(PROJECT)
	makeindex $(PROJECT)
	pdflatex $(PROJECT)

clean :
	-rm $(PROJECT).pdf $(PROJECT).log $(PROJECT).aux $(PROJECT).idx $(PROJECT).ilg $(PROJECT).ind $(PROJECT).toc $(PROJECT).out
