# Win32 Makefile for regutil
# this makefile works with the microsoft visual c compiler
# you are meant to copy Makefile.nt to the name Makefile, and
# then type `make dist' to get an optimised version of the library

#  The contents of this file are subject to the Mozilla Public License
#  Version 1.0 (the "License"); you may not use this file except in
#  compliance with the License. You may obtain a copy of the License at
#  http://www.mozilla.org/MPL/

#  Software distributed under the License is distributed on an "AS IS"
#  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
#  License for the specific language governing rights and limitations
#  under the License.

#  The Original Code is regutil.

#  The Initial Developer of the Original Code is Patrick TJ McPhee.
#  Portions created by Patrick McPhee are Copyright © 1998, 2001
#  Patrick TJ McPhee. All Rights Reserved.

#  Contributors:

# $Header: /netlabs.cvs/osfree/src/REXX/libs/rexxutil/Makefile.nt,v 1.3 2004/08/21 14:48:38 prokushev Exp $

DEBUG=-Zi
DOPT=-Ox -G5
INCDIR=../regina
LIBDIR=..\regina
CDEFS=-DNOT_LIKE_IBM -DMAPVIEWOFFILE
CFLAGS=$(OPT) $(DEBUG) $(CDEFS) -nologo -GF -I$(INCDIR) -MD
LDFLAGS=-LD $(OPT) $(DEBUG) -MD
CC=cl

OBJS=regfilesys.obj regini.obj regmacrospace.obj regscreen.obj\
 regsem.obj regutil.obj rxsupport.obj random.obj regstem.obj regwin.obj\
 regunicode.obj regcrypt.obj


rexxutil.dll : $(OBJS) regutil.def
	$(CC) $(CFLAGS) $(LDFLAGS) -Ferexxutil.dll $(OBJS) -link /def:regutil.def kernel32.lib advapi32.lib $(LIBDIR)\regina.lib ole32.lib oleaut32.lib uuid.lib user32.lib

regfilesys.obj : regfilesys.c regutil.h rxproto.h
regini.obj : regini.c regutil.h rxproto.h
regmacrospace.obj : regmacrospace.c regutil.h rxproto.h
regscreen.obj : regscreen.c regutil.h rxproto.h
regsem.obj : regsem.c regutil.h rxproto.h
regsysparm.obj : regsysparm.c regutil.h rxproto.h
regutil.obj : regutil.c regutil.h rxproto.h
rxsupport.obj : rxsupport.c rxproto.h

dist:
	$(MAKE) $(MAKEFLAGS) OPT="$(DOPT)" DEBUG=""


clean:
	del /f *.obj *.pdb *.lib *.dll *.exp *.ilk
