PKGDIR?= ../../..
L4DIR ?= $(PKGDIR)/../..

# the name of your library
TARGET	= libos2common.a

# list your .c files here
SRC_C	= globals.c io.c mountreg.c token.c utility.c string.c

include $(L4DIR)/mk/lib.mk
