#
# A Makefile for ANSI
# (c) osFree project,
# author, date
#

PROJ = ver
DESC = Displays System Version Number
#defines object file names in format objname.$(O)
srcfiles = $(p)ver$(e)
# defines additional options for C compiler
ADD_COPT = -i=$(MYDIR)..$(SEP)include
STUB=$(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)os2stub.exe

!include $(%ROOT)/mk/appsos2.mk
