#
# A Makefile for BIND
# (c) osFree project,
# author, date
#

PROJ = bind
TRGT = $(PROJ).exe
DESC = Binder
#defines object file names in format $(p)objname$(e)
srcfiles = $(p)loader$(e)
# defines additional options for C compiler

!include $(%ROOT)tools/mk/appsdos.mk
