/* This file is part of osFree project */

import <os2def.h>
import <l4/dm_generic/dm_generic.h>
import <l4/sys/types.h>

interface os2app
{
    /* Notify os2app about asynchronous event */
    [oneway]
    void app_notify(void);

    /* Add memory area to the memory map */
    //long app_AddArea([in] l4_addr_t addr,
    //                 [in] l4_size_t size,
    //                 [in] l4_uint32_t flags);

    /* get dataspace and region */
    //long app_AttachDataspace([in] l4_addr_t addr,
    //                         [in] l4dm_dataspace_t *ds,
    //                         [in] l4_uint32_t rights);

    //long app_ReleaseDataspace([in] l4dm_dataspace_t *ds);
};
