PKGDIR?= ../..
L4DIR ?= $(PKGDIR)/../..

# the name of your library
TARGET	= kal.s.so

# list your .c files here
SRC_C	= init.c

MODE=l4env_base
# if your library implements the client side of an idl defined in an
# idl-file of your package, list the idl file name(s) here (no path needed)

include $(L4DIR)/mk/lib.mk
