/* This file is part of osFree project */

import <l4/os3/gcc_os2def.h>
import <l4/dm_generic/dm_generic.h>
import <l4/sys/types.h>

interface os2app
{
    /* Get LoadError */
    void app_GetLoadError([in, out,
                          ref,
                          prealloc_client,
                          prealloc_server,
                          size_is(cbLoadError)] char **uchLoadError,
                          [in, out] ULONG *cbLoadError,
                          [out] ULONG *retCode);

    /* Terminate itself */
    void app_Terminate(void);

    /* Add memory area to the memory map */
    long app_AddArea([in] l4_addr_t addr,
                     [in] l4_size_t size,
                     [in] l4_uint32_t flags);

    /* get dataspace and region */
    long app_AttachDataspace([in] l4_addr_t addr,
                             [in] l4dm_dataspace_t *ds,
                             [in] l4_uint32_t rights);

    long app_ReleaseDataspace([in] l4dm_dataspace_t *ds);
};
