#
# A Makefile for COMP
# (c) osFree project,
# author, date
#

PROJ = comp
DESC = Compare tool
#defines object file names in format objname.$(O)
srcfiles = $(p)cmp$(e)
# defines additional options for C compiler
ADD_COPT = -i=..$(SEP)include
STUB=$(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)os2stub.exe

!include $(%ROOT)/mk/appsos2.mk
