#ifndef scentry_idl
#define scentry_idl

#include <somobj.idl>
#include "sctypes.h"

interface SOMTEntryC : SOMObject
{
  attribute string somtEntryName;
  attribute SOMTTypes somtElementType;
  readonly attribute string somtElementTypeName;
  readonly attribute string somtEntryComment;
  readonly attribute unsigned long somtSourceLineNumber;
  readonly attribute TypeCode somtTypeCode;
  readonly attribute boolean somtIsReference;
  readonly attribute string somtIDLScopedName;
  readonly attribute string somtCScopedName;
  string somtGetModifierValue(in string modifierName);
  boolean somtGetFirstModifier(inout string modifierName,
                         inout string modifierValue);
  boolean somtGetNextModifier(inout string modifierName,
                        inout string modifierValue);
  long somtFormatModifier(in string buffer,
                       in string name,
                       in string value);
  long somtGetModifierList(in string buffer);
  long somtSetSymbolsOnEntry(in SOMTEmitC emitter,
                          in string prefix);
  void somtSetEntryStruct(inout Entry es);

#ifdef __SOMIDL__
  implementation {

    releaseorder: _get_somtEntryName, _set_somtEntryName,
                  _get_somtElementType, _set_somtElementType,
                  _get_somtEntryComment, _get_somtSourceLineNumber,
                  _get_somtTypeCode, _get_somtIsReference,
                  somtGetModifierValue, somtGetFirstModifier,
                  somtGetNextModifier, somtFormatModifier,
                  somtGetModifierList, somtSetSymbolsOnEntry,
                  somtSetEntryStruct, _get_somtEntryStruct,
                  somtShowAssocEntry, _get_somtCScopedName,
                  _get_somtIDLScopedName, _get_somtElementTypeName;

    majorversion = 2;
    minorversion = 1;
    filestem = scentry;
    callstyle = oidl;

    passthru C_h_after =        "#include <sctypes.h>"
  "#include <scemit.h>"
  "#include <sctmplt.h>";
    passthru C_xh_after =        "#include <sctypes.h>"
  "#include <sctmplt.xh>";

    somInit: override;
    somUninit: override;
    somPrintSelf: override;
    somDumpSelfInt: override;
    somDumpSelf: override;

    somtEntryComment: nodata;
    somtCScopedName: nodata;
    somtIDLScopedName: nodata;
    somtSourceLineNumber: nodata;
    somtTypeCode: nodata;
    somtIsReference: nodata;
    somtEntryStruct: nodata;
    somtElementTypeName: nodata;
    somtEntryName: noget;

  };
#endif
};


#endif
