DESCRIPTION = LINK386 linker
SOURCES = deff386 link386 mesg386 xlate386 demangle dlltool fuzzy hash parse cmdline cmdscan context error file memory pathconv orlentry orlhash orlflhnd elfentr elfflhn elfload elflwlv coffimpl cofflwlv coffflhn coffload coffentr omfentr omfdrctv omfmunge omfload omfflhn

#linkstub

!include $(%ROOT)tools/mk/build.mk

