#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

#srcfiles = $(p)input$(e)
ADD_COPT = -i=$(MYDIR)..$(SEP)include

!include $(%ROOT)tools/mk/appsos2_fpm.mk

#DEST = none
TARGETS = $(OBJS)
TARGET = all
