#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

srcfiles = $(p)input$(e)
ADD_COPT = -i=$(MYDIR)..$(SEP)include
DEST = none

!include $(%ROOT)/mk/appsos2_fpm.mk

TARGETS = $(OBJS)
