/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef biter_idl
#define biter_idl
#include <naming.idl>
module Biter
{
	interface BINDITER_TWO;
	interface BINDITER_ONE;
	interface BINDITER_TWO :
		CosNaming::BindingIterator
	{
		void BI_Init2(
			inout somToken ctrl,
			in CosNaming::BindingList bl);
		void add_bindings(
			in CosNaming::BindingList bl);
#ifdef __SOMIDL__
		implementation
		{
#ifdef __PRIVATE__
			CosNaming::BindingList bindings;
			unsigned long pos;
			functionprefix = biter_BIT_;
			next_one : override;
			next_n : override;
			destroy : override;
#endif
			releaseorder : BI_Init2,add_bindings;
			dllname = "somnmf.dll";
			majorversion = 3;
			minorversion = 0;
		};
#endif /* __SOMIDL__ */
	};
	interface BINDITER_ONE :
		CosNaming::BindingIterator
	{
		typedef sequence<string> stringSeq;
		void BI_Init1(
			inout somToken ctrl,
			in stringSeq key,
			in string databaseFile);
#ifdef __SOMIDL__
		implementation
		{
#ifdef __PRIVATE__
			sequence<string> cursor;
			string databaseFile;
			CosNaming::BindingList bindings;
			functionprefix = biter_BIO_;
			next_one : override;
			next_n : override;
			destroy : override;
#endif
			dllname = "somnmf.dll";
			releaseorder : BI_Init1;
		};
#endif /* __SOMIDL__ */
	};
};
#endif /* biter_idl */
