/*  IDL interface for the
 *  filesystem server
 */

import <l4/os3/gcc_os2def.h>
import <l4/generic_fprov/generic_fprov.idl>
 
interface os2fs : l4fprov::file // inherits file provider interface
{
    /* misc functions */
    int  get_drivemap([out] ULONG *map);    
    
    /* file CPAPI */
    [allow_reply_only]
    APIRET dos_Read([in] HFILE hFile,
                    [out, size_is(count), ref, prealloc_client,
                    prealloc_server] char **buf,
                    [in, out] ULONG *count);

    [allow_reply_only]
    APIRET dos_Write([in] HFILE handle,
                     [in, prealloc_server, 
		     ref, size_is(count)] char *buf,
                     [in, out] ULONG *count);

    APIRET dos_ResetBuffer([in] HFILE handle);
    
    APIRET dos_SetFilePtrL([in]  HFILE handle,
                           [in]  long long ib,
			   [in]  ULONG method,
			   [out] long long *ibActual);

    APIRET dos_Close([in] HFILE handle);
    
    APIRET dos_QueryHType([in] HFILE handle,
                          [out] ULONG *pType,
			  [out] ULONG *pAttr);

    APIRET dos_OpenL([in, string] char *pszFileName,
                     [out] HFILE *phFile,
		     [out] ULONG *pulAction,
		     [in] long long cbFile,
		     [in] ULONG ulAttribute,
		     [in] ULONG fsOpenFlags,
		     [in] ULONG fsOpenMode,
		     [in, out] EAOP2 *peaop2);

    APIRET dos_DupHandle([in] HFILE hFile,
                         [in, out] HFILE *phFile2);

    APIRET dos_Delete([in, string] char *pszFileName);

    APIRET dos_ForceDelete([in, string] char *pszFileName);

    APIRET dos_DeleteDir([in, string] char *pszDirName);

    APIRET dos_CreateDir([in, string] char *pszDirName,
                         [in] EAOP2 *peaop2);
};
