#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ = diskcomp
TRGT = $(PROJ).exe
DESC = Compare disks
#defines object file names in format objname.$(O)
srcfiles = $(p)diskcomp$(e) $(p)drive$(e) $(p)md5$(e) $(p)misc$(e) $(p)tcc2wat$(e)
# defines additional options for C compiler

!include $(%ROOT)/mk/appsdos.mk
