#
# A Makefile for ANSI
# (c) osFree project,
# author, date
#

PROJ = rexxc
DESC = rexxc
srcfiles = $(p)rexxc$(e)
# defines additional options for C compiler
ADD_COPT    = -i=$(MYDIR)..$(SEP)..$(SEP)interp
#NODEFAULTLIBS = 1
#ADD_LINKOPT = lib $(BLD)$(SEP)lib$(SEP)os2386.lib, clib3r.lib
STUB=$(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)os2stub.exe

!include $(%ROOT)/mk/appsos2.mk
