#
# A Makefile for OS/3 boot sequence project
# micro IIF drivers
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = pdl sc somipc somkpub somref somcorba somir somd somnmf somcdr som somany somu somestrm somirfmt Frameworks

!include $(%ROOT)/mk/all.mk

