#
# A Makefile for somFree project
#

DIRS = makeall

pdl somipc sc somtk

#somkpub somref somcorba somir somd somnmf somcdr som somany somu somestrm somirfmt Frameworks

!include $(%ROOT)/mk/all.mk

