#
# A Makefile for OS/3 boot sequence project
# micro IIF drivers
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = pdl sc somipc som somcdr somcorba somany somkpub somref somir somu somestrm somnmf somd somirfmt Frameworks

!include $(%ROOT)/mk/all.mk

