#
# A Makefile for DOSX
# (c) osFree project,
# author, date
#

PROJ       = dosx
TRGT       = $(PROJ).exe
DESC       = 286 MS-DOS Extender
srcfiles   = $(p)dosx$(e)
JWASM      = 1
DEST       = os2$(SEP)mdos$(SEP)winos2

DIRS = hdpmi

!include $(%ROOT)/mk/appsdos.mk
