#
# A Makefile for DOSX
# (c) osFree project,
# author, date
#

PROJ       = dosx
TRGT       = $(PROJ).exe
DESC       = 286 MS-DOS Extender
srcfiles   = $(p)dosx$(e)
JWASM      = 1

!include $(%ROOT)/mk/appsdos.mk
