/*static char *SCCSID = "@(#)pmrxhlp.h  6.1 91/10/10";*/
/*static char *SCCSID = "@(#)pmrxhlp.h  12.2 89/08/26";                       */

#define  PMREXX_SUBTABLE      100
#define  FONT_DIALOG_SUBTABLE 200
#define  RH_EFH_SUBTABLE      300
#define  SAVEQUIT_SUBTABLE    700
#define  SEARCH_SUBTABLE      800
#define  IDH_RXHM_EXTHELP      01
#define  IDH_RXHM_FILE         02
#define  IDH_RXHA_SAVE         03
#define  IDH_RXHA_SAVEAS       04
#define  IDH_DID_FILETEXT      06
#define  IDH_OKBUTTON          07
#define  IDH_DID_PATHEDIT      08
#define  IDH_RXHA_EXIT         09
#define  IDH_RXHM_EDIT         10
#define  IDH_RXHA_COPY         11
#define  IDH_RXHA_PASTE        12
#define  IDH_RXHA_DELETE       13
#define  IDH_RXHA_ALL          14
#define  IDH_RXH_RERUNPROC     16
#define  IDH_RXHA_TRACE        17
#define  IDH_RXHA_FONTS        18
#define  IDH_FONT_NAMES        19
#define  IDH_FONT_SIZES        20
#define  IDH_FONT_STYLES       21
#define  IDH_SET_BUTTON        22
#define  IDH_USER_BUTTON       23
#define  IDH_RXHM_ACTIONS      24
#define  IDH_RXHA_HALT         25
#define  IDH_RXHA_TRCSTEP      26
#define  IDH_RXHA_TRCLAST      27
#define  IDH_RXHA_TRCOFF       28
#define  IDH_RXHM_HELPHELP     29
#define  IDH_RXHM_INDEXHELP    30
#define  IDH_RXHM_KEYSHELP     31
#define  IDH_RXHA_CUT          32
#define  IDH_RXHA_OPEN         33
#define  IDH_RXHA_DALL         34
#define  IDH_RXHA_PROPERTIES   35
#define  IDH_RXHA_RESULTS      36
#define  IDH_RXHA_SEARCH       37
#define  IDH_RXHA_ABOUT        42
#define  IDH_RXHM_HELP         45
#define  IDH_FONT_DIALOG      400
#define  IDH_FONT_CANCEL      401
#define  IDH_FONT_OK          402
#define  IDH_FONT_HELP        403
#define  IDH_FONT_NAME        404
#define  IDH_FONT_STYLE       405
#define  IDH_FONT_SIZE        406
#define  IDH_FONT_OUTLINE     407
#define  IDH_FONT_UNDERSCORE  408
#define  IDH_FONT_STRIKEOUT   409
#define  IDH_FONT_DISPLAY     410
#define  IDH_FONT_PRINT       411
#define  IDH_RH_EFH           500
#define  IDH_SAVEQUIT         600
#define  IDH_SEARCH           601
#define  IDH_SEARCH_FIELD     602
#define  IDH_SEARCH_CASE      603
#define  IDH_SEARCH_HELP      604
#define  IDH_SEARCH_OK        605
#define  IDH_SEARCH_CANCEL    606
#define  IDH_B_SAVE            52
#define  IDH_B_SAVEAS          53
#define  IDH_B_DISCARD         54
#define  IDH_PB_CANCEL         55
#define  IDH_PB_HELP           56
#define  IDH_PB_OK             57
#define  IDH_FILENAME          58
#define  IDH_DRIVE             59
#define  IDH_FILTER            60
#define  IDH_DIRECTORY         61
#define  IDH_FILES             62
