#
# A Makefile for krnl386
# (c) osFree project,
# author, date
#

PROJ       = startup
TRGT       = $(PROJ).exe
DESC       = Windows/286 startup
srcfiles   = $(p)main$(e)

!include $(%ROOT)/mk/appsdos.mk
