/* 
 $Id: FreePM_err.hpp,v 1.2 2003/06/18 22:51:49 evgen2 Exp $ 
*/
/* FreePM_err.hpp */

#ifndef FREEPM_ERR_H
#define FREEPM_ERR_H
#ifdef __cplusplus
      extern "C" {
#endif

/* made from PMERR.H + os2_ErrCodes.h + FreePM specific errors */

#define POKA_FREEPM_ERR 0
#define FREEPMERR_BASE  0x5000

/* This section lists PM errors returned by WinGetLastError
   in order of their error numbers. For explanations of these errors,
   see Error Name and Explanation.
*/
/*     Error Constant                          Error Number  */

      #define PMERR_OK                          0x0000
      #define PMERR_INVALID_HWND               0x1001

      #define PMERR_NO_MSG_QUEUE                0x1036
      #define PMERR_INVALID_HAB                 0x104A

      #define PMERR_MSG_QUEUE_ALREADY_EXISTS    0x1052

      #define PMERR_ALREADY_INITIALIZED         0x1403
/* FreePM errors */
      #define FPMERR_NULL_POINTER              (FREEPMERR_BASE + 0x0001)
      #define FPMERR_NULL_WINDPROC             (FREEPMERR_BASE + 0x0002)
      #define FPMERR_INITSERVER_CONNECTION      (FREEPMERR_BASE + 0x0101)

#if POKA_FREEPM_ERR
todo

Error Number Error Constant

0x0836   NERR_NetNotStarted
0x0845   NERR_RedirectedPath
0x084B   NERR_BufTooSmall
0x085E   NERR_InvalidAPI
0x0866   NERR_QNotFound
0x0867   NERR_JobNotFound
0x0868   NERR_DestNotFound
0x0869   NERR_DestExists
0x086A   NERR_QExists
0x086B   NERR_QNoRoom
0x086C   NERR_JobNoRoom
0x086D   NERR_DestNoRoom
0x086E   NERR_DestIdle
0x086F   NERR_DestInvalidOp
0x0871   NERR_SpoolerNotLoaded
0x0872   NERR_DestInvalidState
0x0874   NERR_JobInvalidState
0x0875   NERR_SpoolNoMemory
0x0876   NERR_DriverNotFound
0x0877   NERR_DataTypeInvalid
0x0878   NERR_ProcNotFound
0x0925   NERR_BadDev
0x0927   NERR_CommDevInUse
0x092F   NERR_InvalidComputer
0x0961   NERR_OpenFiles
0x0965   NERR_LocalDrive
0x1001   PMERR_INVALID_HWND
0x1001   HMERR_NO_FRAME_WND_IN_CHAIN
0x1002   PMERR_INVALID_HMQ
0x1002   HMERR_INVALID_ASSOC_APP_WND
0x1003   PMERR_PARAMETER_OUT_OF_RANGE
0x1003   HMERR_INVALID_ASSOC_HELP_INST
0x1004   PMERR_WINDOW_LOCK_UNDERFLOW
0x1004   HMERR_INVALID_DESTROY_HELP_INST
0x1005   PMERR_WINDOW_LOCK_OVERFLOW
0x1005   HMERR_NO_HELP_INST_IN_CHAIN
0x1006   PMERR_BAD_WINDOW_LOCK_COUNT
0x1006   HMERR_INVALID_HELP_INSTANCE_HDL
0x1007   PMERR_WINDOW_NOT_LOCKED
0x1007   HMERR_INVALID_QUERY_APP_WND
0x1008   PMERR_INVALID_SELECTOR
0x1008   HMERR_HELP_INST_CALLED_INVALID
0x1009   PMERR_CALL_FROM_WRONG_THREAD
0x1009   HMERR_HELPTABLE_UNDEFINE
0x100A   PMERR_RESOURCE_NOT_FOUND
0x100A   HMERR_HELP_INSTANCE_UNDEFINE
0x100B   PMERR_INVALID_STRING_PARM
0x100B   HMERR_HELPITEM_NOT_FOUND
0x100C   PMERR_INVALID_HHEAP
0x100C   HMERR_INVALID_HELPSUBITEM_SIZE
0x100D   PMERR_INVALID_HEAP_POINTER
0x100D   HMERR_HELPSUBITEM_NOT_FOUND
0x100E   PMERR_INVALID_HEAP_SIZE_PARM
0x100F   PMERR_INVALID_HEAP_SIZE
0x1010   PMERR_INVALID_HEAP_SIZE_WORD
0x1011   PMERR_HEAP_OUT_OF_MEMORY
0x1012   PMERR_HEAP_MAX_SIZE_REACHED
0x1013   PMERR_INVALID_HATOMTBL
0x1014   PMERR_INVALID_ATOM
0x1015   PMERR_INVALID_ATOM_NAME
0x1016   PMERR_INVALID_INTEGER_ATOM
0x1017   PMERR_ATOM_NAME_NOT_FOUND
0x1018   PMERR_QUEUE_TOO_LARGE
0x1019   PMERR_INVALID_FLAG
0x101A   PMERR_INVALID_HACCEL
0x101B   PMERR_INVALID_HPTR
0x101C   PMERR_INVALID_HENUM
0x101D   PMERR_INVALID_SRC_CODEPAGE
0x101E   PMERR_INVALID_DST_CODEPAGE
0x101F   PMERR_UNKNOWN_COMPONENT_ID
0x1020   PMERR_UNKNOWN_ERROR_CODE
0x1021   PMERR_SEVERITY_LEVELS
0x1034   PMERR_INVALID_RESOURCE_FORMAT
0x1035   WINDBG_WINDOW_UNLOCK_WAIT
0x1036   PMERR_NO_MSG_QUEUE
0x1037   PMERR_CANNOT_SET_FOCUS
0x1038   PMERR_QUEUE_FULL
0x1039   PMERR_LIBRARY_LOAD_FAILED
0x103A   PMERR_PROCEDURE_LOAD_FAILED
0x103B   PMERR_LIBRARY_DELETE_FAILED
0x103C   PMERR_PROCEDURE_DELETE_FAILED
0x103D   PMERR_ARRAY_TOO_LARGE
0x103E   PMERR_ARRAY_TOO_SMALL
0x103F   PMERR_DATATYPE_ENTRY_BAD_INDEX
0x1040   PMERR_DATATYPE_ENTRY_CTL_BAD
0x1041   PMERR_DATATYPE_ENTRY_CTL_MISS
0x1042   PMERR_DATATYPE_ENTRY_INVALID
0x1043   PMERR_DATATYPE_ENTRY_NOT_NUM
0x1044   PMERR_DATATYPE_ENTRY_NOT_OFF
0x1045   PMERR_DATATYPE_INVALID
0x1046   PMERR_DATATYPE_NOT_UNIQUE
0x1047   PMERR_DATATYPE_TOO_LONG
0x1048   PMERR_DATATYPE_TOO_SMALL
0x1049   PMERR_DIRECTION_INVALID
0x104A   PMERR_INVALID_HAB
0x104D   PMERR_INVALID_HSTRUCT
0x104E   PMERR_LENGTH_TOO_SMALL
0x104F   PMERR_MSGID_TOO_SMALL
0x1050   PMERR_NO_HANDLE_ALLOC
0x1051   PMERR_NOT_IN_A_PM_SESSION
0x1055   PMERR_OLD_RESOURCE
0x1056   PMERR_WPDSERVER_IS_ACTIVE
0x1057   PMERR_WPDSERVER_NOT_STARTED
0x1058   PMERR_SOMDD_IS_ACTIVE
0x1059   PMERR_SOMDD_NOT_STARTED
0x1101   PMERR_INVALID_PIB
0x1102   PMERR_INSUFF_SPACE_TO_ADD
0x1103   PMERR_INVALID_GROUP_HANDLE
0x1104   PMERR_DUPLICATE_TITLE
0x1105   PMERR_INVALID_TITLE
0x1106   PMERR_INVALID_TARGET_HANDLE
0x1107   PMERR_HANDLE_NOT_IN_GROUP
0x1108   PMERR_INVALID_PATH_STATEMENT
0x1109   PMERR_NO_PROGRAM_FOUND
0x110A   PMERR_INVALID_BUFFER_SIZE
0x110B   PMERR_BUFFER_TOO_SMALL
0x110C   PMERR_PL_INITIALISATION_FAIL
0x110D   PMERR_CANT_DESTROY_SYS_GROUP
0x110E   PMERR_INVALID_TYPE_CHANGE
0x110F   PMERR_INVALID_PROGRAM_HANDLE
0x1110   PMERR_NOT_CURRENT_PL_VERSION
0x1111   PMERR_INVALID_CIRCULAR_REF
0x1112   PMERR_MEMORY_ALLOCATION_ERR
0x1113   PMERR_MEMORY_DEALLOCATION_ERR
0x1114   PMERR_TASK_HEADER_TOO_BIG
0x1115   PMERR_INVALID_INI_FILE_HANDLE
0x1116   PMERR_MEMORY_SHARE
0x1117   PMERR_OPEN_QUEUE
0x1118   PMERR_CREATE_QUEUE
0x1119   PMERR_WRITE_QUEUE
0x111A   PMERR_READ_QUEUE
0x111B   PMERR_CALL_NOT_EXECUTED
0x111C   PMERR_UNKNOWN_APIPKT
0x111D   PMERR_INITHREAD_EXISTS
0x111E   PMERR_CREATE_THREAD
0x111F   PMERR_NO_HK_PROFILE_INSTALLED
0x1120   PMERR_INVALID_DIRECTORY
0x1121   PMERR_WILDCARD_IN_FILENAME
0x1122   PMERR_FILENAME_BUFFER_FULL
0x1123   PMERR_FILENAME_TOO_LONG
0x1124   PMERR_INI_FILE_IS_SYS_OR_USER
0x1125   PMERR_BROADCAST_PLMSG
0x1126   PMERR_190_INIT_DONE
0x1127   PMERR_HMOD_FOR_PMSHAPI
0x1128   PMERR_SET_HK_PROFILE
0x1129   PMERR_API_NOT_ALLOWED
0x112A   PMERR_INI_STILL_OPEN
0x112B   PMERR_PROGDETAILS_NOT_IN_INI
0x112C   PMERR_PIBSTRUCT_NOT_IN_INI
0x112D   PMERR_INVALID_DISKPROGDETAILS
0x112E   PMERR_PROGDETAILS_READ_FAILURE
0x112F   PMERR_PROGDETAILS_WRITE_FAILURE
0x1130   PMERR_PROGDETAILS_QSIZE_FAILURE
0x1131   PMERR_INVALID_PROGDETAILS
0x1132   PMERR_SHEPROFILEHOOK_NOT_FOUND
0x1133   PMERR_190PLCONVERTED
0x1134   PMERR_FAILED_TO_CONVERT_INI_PL
0x1135   PMERR_PMSHAPI_NOT_INITIALISED
0x1136   PMERR_INVALID_SHELL_API_HOOK_ID
0x1200   PMERR_DOS_ERROR
0x1201   PMERR_NO_SPACE
0x1202   PMERR_INVALID_SWITCH_HANDLE
0x1203   PMERR_NO_HANDLE
0x1204   PMERR_INVALID_PROCESS_ID
0x1205   PMERR_NOT_SHELL
0x1206   PMERR_INVALID_WINDOW
0x1207   PMERR_INVALID_POST_MSG
0x1208   PMERR_INVALID_PARAMETERS
0x1208   PMERR_INVALID_PARAMETERS
0x1209   PMERR_INVALID_PROGRAM_TYPE
0x120A   PMERR_NOT_EXTENDED_FOCUS
0x120B   PMERR_INVALID_SESSION_ID
0x120C   PMERR_SMG_INVALID_ICON_FILE
0x120D   PMERR_SMG_ICON_NOT_CREATED
0x120E   PMERR_SHL_DEBUG
0x1301   PMERR_OPENING_INI_FILE
0x1302   PMERR_INI_FILE_CORRUPT
0x1303   PMERR_INVALID_PARM
0x1304   PMERR_NOT_IN_IDX
0x1305   PMERR_NO_ENTRIES_IN_GROUP
0x1306   PMERR_INI_WRITE_FAIL
0x1307   PMERR_IDX_FULL
0x1308   PMERR_INI_PROTECTED
0x1309   PMERR_MEMORY_ALLOC
0x130A   PMERR_INI_INIT_ALREADY_DONE
0x130B   PMERR_INVALID_INTEGER
0x130C   PMERR_INVALID_ASCIIZ
0x130D   PMERR_CAN_NOT_CALL_SPOOLER
0x130D   PMERR_VALIDATION_REJECTED
0x1401   PMERR_WARNING_WINDOW_NOT_KILLED
0x1402   PMERR_ERROR_INVALID_WINDOW

0x1405   PMERR_MSG_PROG_NO_MOU
0x1406   PMERR_MSG_PROG_NON_RECOV
0x1407   PMERR_WINCONV_INVALID_PATH
0x1408   PMERR_PI_NOT_INITIALISED
0x1409   PMERR_PL_NOT_INITIALISED
0x140A   PMERR_NO_TASK_MANAGER
0x140B   PMERR_SAVE_NOT_IN_PROGRESS
0x140C   PMERR_NO_STACK_SPACE
0x140D   PMERR_INVALID_COLR_FIELD
0x140E   PMERR_INVALID_COLR_VALUE
0x140F   PMERR_COLR_WRITE
0x1501   PMERR_TARGET_FILE_EXISTS
0x1502   PMERR_SOURCE_SAME_AS_TARGET
0x1503   PMERR_SOURCE_FILE_NOT_FOUND
0x1504   PMERR_INVALID_NEW_PATH
0x1505   PMERR_TARGET_FILE_NOT_FOUND
0x1506   PMERR_INVALID_DRIVE_NUMBER
0x1507   PMERR_NAME_TOO_LONG
0x1508   PMERR_NOT_ENOUGH_ROOM_ON_DISK
0x1509   PMERR_NOT_ENOUGH_MEM
0x150B   PMERR_LOG_DRV_DOES_NOT_EXIST
0x150C   PMERR_INVALID_DRIVE
0x150D   PMERR_ACCESS_DENIED
0x150E   PMERR_NO_FIRST_SLASH
0x150F   PMERR_READ_ONLY_FILE
0x151F   PMERR_GROUP_PROTECTED
0x152F   PMERR_INVALID_PROGRAM_CATEGORY
0x1530   PMERR_INVALID_APPL
0x1531   PMERR_CANNOT_START
0x1532   PMERR_STARTED_IN_BACKGROUND
0x1533   PMERR_INVALID_HAPP
0x1534   PMERR_CANNOT_STOP
0x1601   PMERR_INTERNAL_ERROR_1
0x1602   PMERR_INTERNAL_ERROR_2
0x1603   PMERR_INTERNAL_ERROR_3
0x1604   PMERR_INTERNAL_ERROR_4
0x1605   PMERR_INTERNAL_ERROR_5
0x1606   PMERR_INTERNAL_ERROR_6
0x1607   PMERR_INTERNAL_ERROR_7
0x1608   PMERR_INTERNAL_ERROR_8
0x1609   PMERR_INTERNAL_ERROR_9
0x160A   PMERR_INTERNAL_ERROR_10
0x160B   PMERR_INTERNAL_ERROR_11
0x160C   PMERR_INTERNAL_ERROR_12
0x160D   PMERR_INTERNAL_ERROR_13
0x160E   PMERR_INTERNAL_ERROR_14
0x160F   PMERR_INTERNAL_ERROR_15
0x1610   PMERR_INTERNAL_ERROR_16
0x1611   PMERR_INTERNAL_ERROR_17
0x1612   PMERR_INTERNAL_ERROR_18
0x1613   PMERR_INTERNAL_ERROR_19
0x1614   PMERR_INTERNAL_ERROR_20
0x1615   PMERR_INTERNAL_ERROR_21
0x1616   PMERR_INTERNAL_ERROR_22
0x1617   PMERR_INTERNAL_ERROR_23
0x1618   PMERR_INTERNAL_ERROR_24
0x1619   PMERR_INTERNAL_ERROR_25
0x161A   PMERR_INTERNAL_ERROR_26
0x161B   PMERR_INTERNAL_ERROR_27
0x161C   PMERR_INTERNAL_ERROR_28
0x161D   PMERR_INTERNAL_ERROR_29
0x1630   PMERR_INVALID_FREE_MESSAGE_ID
0x1641   PMERR_FUNCTION_NOT_SUPPORTED
0x1642   PMERR_INVALID_ARRAY_COUNT
0x1643   PMERR_INVALID_LENGTH
0x1644   PMERR_INVALID_BUNDLE_TYPE
0x1645   PMERR_INVALID_PARAMETER
0x1646   PMERR_INVALID_NUMBER_OF_PARMS
0x1647   PMERR_GREATER_THAN_64K
0x1648   PMERR_INVALID_PARAMETER_TYPE
0x1649   PMERR_NEGATIVE_STRCOND_DIM
0x164A   PMERR_INVALID_NUMBER_OF_TYPES
0x164B   PMERR_INCORRECT_HSTRUCT
0x164C   PMERR_INVALID_ARRAY_SIZE
0x164D   PMERR_INVALID_CONTROL_DATATYPE
0x164E   PMERR_INCOMPLETE_CONTROL_SEQU
0x164F   PMERR_INVALID_DATATYPE
0x1650   PMERR_INCORRECT_DATATYPE
0x1651   PMERR_NOT_SELF_DESCRIBING_DTYP
0x1652   PMERR_INVALID_CTRL_SEQ_INDEX
0x1653   PMERR_INVALID_TYPE_FOR_LENGTH
0x1654   PMERR_INVALID_TYPE_FOR_OFFSET
0x1655   PMERR_INVALID_TYPE_FOR_MPARAM
0x1656   PMERR_INVALID_MESSAGE_ID
0x1657   PMERR_C_LENGTH_TOO_SMALL
0x1658   PMERR_APPL_STRUCTURE_TOO_SMALL
0x1659   PMERR_INVALID_ERRORINFO_HANDLE
0x165A   PMERR_INVALID_CHARACTER_INDEX
0x1700   WPERR_PROTECTED_CLASS
0x1701   WPERR_INVALID_CLASS
0x1702   WPERR_INVALID_SUPERCLASS
0x1703   WPERR_NO_MEMORY
0x1704   WPERR_SEMAPHORE_ERROR
0x1705   WPERR_BUFFER_TOO_SMALL
0x1706   WPERR_CLSLOADMOD_FAILED
0x1707   WPERR_CLSPROCADDR_FAILED
0x1708   WPERR_OBJWORD_LOCATION
0x1709   WPERR_INVALID_OBJECT
0x170A   WPERR_MEMORY_CLEANUP
0x170B   WPERR_INVALID_MODULE
0x170C   WPERR_INVALID_OLDCLASS
0x170D   WPERR_INVALID_NEWCLASS
0x170E   WPERR_NOT_IMMEDIATE_CHILD
0x170F   WPERR_NOT_WORKPLACE_CLASS
0x1710   WPERR_CANT_REPLACE_METACLS
0x1711   WPERR_INI_FILE_WRITE
0x1712   WPERR_INVALID_FOLDER
0x1713   WPERR_BUFFER_OVERFLOW
0x1714   WPERR_OBJECT_NOT_FOUND
0x1715   WPERR_INVALID_HFIND
0x1716   WPERR_INVALID_COUNT
0x1717   WPERR_INVALID_BUFFER
0x1718   WPERR_ALREADY_EXISTS
0x1719   WPERR_INVALID_FLAGS
0x1720   WPERR_INVALID_OBJECTID
0x1721   WPERR_INVALID_TARGET_OBJECT
0x1F00   PMERR_NOT_DRAGGING
0x2001   PMERR_ALREADY_IN_AREA
0x2001   HMERR_INDEX_NOT_FOUND
0x2002   PMERR_ALREADY_IN_ELEMENT
0x2002   HMERR_CONTENT_NOT_FOUND
0x2003   PMERR_ALREADY_IN_PATH
0x2003   HMERR_OPEN_LIB_FILE
0x2004   PMERR_ALREADY_IN_SEG
0x2004   HMERR_READ_LIB_FILE
0x2005   PMERR_AREA_INCOMPLETE
0x2005   HMERR_CLOSE_LIB_FILE
0x2006   PMERR_BASE_ERROR
0x2006   HMERR_INVALID_LIB_FILE
0x2007   PMERR_BITBLT_LENGTH_EXCEEDED
0x2007   HMERR_NO_MEMORY
0x2008   PMERR_BITMAP_IN_USE
0x2008   HMERR_ALLOCATE_SEGMENT
0x2009   PMERR_BITMAP_IS_SELECTED
0x2009   HMERR_FREE_MEMORY
0x200A   PMERR_BITMAP_NOT_FOUND
0x200B   PMERR_BITMAP_NOT_SELECTED
0x200C   PMERR_BOUNDS_OVERFLOW
0x200D   PMERR_CALLED_SEG_IS_CHAINED
0x200E   PMERR_CALLED_SEG_IS_CURRENT
0x200F   PMERR_CALLED_SEG_NOT_FOUND
0x2010   PMERR_CANNOT_DELETE_ALL_DATA
0x2010   HMERR_PANEL_NOT_FOUND
0x2011   PMERR_CANNOT_REPLACE_ELEMENT_0
0x2011   HMERR_DATABASE_NOT_OPEN
0x2012   PMERR_COL_TABLE_NOT_REALIZABLE
0x2013   PMERR_COL_TABLE_NOT_REALIZED
0x2013   HMERR_LOAD_DLL
0x2014   PMERR_COORDINATE_OVERFLOW
0x2015   PMERR_CORR_FORMAT_MISMATCH
0x2016   PMERR_DATA_TOO_LONG
0x2017   PMERR_DC_IS_ASSOCIATED
0x2018   PMERR_DESC_STRING_TRUNCATED
0x2019   PMERR_DEVICE_DRIVER_ERROR_1
0x201A   PMERR_DEVICE_DRIVER_ERROR_2
0x201B   PMERR_DEVICE_DRIVER_ERROR_3
0x201C   PMERR_DEVICE_DRIVER_ERROR_4
0x201D   PMERR_DEVICE_DRIVER_ERROR_5
0x201E   PMERR_DEVICE_DRIVER_ERROR_6
0x201F   PMERR_DEVICE_DRIVER_ERROR_7
0x2020   PMERR_DEVICE_DRIVER_ERROR_8
0x2021   PMERR_DEVICE_DRIVER_ERROR_9
0x2022   PMERR_DEVICE_DRIVER_ERROR_10
0x2023   PMERR_DEV_FUNC_NOT_INSTALLED
0x2024   PMERR_DOSOPEN_FAILURE
0x2025   PMERR_DOSREAD_FAILURE
0x2026   PMERR_DRIVER_NOT_FOUND
0x2027   PMERR_DUP_SEG
0x2028   PMERR_DYNAMIC_SEG_SEQ_ERROR
0x2029   PMERR_DYNAMIC_SEG_ZERO_INV
0x202A   PMERR_ELEMENT_INCOMPLETE
0x202B   PMERR_ESC_CODE_NOT_SUPPORTED
0x202C   PMERR_EXCEEDS_MAX_SEG_LENGTH
0x202D   PMERR_FONT_AND_MODE_MISMATCH
0x202E   PMERR_FONT_FILE_NOT_LOADED
0x202F   PMERR_FONT_NOT_LOADED
0x2030   PMERR_FONT_TOO_BIG
0x2031   PMERR_HARDWARE_INIT_FAILURE
0x2032   PMERR_HBITMAP_BUSY
0x2033   PMERR_HDC_BUSY
0x2034   PMERR_HRGN_BUSY
0x2035   PMERR_HUGE_FONTS_NOT_SUPPORTED
0x2036   PMERR_ID_HAS_NO_BITMAP
0x2037   PMERR_IMAGE_INCOMPLETE
0x2038   PMERR_INCOMPAT_COLOR_FORMAT
0x2039   PMERR_INCOMPAT_COLOR_OPTIONS
0x203A   PMERR_INCOMPATIBLE_BITMAP
0x203B   PMERR_INCOMPATIBLE_METAFILE
0x203C   PMERR_INCORRECT_DC_TYPE
0x203D   PMERR_INSUFFICIENT_DISK_SPACE
0x203E   PMERR_INSUFFICIENT_MEMORY
0x203F   PMERR_INV_ANGLE_PARM
0x2040   PMERR_INV_ARC_CONTROL
0x2041   PMERR_INV_AREA_CONTROL
0x2042   PMERR_INV_ARC_POINTS
0x2043   PMERR_INV_ATTR_MODE
0x2044   PMERR_INV_BACKGROUND_COL_ATTR
0x2045   PMERR_INV_BACKGROUND_MIX_ATTR
0x2046   PMERR_INV_BITBLT_MIX
0x2047   PMERR_INV_BITBLT_STYLE
0x2048   PMERR_INV_BITMAP_DIMENSION
0x2049   PMERR_INV_BOX_CONTROL
0x204A   PMERR_INV_BOX_ROUNDING_PARM
0x204B   PMERR_INV_CHAR_ANGLE_ATTR
0x204C   PMERR_INV_CHAR_DIRECTION_ATTR
0x204D   PMERR_INV_CHAR_MODE_ATTR
0x204E   PMERR_INV_CHAR_POS_OPTIONS
0x204F   PMERR_INV_CHAR_SET_ATTR
0x2050   PMERR_INV_CHAR_SHEAR_ATTR
0x2051   PMERR_INV_CLIP_PATH_OPTIONS
0x2052   PMERR_INV_CODEPAGE
0x2053   PMERR_INV_COLOR_ATTR
0x2054   PMERR_INV_COLOR_DATA
0x2055   PMERR_INV_COLOR_FORMAT
0x2056   PMERR_INV_COLOR_INDEX
0x2057   PMERR_INV_COLOR_OPTIONS
0x2058   PMERR_INV_COLOR_START_INDEX
0x2059   PMERR_INV_COORD_OFFSET
0x205A   PMERR_INV_COORD_SPACE
0x205B   PMERR_INV_COORDINATE
0x205C   PMERR_INV_CORRELATE_DEPTH
0x205D   PMERR_INV_CORRELATE_TYPE
0x205E   PMERR_INV_CURSOR_BITMAP
0x205F   PMERR_INV_DC_DATA
0x2060   PMERR_INV_DC_TYPE
0x2061   PMERR_INV_DEVICE_NAME
0x2062   PMERR_INV_DEV_MODES_OPTIONS
0x2063   PMERR_INV_DRAW_CONTROL
0x2064   PMERR_INV_DRAW_VALUE
0x2065   PMERR_INV_DRAWING_MODE
0x2066   PMERR_INV_DRIVER_DATA
0x2067   PMERR_INV_DRIVER_NAME
0x2068   PMERR_INV_DRAW_BORDER_OPTION
0x2069   PMERR_INV_EDIT_MODE
0x206A   PMERR_INV_ELEMENT_OFFSET
0x206B   PMERR_INV_ELEMENT_POINTER
0x206C   PMERR_INV_END_PATH_OPTIONS
0x206D   PMERR_INV_ESC_CODE
0x206E   PMERR_INV_ESCAPE_DATA
0x206F   PMERR_INV_EXTENDED_LCID
0x2070   PMERR_INV_FILL_PATH_OPTIONS
0x2071   PMERR_INV_FIRST_CHAR
0x2072   PMERR_INV_FONT_ATTRS
0x2073   PMERR_INV_FONT_FILE_DATA
0x2074   PMERR_INV_FOR_THIS_DC_TYPE
0x2075   PMERR_INV_FORMAT_CONTROL
0x2076   PMERR_INV_FORMS_CODE
0x2077   PMERR_INV_FONTDEF
0x2078   PMERR_INV_GEOM_LINE_WIDTH_ATTR
0x2079   PMERR_INV_GETDATA_CONTROL
0x207A   PMERR_INV_GRAPHICS_FIELD
0x207B   PMERR_INV_HBITMAP
0x207C   PMERR_INV_HDC
0x207D   PMERR_INV_HJOURNAL
0x207E   PMERR_INV_HMF
0x207F   PMERR_INV_HPS
0x2080   PMERR_INV_HRGN
0x2081   PMERR_INV_ID
0x2082   PMERR_INV_IMAGE_DATA_LENGTH
0x2083   PMERR_INV_IMAGE_DIMENSION
0x2084   PMERR_INV_IMAGE_FORMAT
0x2085   PMERR_INV_IN_AREA
0x2086   PMERR_INV_IN_CALLED_SEG
0x2087   PMERR_INV_IN_CURRENT_EDIT_MODE
0x2088   PMERR_INV_IN_DRAW_MODE
0x2089   PMERR_INV_IN_ELEMENT
0x208A   PMERR_INV_IN_IMAGE
0x208B   PMERR_INV_IN_PATH
0x208C   PMERR_INV_IN_RETAIN_MODE
0x208D   PMERR_INV_IN_SEG
0x208E   PMERR_INV_IN_VECTOR_SYMBOL
0x208F   PMERR_INV_INFO_TABLE
0x2090   PMERR_INV_JOURNAL_OPTION
0x2091   PMERR_INV_KERNING_FLAGS
0x2092   PMERR_INV_LENGTH_OR_COUNT
0x2093   PMERR_INV_LINE_END_ATTR
0x2094   PMERR_INV_LINE_JOIN_ATTR
0x2095   PMERR_INV_LINE_TYPE_ATTR
0x2096   PMERR_INV_LINE_WIDTH_ATTR
0x2097   PMERR_INV_LOGICAL_ADDRESS
0x2098   PMERR_INV_MARKER_BOX_ATTR
0x2099   PMERR_INV_MARKER_SET_ATTR
0x209A   PMERR_INV_MARKER_SYMBOL_ATTR
0x209B   PMERR_INV_MATRIX_ELEMENT
0x209C   PMERR_INV_MAX_HITS
0x209D   PMERR_INV_METAFILE
0x209E   PMERR_INV_METAFILE_LENGTH
0x209F   PMERR_INV_METAFILE_OFFSET
0x20A0   PMERR_INV_MICROPS_DRAW_CONTROL
0x20A1   PMERR_INV_MICROPS_FUNCTION
0x20A2   PMERR_INV_MICROPS_ORDER
0x20A3   PMERR_INV_MIX_ATTR
0x20A4   PMERR_INV_MODE_FOR_OPEN_DYN
0x20A5   PMERR_INV_MODE_FOR_REOPEN_SEG
0x20A6   PMERR_INV_MODIFY_PATH_MODE
0x20A7   PMERR_INV_MULTIPLIER
0x20A8   PMERR_INV_NESTED_FIGURES
0x20A9   PMERR_INV_OR_INCOMPAT_OPTIONS
0x20AA   PMERR_INV_ORDER_LENGTH
0x20AB   PMERR_INV_ORDERING_PARM
0x20AC   PMERR_INV_OUTSIDE_DRAW_MODE
0x20AD   PMERR_INV_PAGE_VIEWPORT
0x20AE   PMERR_INV_PATH_ID
0x20AF   PMERR_INV_PATH_MODE
0x20B0   PMERR_INV_PATTERN_ATTR
0x20B1   PMERR_INV_PATTERN_REF_PT_ATTR
0x20B2   PMERR_INV_PATTERN_SET_ATTR
0x20B3   PMERR_INV_PATTERN_SET_FONT
0x20B4   PMERR_INV_PICK_APERTURE_OPTION
0x20B5   PMERR_INV_PICK_APERTURE_POSN
0x20B6   PMERR_INV_PICK_APERTURE_SIZE
0x20B7   PMERR_INV_PICK_NUMBER
0x20B8   PMERR_INV_PLAY_METAFILE_OPTION
0x20B9   PMERR_INV_PRIMITIVE_TYPE
0x20BA   PMERR_INV_PS_SIZE
0x20BB   PMERR_INV_PUTDATA_FORMAT
0x20BC   PMERR_INV_QUERY_ELEMENT_NO
0x20BD   PMERR_INV_RECT
0x20BE   PMERR_INV_REGION_CONTROL
0x20BF   PMERR_INV_REGION_MIX_MODE
0x20C0   PMERR_INV_REPLACE_MODE_FUNC
0x20C1   PMERR_INV_RESERVED_FIELD
0x20C2   PMERR_INV_RESET_OPTIONS
0x20C3   PMERR_INV_RGBCOLOR
0x20C4   PMERR_INV_SCAN_START
0x20C5   PMERR_INV_SEG_ATTR
0x20C6   PMERR_INV_SEG_ATTR_VALUE
0x20C7   PMERR_INV_SEG_CH_LENGTH
0x20C8   PMERR_INV_SEG_NAME
0x20C9   PMERR_INV_SEG_OFFSET
0x20CA   PMERR_INV_SETID
0x20CB   PMERR_INV_SETID_TYPE
0x20CC   PMERR_INV_SET_VIEWPORT_OPTION
0x20CD   PMERR_INV_SHARPNESS_PARM
0x20CE   PMERR_INV_SOURCE_OFFSET
0x20CF   PMERR_INV_STOP_DRAW_VALUE
0x20D0   PMERR_INV_TRANSFORM_TYPE
0x20D1   PMERR_INV_USAGE_PARM
0x20D2   PMERR_INV_VIEWING_LIMITS
0x20D3   PMERR_JFILE_BUSY
0x20D4   PMERR_JNL_FUNC_DATA_TOO_LONG
0x20D5   PMERR_KERNING_NOT_SUPPORTED
0x20D6   PMERR_LABEL_NOT_FOUND
0x20D7   PMERR_MATRIX_OVERFLOW
0x20D8   PMERR_METAFILE_INTERNAL_ERROR
0x20D9   PMERR_METAFILE_IN_USE
0x20DA   PMERR_METAFILE_LIMIT_EXCEEDED
0x20DB   PMERR_NAME_STACK_FULL
0x20DC   PMERR_NOT_CREATED_BY_DEVOPENDC
0x20DD   PMERR_NOT_IN_AREA
0x20DE   PMERR_NOT_IN_DRAW_MODE
0x20DF   PMERR_NOT_IN_ELEMENT
0x20E0   PMERR_NOT_IN_IMAGE
0x20E1   PMERR_NOT_IN_PATH
0x20E2   PMERR_NOT_IN_RETAIN_MODE
0x20E3   PMERR_NOT_IN_SEG
0x20E4   PMERR_NO_BITMAP_SELECTED
0x20E5   PMERR_NO_CURRENT_ELEMENT
0x20E6   PMERR_NO_CURRENT_SEG
0x20E7   PMERR_NO_METAFILE_RECORD_HANDLE
0x20E8   PMERR_ORDER_TOO_BIG
0x20E9   PMERR_OTHER_SET_ID_REFS
0x20EA   PMERR_OVERRAN_SEG
0x20EB   PMERR_OWN_SET_ID_REFS
0x20EC   PMERR_PATH_INCOMPLETE
0x20ED   PMERR_PATH_LIMIT_EXCEEDED
0x20EE   PMERR_PATH_UNKNOWN
0x20EF   PMERR_PEL_IS_CLIPPED
0x20F0   PMERR_PEL_NOT_AVAILABLE
0x20F1   PMERR_PRIMITIVE_STACK_EMPTY
0x20F2   PMERR_PROLOG_ERROR
0x20F3   PMERR_PROLOG_SEG_ATTR_NOT_SET
0x20F4   PMERR_PS_BUSY
0x20F5   PMERR_PS_IS_ASSOCIATED
0x20F6   PMERR_RAM_JNL_FILE_TOO_SMALL
0x20F7   PMERR_REALIZE_NOT_SUPPORTED
0x20F8   PMERR_REGION_IS_CLIP_REGION
0x20F9   PMERR_RESOURCE_DEPLETION
0x20FA   PMERR_SEG_AND_REFSEG_ARE_SAME
0x20FB   PMERR_SEG_CALL_RECURSIVE
0x20FC   PMERR_SEG_CALL_STACK_EMPTY
0x20FD   PMERR_SEG_CALL_STACK_FULL
0x20FE   PMERR_SEG_IS_CURRENT
0x20FF   PMERR_SEG_NOT_CHAINED
0x2100   PMERR_SEG_NOT_FOUND
0x2101   PMERR_SEG_STORE_LIMIT_EXCEEDED
0x2102   PMERR_SETID_IN_USE
0x2103   PMERR_SETID_NOT_FOUND
0x2104   PMERR_STARTDOC_NOT_ISSUED
0x2105   PMERR_STOP_DRAW_OCCURRED
0x2106   PMERR_TOO_MANY_METAFILES_IN_USE
0x2107   PMERR_TRUNCATED_ORDER
0x2108   PMERR_UNCHAINED_SEG_ZERO_INV
0x2109   PMERR_UNSUPPORTED_ATTR
0x210A   PMERR_UNSUPPORTED_ATTR_VALUE
0x210B   PMERR_ENDDOC_NOT_ISSUED
0x210C   PMERR_PS_NOT_ASSOCIATED
0x210D   PMERR_INV_FLOOD_FILL_OPTIONS
0x210E   PMERR_INV_FACENAME
0x210F   PMERR_PALETTE_SELECTED
0x2110   PMERR_NO_PALETTE_SELECTED
0x2111   PMERR_INV_HPAL
0x2112   PMERR_PALETTE_BUSY
0x2113   PMERR_START_POINT_CLIPPED
0x2114   PMERR_NO_FILL
0x2115   PMERR_INV_FACENAMEDESC
0x2116   PMERR_INV_BITMAP_DATA
0x2117   PMERR_INV_CHAR_ALIGN_ATTR
0x2118   PMERR_INV_HFONT
0x2119   PMERR_HFONT_IS_SELECTED
0x2120   PMERR_DRVR_NOT_SUPPORTED
0x2120   PMERR_RASTER_FONT
0x3001   HMERR_DDF_MEMORY
0x3002   HMERR_DDF_ALIGN_TYPE
0x3003   HMERR_DDF_BACKCOLOR
0x3004   HMERR_DDF_FORECOLOR
0x3005   HMERR_DDF_FONTSTYLE
0x3006   HMERR_DDF_REFTYPE
0x3007   HMERR_DDF_LIST_UNCLOSED
0x3008   HMERR_DDF_LIST_UNINITIALIZED
0x3009   HMERR_DDF_LIST_BREAKTYPE
0x300A   HMERR_DDF_LIST_SPACING
0x300B   HMERR_DDF_HINSTANCE
0x300C   HMERR_DDF_EXCEED_MAX_LENGTH
0x300D   HMERR_DDF_EXCEED_MAX_INC
0x300E   HMERR_DDF_INVALID_DDF
0x300F   HMERR_DDF_FORMAT_TYPE
0x3010   HMERR_DDF_INVALID_PARM
0x3011   HMERR_DDF_INVALID_FONT
0x3012   HMERR_DDF_SEVERE
0x4001   PMERR_SPL_DRIVER_ERROR
0x4001   MERR_SPL_DRIVER_ERROR
0x4002   PMERR_SPL_DEVICE_ERROR
0x4002   MERR_SPL_DEVICE_ERROR
0x4003   PMERR_SPL_DEVICE_NOT_INSTALLED
0x4003   MERR_SPL_DEVICE_NOT_INSTALLED
0x4004   PMERR_SPL_QUEUE_ERROR
0x4004   MERR_SPL_QUEUE_ERROR
0x4005   PMERR_SPL_INV_HSPL
0x4005   MERR_SPL_INV_HSPL
0x4006   PMERR_SPL_NO_DISK_SPACE
0x4006   MERR_SPL_NO_DISK_SPACE
0x4007   PMERR_SPL_NO_MEMORY
0x4007   MERR_SPL_NO_MEMORY
0x4008   PMERR_SPL_PRINT_ABORT
0x4008   MERR_SPL_PRINT_ABORT
0x4009   PMERR_SPL_SPOOLER_NOT_INSTALLED
0x4009   MERR_SPL_SPOOLER_NOT_INSTALLED
0x400A   PMERR_SPL_INV_FORMS_CODE
0x400A   MERR_SPL_INV_FORMS_CODE
0x400B   PMERR_SPL_INV_PRIORITY
0x400B   MERR_SPL_INV_PRIORITY
0x400C   PMERR_SPL_NO_FREE_JOB_ID
0x400C   MERR_SPL_NO_FREE_JOB_ID
0x400D   PMERR_SPL_NO_DATA
0x400D   MERR_SPL_NO_DATA
0x400E   PMERR_SPL_INV_TOKEN
0x400E   MERR_SPL_INV_TOKEN
0x400F   PMERR_SPL_INV_DATATYPE
0x400F   MERR_SPL_INV_DATATYPE
0x4010   PMERR_SPL_PROCESSOR_ERROR
0x4010   MERR_SPL_PROCESSOR_ERROR
0x4011   PMERR_SPL_INV_JOB_ID
0x4011   MERR_SPL_INV_JOB_ID
0x4012   PMERR_SPL_JOB_NOT_PRINTING
0x4012   MERR_SPL_JOB_NOT_PRINTING
0x4013   PMERR_SPL_JOB_PRINTING
0x4013   MERR_SPL_JOB_PRINTING
0x4014   PMERR_SPL_QUEUE_ALREADY_EXISTS
0x4014   MERR_SPL_QUEUE_ALREADY_EXISTS
0x4015   PMERR_SPL_INV_QUEUE_NAME
0x4015   MERR_SPL_INV_QUEUE_NAME
0x4016   PMERR_SPL_QUEUE_NOT_EMPTY
0x4016   MERR_SPL_QUEUE_NOT_EMPTY
0x4017   PMERR_SPL_DEVICE_ALREADY_EXISTS
0x4017   MERR_SPL_DEVICE_ALREADY_EXISTS
0x4018   PMERR_SPL_DEVICE_LIMIT_REACHED
0x4018   MERR_SPL_DEVICE_LIMIT_REACHED
0x4019   PMERR_SPL_STATUS_STRING_TRUNC
0x4019   MERR_SPL_STATUS_STRING_TRUNC
0x401A   PMERR_SPL_INV_LENGTH_OR_COUNT
0x401A   MERR_SPL_INV_LENGTH_OR_COUNT
0x401B   PMERR_SPL_FILE_NOT_FOUND
0x401B   MERR_SPL_FILE_NOT_FOUND
0x401C   PMERR_SPL_CANNOT_OPEN_FILE
0x401C   MERR_SPL_CANNOT_OPEN_FILE
0x401D   PMERR_SPL_DRIVER_NOT_INSTALLED
0x401D   MERR_SPL_DRIVER_NOT_INSTALLED
0x401E   PMERR_SPL_INV_PROCESSOR_DATTYPE
0x401E   MERR_SPL_INV_PROCESSOR_DATTYPE
0x401F   PMERR_SPL_INV_DRIVER_DATATYPE
0x401F   MERR_SPL_INV_DRIVER_DATATYPE
0x4020   PMERR_SPL_PROCESSOR_NOT_INST
0x4020   MERR_SPL_PROCESSOR_NOT_INST
0x4021   PMERR_SPL_NO_SUCH_LOG_ADDRESS
0x4021   MERR_SPL_NO_SUCH_LOG_ADDRESS
0x4022   PMERR_SPL_PRINTER_NOT_FOUND
0x4022   MERR_SPL_PRINTER_NOT_FOUND
0x4023   PMERR_SPL_DD_NOT_FOUND
0x4023   MERR_SPL_DD_NOT_FOUND
0x4024   PMERR_SPL_QUEUE_NOT_FOUND
0x4024   MERR_SPL_QUEUE_NOT_FOUND
0x4025   PMERR_SPL_MANY_QUEUES_ASSOC
0x4025   MERR_SPL_MANY_QUEUES_ASSOC
0x4026   PMERR_SPL_NO_QUEUES_ASSOCIATED
0x4026   MERR_SPL_NO_QUEUES_ASSOCIATED
0x4027   PMERR_SPL_INI_FILE_ERROR
0x4027   MERR_SPL_INI_FILE_ERROR
0x4028   PMERR_SPL_NO_DEFAULT_QUEUE
0x4028   MERR_SPL_NO_DEFAULT_QUEUE
0x4029   PMERR_SPL_NO_CURRENT_FORMS_CODE
0x4029   MERR_SPL_NO_CURRENT_FORMS_CODE
0x402A   PMERR_SPL_NOT_AUTHORISED
0x402A   MERR_SPL_NOT_AUTHORISED
0x402B   PMERR_SPL_TEMP_NETWORK_ERROR
0x402B   MERR_SPL_TEMP_NETWORK_ERROR
0x402C   PMERR_SPL_HARD_NETWORK_ERROR
0x402C   MERR_SPL_HARD_NETWORK_ERROR
0x402D   PMERR_DEL_NOT_ALLOWED
0x402D   MERR_DEL_NOT_ALLOWED
0x402E   PMERR_CANNOT_DEL_QP_REF
0x402E   MERR_CANNOT_DEL_QP_REF
0x402F   PMERR_CANNOT_DEL_QNAME_REF
0x402F   MERR_CANNOT_DEL_QNAME_REF
0x4030   PMERR_CANNOT_DEL_PRINTER_DD_REF
0x4030   MERR_CANNOT_DEL_PRINTER_DD_REF
0x4031   PMERR_CANNOT_DEL_PRN_NAME_REF
0x4031   MERR_CANNOT_DEL_PRN_NAME_REF
0x4032   PMERR_CANNOT_DEL_PRN_ADDR_REF
0x4032   MERR_CANNOT_DEL_PRN_ADDR_REF
0x4033   PMERR_SPOOLER_QP_NOT_DEFINED
0x4033   MERR_SPOOLER_QP_NOT_DEFINED
0x4034   PMERR_PRN_NAME_NOT_DEFINED
0x4034   MERR_PRN_NAME_NOT_DEFINED
0x4035   PMERR_PRN_ADDR_NOT_DEFINED
0x4035   MERR_PRN_ADDR_NOT_DEFINED
0x4036   PMERR_PRINTER_DD_NOT_DEFINED
0x4036   MERR_PRINTER_DD_NOT_DEFINED
0x4037   PMERR_PRINTER_QUEUE_NOT_DEFINED
0x4037   MERR_PRINTER_QUEUE_NOT_DEFINED
0x4038   PMERR_PRN_ADDR_IN_USE
0x4038   MERR_PRN_ADDR_IN_USE
0x4039   PMERR_SPL_TOO_MANY_OPEN_FILES
0x4039   MERR_SPL_TOO_MANY_OPEN_FILES
0x403A   PMERR_SPL_CP_NOT_REQD
0x403A   MERR_SPL_CP_NOT_REQD
0x4040   PMERR_UNABLE_TO_CLOSE_DEVICE
0x4040   MERR_UNABLE_TO_CLOSE_DEVICE
0x4FC9   PMERR_SPLMSGBOX_INFO_CAPTION
0x4FC9   MERR_SPLMSGBOX_INFO_CAPTION
0x4FCA   PMERR_SPLMSGBOX_WARNING_CAPTION
0x4FCA   MERR_SPLMSGBOX_WARNING_CAPTION
0x4FCB   PMERR_SPLMSGBOX_ERROR_CAPTION
0x4FCB   MERR_SPLMSGBOX_ERROR_CAPTION
0x4FCC   PMERR_SPLMSGBOX_SEVERE_CAPTION
0x4FCC   MERR_SPLMSGBOX_SEVERE_CAPTION
0x4FCD   PMERR_SPLMSGBOX_JOB_DETAILS
0x4FCD   MERR_SPLMSGBOX_JOB_DETAILS
0x4FCE   PMERR_SPLMSGBOX_ERROR_ACTION
0x4FCE   MERR_SPLMSGBOX_ERROR_ACTION
0x4FCF   PMERR_SPLMSGBOX_SEVERE_ACTION
0x4FCF   MERR_SPLMSGBOX_SEVERE_ACTION
0x4FD0   PMERR_SPLMSGBOX_BIT_0_TEXT
0x4FD0   MERR_SPLMSGBOX_BIT_0_TEXT
0x4FD1   PMERR_SPLMSGBOX_BIT_1_TEXT
0x4FD1   MERR_SPLMSGBOX_BIT_1_TEXT
0x4FD2   PMERR_SPLMSGBOX_BIT_2_TEXT
0x4FD2   MERR_SPLMSGBOX_BIT_2_TEXT
0x4FD3   PMERR_SPLMSGBOX_BIT_3_TEXT
0x4FD3   MERR_SPLMSGBOX_BIT_3_TEXT
0x4FD4   PMERR_SPLMSGBOX_BIT_4_TEXT
0x4FD4   MERR_SPLMSGBOX_BIT_4_TEXT
0x4FD5   PMERR_SPLMSGBOX_BIT_5_TEXT
0x4FD5   MERR_SPLMSGBOX_BIT_5_TEXT
0x4FD6   PMERR_SPLMSGBOX_BIT_15_TEXT
0x4FD6   MERR_SPLMSGBOX_BIT_15_TEXT
0x4FD7   PMERR_SPL_NOPATHBUFFER
0x4FD7   MERR_SPL_NOPATHBUFFER
0x4FD8   MERR_SPL_ALREADY_INITIALISED
0x4FD9   MERR_SPL_ERROR
0x5001   PMERR_INV_TYPE
0x5001   MERR_INV_TYPE
0x5002   PMERR_INV_CONV
0x5002   MERR_INV_CONV
0x5003   PMERR_INV_SEGLEN
0x5003   MERR_INV_SEGLEN
0x5004   PMERR_DUP_SEGNAME
0x5004   MERR_DUP_SEGNAME
0x5005   PMERR_INV_XFORM
0x5005   MERR_INV_XFORM
0x5006   PMERR_INV_VIEWLIM
0x5006   MERR_INV_VIEWLIM
0x5007   PMERR_INV_3DCOORD
0x5007   MERR_INV_3DCOORD
0x5008   PMERR_SMB_OVFLOW
0x5008   MERR_SMB_OVFLOW
0x5009   PMERR_SEG_OVFLOW
0x5009   MERR_SEG_OVFLOW
0x5010   PMERR_PIC_DUP_FILENAME
0x5010   MERR_PIC_DUP_FILENAME
SPLERR_BASE+0FA1   PMERR_SPL_ERROR_1
SPLERR_BASE+0FA2   PMERR_SPL_ERROR_2
SPLERR_BASE+0FA3   PMERR_SPL_ERROR_3
SPLERR_BASE+0FA4   PMERR_SPL_ERROR_4
SPLERR_BASE+0FA5   PMERR_SPL_ERROR_5
SPLERR_BASE+0FA6   PMERR_SPL_ERROR_6
SPLERR_BASE+0FA7   PMERR_SPL_ERROR_7
SPLERR_BASE+0FA8   PMERR_SPL_ERROR_8
SPLERR_BASE+0FA9   PMERR_SPL_ERROR_9
SPLERR_BASE+0FAA   PMERR_SPL_ERROR_10
SPLERR_BASE+0FAB   PMERR_SPL_ERROR_11
SPLERR_BASE+0FAC   PMERR_SPL_ERROR_12
SPLERR_BASE+0FAD   PMERR_SPL_ERROR_13
SPLERR_BASE+0FAE   PMERR_SPL_ERROR_14
SPLERR_BASE+0FAF   PMERR_SPL_ERROR_15
SPLERR_BASE+0FB0   PMERR_SPL_ERROR_16
SPLERR_BASE+0FB1   PMERR_SPL_ERROR_17
SPLERR_BASE+0FB2   PMERR_SPL_ERROR_18
SPLERR_BASE+0FB3   PMERR_SPL_ERROR_19
SPLERR_BASE+0FB4   PMERR_SPL_ERROR_20
SPLERR_BASE+0FB5   PMERR_SPL_ERROR_21
SPLERR_BASE+0FB6   PMERR_SPL_ERROR_22
SPLERR_BASE+0FB7   PMERR_SPL_ERROR_23
SPLERR_BASE+0FB8   PMERR_SPL_ERROR_24
SPLERR_BASE+0FB9   PMERR_SPL_ERROR_25
SPLERR_BASE+0FBA   PMERR_SPL_ERROR_26
SPLERR_BASE+0FBB   PMERR_SPL_ERROR_27
SPLERR_BASE+0FBC   PMERR_SPL_ERROR_28
SPLERR_BASE+0FBD   PMERR_SPL_ERROR_29
SPLERR_BASE+0FBE   PMERR_SPL_ERROR_30
SPLERR_BASE+0FBF   PMERR_SPL_ERROR_31
SPLERR_BASE+0FC0   PMERR_SPL_ERROR_32
SPLERR_BASE+0FC1   PMERR_SPL_ERROR_33
SPLERR_BASE+0FC2   PMERR_SPL_ERROR_34
SPLERR_BASE+0FC3   PMERR_SPL_ERROR_35
SPLERR_BASE+0FC4   PMERR_SPL_ERROR_36
SPLERR_BASE+0FC5   PMERR_SPL_ERROR_37
SPLERR_BASE+0FC6   PMERR_SPL_ERROR_38
SPLERR_BASE+0FC7   PMERR_SPL_ERROR_39
SPLERR_BASE+0FC8   PMERR_SPL_ERROR_40
SPLERR_BASE+0FFF   PMERR_SPL_ERROR
SPLERR_BASE+0FFD   PMERR_SPL_ALREADY_INITIALISED
/**************************************************************/


/* This appendix gives an explanation for each PM error.
   The errors are listed in alphabetic order.
   The number associated with each error is given in Error Number and Name.
*/

Error Constant Explanation

HMERR_ALLOCATE_SEGMENT Unable to allocate a segment of memory for memory allocation requests from the Help Manager.

HMERR_CLOSE_LIB_FILE The library file cannot be closed.

HMERR_CONTENT_NOT_FOUND The library file does not have any content.

HMERR_DATABASE_NOT_OPEN Unable to read the unopened database.

HMERR_DDF_ALIGN_TYPE The alignment type is not valid.

HMERR_DDF_BACKCOLOR The background color is not valid.

HMERR_DDF_EXCEED_MAX_INC The value specified to increment DDF memory is too large.

HMERR_DDF_EXCEED_MAX_LENGTH The amount of data is too large for the DDF buffer.

HMERR_DDF_FONTSTYLE The font style is not valid.

HMERR_DDF_FORECOLOR The foreground color is not valid.

HMERR_DDF_FORMAT_TYPE The format type specified is invalid.

HMERR_DDF_HINSTANCE The DDF instance is invalid.

HMERR_DDF_INVALID_DDF The DDF handle is invalid.

HMERR_DDF_INVALID_FONT The font value specified is invalid.

HMERR_DDF_INVALID_PARM One of the DDF parameters specified is invalid.

HMERR_DDF_LIST_BREAKTYPE The value of BreakType is not valid.

HMERR_DDF_LIST_SPACING The value for Spacing is not valid.

HMERR_DDF_LIST_UNCLOSED An attempt was made to nest a list.

HMERR_DDF_LIST_UNINITIALIZED No definition list has been initialized by DdfBeginList.

HMERR_DDF_MEMORY Not enough memory is available.

HMERR_DDF_REFTYPE The reference type is not valid.

HMERR_DDF_SEVERE Internal error detected by the Help Manager.

HMERR_FREE_MEMORY Unable to free allocated memory.

HMERR_HELP_INST_CALLED_INVALID The handle of the instance specified on a call to the Help Manager does not have the class name of a Help Manager instance.

HMERR_HELP_INSTANCE_UNDEFINE The help instance handle specified is invalid.

HMERR_HELPITEM_NOT_FOUND Context-sensitive help was requested but the ID of the main help item specified was not found in the help table.

HMERR_HELPSUBITEM_NOT_FOUND Context-sensitive help was requested but the ID of the help item specified was not found in the help subtable.

HMERR_HELPTABLE_UNDEFINE The application did not provide a help table for context-sensitive help.

HMERR_INDEX_NOT_FOUND The index is not in the library file.

HMERR_INVALID_ASSOC_APP_WND The application window handle specified on the WinAssociateHelpInstance function is not a valid window handle.

HMERR_INVALID_ASSOC_HELP_INST The help instance handle specified on the WinAssociateHelpInstance function is not a valid window handle.

HMERR_INVALID_DESTROY_HELP_INST The window handle specified as the help instance to destroy is not of the help instance class.

HMERR_INVALID_HELP_INSTANCE_HDL The handle specified to be a help instance does not have the class name of a Help Manager instance.

HMERR_INVALID_HELPSUBITEM_SIZE The help subtable item size is less than 2.

HMERR_INVALID_LIB_FILE Improper library file provided.

HMERR_INVALID_QUERY_APP_WND The application window specified on a WinQueryHelpInstance function is not a valid window handle.

HMERR_LOAD_DLL Unable to load resource data link library.

HMERR_NO_FRAME_WND_IN_CHAIN There is no frame window in the window chain from which to find or set the associated help instance.

HMERR_NO_HELP_INST_IN_CHAIN The parent or owner chain of the application window specified does not have an associated help instance.

HMERR_NO_MEMORY Unable to allocate the requested amount of memory.

HMERR_OPEN_LIB_FILE The library file cannot be opened.

HMERR_PANEL_NOT_FOUND Unable to find the requested help panel.

HMERR_READ_LIB_FILE The library file cannot be read.

PMERR_ACCESS_DENIED The memory block was not allocated properly.

PMERR_ALREADY_IN_AREA An attempt was made to begin a new area while an existing area bracket was already open.

PMERR_ALREADY_IN_ELEMENT An attempt was made to begin a new element while an existing element bracket was already open.

PMERR_ALREADY_IN_PATH An attempt was made to begin a new path while an existing path bracket was already open.

PMERR_ALREADY_IN_SEG An attempt was made to open a new segment while an existing segment bracket was already open.

PMERR_APPL_STRUCTURE_TOO_SMALL The application buffer length is less than the total length required for the (application) component types.

PMERR_AREA_INCOMPLETE One of the following has occurred:
o A segment has been opened , closed,
 or drawn.
o GpiAssociate was issued while an
 area bracket was open.
o A drawn segment has opened an area
 bracket and ended without closing it.

PMERR_ARRAY_TOO_LARGE More than 4 bytes was attempted to be inserted or extracted.

PMERR_ARRAY_TOO_SMALL The array specified was too small.

PMERR_ATOM_NAME_NOT_FOUND The specified atom name is not in the atom table.

PMERR_BASE_ERROR An OS/2 base error has occurred.  The base error code can be accessed using the OffBinaryData field of the ERRINFO structure returned by WinGetErrorInfo.

PMERR_BITMAP_IN_USE An attempt was made either to set a bit map into a device context using GpiSetBitmap while it was already selected into an existing device context, or to tag a bit map with a local pattern set identifier (setid) using GpiSetBitmapId while it was already tagged with an existing setid.

PMERR_BITMAP_IS_SELECTED An attempt was made to delete a bit map while it was selected into a device context.

PMERR_BITMAP_NOT_FOUND A attempt was made to perform a bit-map operation on a bit map that did not exist.

PMERR_BITMAP_NOT_SELECTED A attempt was made to perform an operation on presentation space associated with a memory device context that had no selected bit map.

PMERR_BOUNDS_OVERFLOW An internal overflow error occurred during boundary data accumulation.  This can occur if coordinates or matrix transformation elements (or both) are invalid or too large.

PMERR_BUFFER_TOO_SMALL The supplied buffer was not large enough for the data to be returned.

PMERR_C_LENGTH_TOO_SMALL The maximum length of the C structure is less than the total length required for the (C) component types.

PMERR_CALLED_SEG_IS_CHAINED An attempt was made to call a segment that has a chained attribute set.

PMERR_CALLED_SEG_IS_CURRENT An attempt was made to call a segment that is currently open.

PMERR_CALLED_SEG_NOT_FOUND An attempt was made to call a segment that did not exist.

PMERR_CAN_NOT_CALL_SPOOLER An error occurred attempting to call the spooler validation routine.  This error is not raised if the spooler is not installed.

PMERR_CANNOT_DEL_PRINTER_DD_REF Presentation Manager device driver deletion not possible due to a reference.

PMERR_CANNOT_DEL_PRN_ADDR_REF Printer port deletion not possible due to a reference.

PMERR_CANNOT_DEL_PRN_NAME_REF Printer deletion not possible due to a reference.

PMERR_CANNOT_DEL_QNAME_REF Spooler queue deletion not possible due to a reference.

PMERR_CANNOT_DEL_QP_REF Spooler queue processor deletion not possible due to a reference.

PMERR_CANNOT_SET_FOCUS Focus cannot be set if a focus change is in progress, or if a system-modal window exists.

PMERR_CANNOT_STOP The session cannot be stopped.

PMERR_COL_TABLE_NOT_REALIZABLE An attempt was made to realize a color table that is not realizable.

PMERR_COL_TABLE_NOT_REALIZED An attempt was made to realize a color table on a device driver that does not support this function.

PMERR_COORDINATE_OVERFLOW An internal coordinate overflow error occurred.  This can occur if coordinates or matrix transformation elements (or both) are invalid or too large.

PMERR_DATA_TOO_LONG An attempt was made to transfer more than the maximum permitted amount of data (64512 bytes) using GpiPutData, GpiGetData, or GpiElement.

PMERR_DATATYPE_ENTRY_BAD_INDEX An invalid datatype entry index was specified.

PMERR_DATATYPE_ENTRY_CTL_BAD An invalid datatype entry control was specified.

PMERR_DATATYPE_ENTRY_CTL_MISS The datatype entry control was missing.

PMERR_DATATYPE_ENTRY_NOT_NUM The datatype entry specified was not numerical.

PMERR_DATATYPE_ENTRY_NOT_OFF The datatype entry specified was not an offset.

PMERR_DATATYPE_INVALID An invalid datatype was specified.

PMERR_DATATYPE_NOT_UNIQUE An attempt to register a datatype failed because it is not unique.

PMERR_DATATYPE_TOO_LONG The datatype specified was too long.

PMERR_DATATYPE_TOO_SMALL The datatype specified was too small.

PMERR_DC_IS_ASSOCIATED An attempt was made to associate a presentation space with a device context that was already associated or to destroy a device context that was associated.

PMERR_DEL_NOT_ALLOWED Deletion not possible.

PMERR_DESC_STRING_TRUNCATED An attempt was made to supply a description string with GpiBeginElement that was greater then the permitted maximum length (251 characters).  The string was truncated.

PMERR_DEV_FUNC_NOT_INSTALLED The function requested is not supported by the presentation driver.

PMERR_DEVICE_DRIVER_ERROR_1 Miscellaneous error available for use by user written device drivers.

PMERR_DEVICE_DRIVER_ERROR_10 Miscellaneous error available for use by user written device drivers.

PMERR_DEVICE_DRIVER_ERROR_2 Miscellaneous error available for use by user written device drivers.

PMERR_DEVICE_DRIVER_ERROR_3 Miscellaneous error available for use by user written device drivers.

PMERR_DEVICE_DRIVER_ERROR_4 Miscellaneous error available for use by user written device drivers.

PMERR_DEVICE_DRIVER_ERROR_5 Miscellaneous error available for use by user written device drivers.

PMERR_DEVICE_DRIVER_ERROR_6 Miscellaneous error available for use by user written device drivers.

PMERR_DEVICE_DRIVER_ERROR_7 Miscellaneous error available for use by user written device drivers.

PMERR_DEVICE_DRIVER_ERROR_8 Miscellaneous error available for use by user written device drivers.

PMERR_DEVICE_DRIVER_ERROR_9 Miscellaneous error available for use by user written device drivers.

PMERR_DOS_ERROR A DOS call returned an error.

PMERR_DOSOPEN_FAILURE A DosOpen call made during GpiLoadMetaFile or GpiSaveMetaFile gave a good return code but the file was not opened successfully.

PMERR_DOSREAD_FAILURE A DosRead call made during GpiLoadMetaFile gave a good return code.  However, it failed to read any more bytes although the file length indicated that there were more to be read.

PMERR_DRIVER_NOT_FOUND The device driver specified with DevPostDeviceModes was not found.

PMERR_DUP_SEG During GpiPlayMetaFile, while the actual drawing mode was draw-and-retain or retain, a metafile segment to be stored in the presentation space was found to have the same segment identifier as an existing segment.

PMERR_DUP_SEGNAME A called segment has a name that has already been used by another called segment in the input PIF.

PMERR_DUPLICATE_TITLE The program title specified in the PIBSTRUCT already exists within the same group.

PMERR_DYNAMIC_SEG_SEQ_ERROR During removal of dynamic segments while processing GpiDrawChain, GpiDrawFrom, or GpiDrawSegment, the internal state indicated that dynamic segment data was still visible after all chained dynamic segments had been processed.  This can occur if segments drawn dynamically (including called segments) are modified or removed from the chain while visible.

PMERR_DYNAMIC_SEG_ZERO_INV An attempt was been made to open a dynamic segment with a segment identifier of zero.

PMERR_ENDDOC_NOT_ISSUED A request to close the spooled output without first issuing a an ENDDOC was attempted.

PMERR_ESC_CODE_NOT_SUPPORTED The code specified with DevEscape is not supported by the target device driver.

PMERR_EXCEEDS_MAX_SEG_LENGTH During metafile creation or generation of retained graphics the system has exceeded maximum segment size.

PMERR_FONT_AND_MODE_MISMATCH An attempt was made to draw characters with a character mode and character set that are incompatible.  For example, the character specifies an image/raster font when the mode calls for a vector/outline font.

PMERR_FONT_FILE_NOT_LOADED An attempt was made to unload a font file that was not loaded.

PMERR_FONT_NOT_LOADED An attempt was made to create a font that was not loaded.

PMERR_FUNCTION_NOT_SUPPORTED The function is not supported.

PMERR_GREATER_THAN_64K A data item or array dimension is greater than 65 535.

PMERR_HBITMAP_BUSY An internal bit map busy error was detected.  The bit map was locked by one thread during an attempt to access it from another thread.

PMERR_HDC_BUSY An internal device context busy error was detected.  The device context was locked by one thread during an attempt to access it from another thread.

PMERR_HEAP_MAX_SIZE_REACHED The heap has reached its maximum size (64KB), and cannot be increased.

PMERR_HEAP_OUT_OF_MEMORY An attempt to increase the size of the heap failed.

PMERR_HFONT_IS_SELECTED An attempt has been made to either change the owner of a font, or delete when it is currently selected.

PMERR_HRGN_BUSY An internal region busy error was detected.  The region was locked by one thread during an attempt to access it from another thread.

PMERR_HUGE_FONTS_NOT_SUPPORTED An attempt was made using GpiSetCharSet, GpiSetPatternSet, GpiSetMarkerSet, or GpiSetAttrs to select a font that is larger than the maximum size (64Kb) supported by the target device driver.

PMERR_ID_HAS_NO_BITMAP No bit map was tagged with the setid specified on a GpiQueryBitmapHandle function.

PMERR_IMAGE_INCOMPLETE A drawn segment has opened an image bracket and ended without closing it.

PMERR_INCOMPATIBLE_BITMAP An attempt was made to select a bit map or perform a BitBlt operation on a device context that was incompatible with the format of the bit map.

PMERR_INCOMPATIBLE_METAFILE An attempt was made to associate a presentation space and a metafile device context with incompatible page units, size or coordinate format; or to play a metafile using the RES_RESET option (to reset the presentation space) to a presentation space that is itself associated with a metafile device context.

PMERR_INCORRECT_DATATYPE A data type is specified which is incorrect for this function.

PMERR_INCORRECT_DC_TYPE An attempt was made to perform a bit-map operation on a presentation space associated with a device context of a type that is unable to support bit-map operations.

PMERR_INCORRECT_HSTRUCT A structure handle is non-NULL, and is invalid for one of the following reasons:
    It is not the handle of a data structure.
    It is the handle of an ERRINFO
 structure, which should not be used in
 this call.
    A handle block returned by the bindings
 to the application has been used for an
 in-line structure handle.

PMERR_INI_FILE_IS_SYS_OR_USER User or system initialization file cannot be closed.

PMERR_INSUFF_SPACE_TO_ADD The initialization file could not be extended to add the required program or group.

PMERR_INSUFFICIENT_DISK_SPACE The operation terminated through insufficient disk space.

PMERR_INSUFFICIENT_MEMORY The operation terminated through insufficient memory.

PMERR_INV_3DCOORD An order specifying 3-dimensional coordinates has been found in the input PIF.

PMERR_INV_ANGLE_PARM An invalid angle parameter was specified with GpiPartialArc.

PMERR_INV_ARC_CONTROL An invalid control parameter was specified with GpiFullArc.

PMERR_INV_AREA_CONTROL An invalid options parameter was specified with GpiBeginArea.

PMERR_INV_ATTR_MODE An invalid mode parameter was specified with GpiSetAttrMode.

PMERR_INV_BACKGROUND_COL_ATTR An invalid background color attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_BACKGROUND_MIX_ATTR An invalid background mix attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_BITBLT_MIX An invalid lRop was specified with a GpiBitBlt or GpiWCBitBlt function.

PMERR_INV_BITBLT_STYLE An invalid options parameter was specified with a GpiBitBlt or GpiWCBitBlt function.

PMERR_INV_BITMAP_DATA In processing a bit map, the end of the data was unexpectedly encountered.

PMERR_INV_BITMAP_DIMENSION An invalid dimension was specified with a load bit-map function.

PMERR_INV_BOX_CONTROL An invalid control parameter was specified with GpiBox.

PMERR_INV_BOX_ROUNDING_PARM An invalid corner rounding control parameter was specified with GpiBox.

PMERR_INV_CHAR_ALIGN_ATTR The text alignment attribute specified in GpiSetTextAlignment is not valid.

PMERR_INV_CHAR_ANGLE_ATTR The default character angle attribute value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_CHAR_DIRECTION_ATTR An invalid character direction attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_CHAR_MODE_ATTR An invalid character mode attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_CHAR_POS_OPTIONS An invalid options parameter was specified with GpiCharStringPos or GpiCharStringPosAt.

PMERR_INV_CHAR_SET_ATTR An invalid character setid attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_CHAR_SHEAR_ATTR An invalid character shear attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_CLIP_PATH_OPTIONS An invalid options parameter was specified with GpiSetClipPath.

PMERR_INV_CODEPAGE An invalid code-page parameter was specified with GpiSetCp.

PMERR_INV_COLOR_ATTR An invalid color attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_COLOR_DATA Invalid color table definition data was specified with GpiCreateLogColorTable.

PMERR_INV_COLOR_FORMAT An invalid format parameter was specified with GpiCreateLogColorTable.

PMERR_INV_COLOR_INDEX An invalid color index parameter was specified with GpiQueryRGBColor.

PMERR_INV_COLOR_OPTIONS An invalid options parameter was specified with a logical color table or color query function.

PMERR_INV_COLOR_START_INDEX An invalid starting index parameter was specified with a logical color table or color query function.

PMERR_INV_CONV Invalid conversion-type parameter.

PMERR_INV_COORD_OFFSET An invalid coordinate offset value was specified.

PMERR_INV_COORD_SPACE An invalid source or target coordinate space parameter was specified with GpiConvert.

PMERR_INV_COORDINATE An invalid coordinate value was specified.

PMERR_INV_CORRELATE_DEPTH An invalid maxdepth parameter was specified with GpiCorrelateSegment, GpiCorrelateFrom, or GpiCorrelateChain.

PMERR_INV_CORRELATE_TYPE An invalid type parameter was specified with GpiCorrelateSegment, GpiCorrelateFrom, or GpiCorrelateChain.

PMERR_INV_CURSOR_BITMAP An invalid pointer was referenced with WinSetPointer.

PMERR_INV_DC_DATA An invalid data parameter was specified with DevOpenDC.

PMERR_INV_DC_TYPE An invalid type parameter was specified with DevOpenDC, or a function was issued that is invalid for a OD_METAFILE_NOQUERY device context.

PMERR_INV_DEV_MODES_OPTIONS An invalid options parameter was specified with DevPostDeviceModes.

PMERR_INV_DEVICE_NAME An invalid devicename parameter was specified with DevPostDeviceModes.

PMERR_INV_DRAW_BORDER_OPTION An invalid option parameter was specified with WinDrawBorder.

PMERR_INV_DRAW_CONTROL An invalid control parameter was specified with GpiSetDrawControl or GpiQueryDrawControl.

PMERR_INV_DRAW_VALUE An invalid value parameter was specified with GpiSetDrawControl.

PMERR_INV_DRAWING_MODE An invalid mode parameter was specified with GpiSetDrawControl not draw-and-retain or draw.

PMERR_INV_DRIVER_DATA Invalid driver data was specified.

PMERR_INV_DRIVER_NAME A driver name was specified which has not been installed.

PMERR_INV_EDIT_MODE An invalid mode parameter was specified with GpiSetEditMode.

PMERR_INV_ELEMENT_OFFSET An invalid off (offset) parameter was specified with GpiQueryElement.

PMERR_INV_ELEMENT_POINTER An attempt was made to issue GpiPutData with the element pointer not pointing at the last element.

PMERR_INV_END_PATH_OPTIONS An attempt to create or delete a path out of context of the path bracket was made.

PMERR_INV_ESC_CODE An invalid escape code was used in a call to DevEscape.

PMERR_INV_ESCAPE_DATA An invalid data parameter was specified with DevEscape.

PMERR_INV_FACENAME An invalid font family name was passed to GpiQueryFaceString.

PMERR_INV_FACENAMEDESC The font facename description is invalid.

PMERR_INV_FILL_PATH_OPTIONS An invalid options parameter was specified with GpiFillPath.

PMERR_INV_FIRST_CHAR An invalid firstchar parameter was specified with GpiQueryWidthTable.

PMERR_INV_FLOOD_FILL_OPTIONS Invalid flood fill parameters were specified.

PMERR_INV_FONT_ATTRS An invalid attrs parameter was specified with GpiCreateLogFont.

PMERR_INV_FONT_FILE_DATA The font file specified with GpiLoadFonts, GpiLoadPublicFonts, GpiQueryFontFileDescriptions, or GpiQueryFullFontFileDescs contains invalid data.

PMERR_INV_FOR_THIS_DC_TYPE An attempt has been made to issue GpiRemoveDynamics or GpiDrawDynamics to a presentation space associated with a metafile device context.

PMERR_INV_FORMS_CODE An invalid forms code parameter was specified with DevQueryHardcopyCaps.

PMERR_INV_GEOM_LINE_WIDTH_ATTR An invalid geometric line width attribute value was specified.

PMERR_INV_GETDATA_CONTROL An invalid format parameter was specified with GpiGetData.

PMERR_INV_GRAPHICS_FIELD An invalid field parameter was specified with GpiSetGraphicsField.

PMERR_INV_HBITMAP An invalid bit-map handle was specified.

PMERR_INV_HDC An invalid device-context handle or (micro presentation space) presentation-space handle was specified.

PMERR_INV_HFONT An invalid font handle was specified.

PMERR_INV_HMF An invalid metafile handle was specified.

PMERR_INV_HPAL An invalid color palette handle was specified.

PMERR_INV_HPS An invalid presentation-space handle was specified.

PMERR_INV_HRGN An invalid region handle was specified.

PMERR_INV_ID An invalid lPSid parameter was specified with GpiRestorePS.

PMERR_INV_IMAGE_DATA_LENGTH An invalid lLength parameter was specified with GpiImage. There is a mismatch between the image size and the data length.

PMERR_INV_IMAGE_DIMENSION An invalid psizlImageSize parameter was specified with GpiImage.

PMERR_INV_IMAGE_FORMAT An invalid lFormat parameter was specified with GpiImage.

PMERR_INV_IN_AREA An attempt was made to issue a function invalid inside an area bracket. This can be detected while the actual drawing mode is draw or draw-and-retain or during segment drawing or correlation functions.

PMERR_INV_IN_CURRENT_EDIT_MODE An attempt was made to issue a function invalid inside the current editing mode.

PMERR_INV_IN_ELEMENT An attempt was made to issue a function invalid inside an element bracket.

PMERR_INV_IN_IMAGE An attempt was made to issue a function invalid inside an element bracket.

PMERR_INV_IN_PATH An attempt was made to issue a function invalid inside a path bracket.

PMERR_INV_IN_RETAIN_MODE An attempt was made to issue a function (for example, query) that is invalid when the actual drawing mode is not draw or draw-and-retain.

PMERR_INV_IN_SEG An attempt was made to issue a function invalid inside a segment bracket.

PMERR_INV_IN_VECTOR_SYMBOL An invalid order was detected inside a vector symbol definition while drawing a vector (outline) font.

PMERR_INV_INFO_TABLE An invalid bit-map info table was specified with a bit-map operation.

PMERR_INV_LENGTH_OR_COUNT An invalid length or count parameter was specified.

PMERR_INV_LINE_END_ATTR An invalid line end attribute value was specified.

PMERR_INV_LINE_JOIN_ATTR An invalid line join attribute value was specified.

PMERR_INV_LINE_TYPE_ATTR An invalid line type attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_LINE_WIDTH_ATTR An invalid line width attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_LOGICAL_ADDRESS An invalid device logical address was specified.

PMERR_INV_MARKER_BOX_ATTR An invalid marker box attribute value was specified.

PMERR_INV_MARKER_SET_ATTR An invalid marker set attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_MARKER_SYMBOL_ATTR An invalid marker symbol attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_MATRIX_ELEMENT An invalid transformation matrix element was specified.

PMERR_INV_MAX_HITS An invalid maxhits parameter was specified with GpiCorrelateSegment, GpiCorrelateFrom, or GpiCorrelateChain.

PMERR_INV_METAFILE An invalid metafile was specified with GpiPlayMetaFile.

PMERR_INV_METAFILE_LENGTH An invalid length parameter was specified with GpiSetMetaFileBits or GpiQueryMetaFileBits.

PMERR_INV_METAFILE_OFFSET An invalid length parameter was specified with GpiSetMetaFileBits or GpiQueryMetaFileBits.

PMERR_INV_MICROPS_DRAW_CONTROL A draw control parameter was specified with GpiSetDrawControl that is invalid in a micro presentation space.

PMERR_INV_MICROPS_FUNCTION An attempt was made to issue a function that is invalid in a micro presentation space.

PMERR_INV_MICROPS_ORDER An attempt was made to play a metafile containing orders that are invalid in a micro presentation space.

PMERR_INV_MIX_ATTR An invalid mix attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_MODE_FOR_OPEN_DYN An attempt was made to open a segment with the ATTR_DYNAMIC segment set, while the drawing mode was set to DM_DRAW or DM_DRAWANDRETAIN.

PMERR_INV_MODE_FOR_REOPEN_SEG An attempt was made to reopen an existing segment while the drawing mode was set to DM_DRAW or DM_DRAWANDRETAIN.

PMERR_INV_MODIFY_PATH_MODE An invalid mode parameter was specified with GpiModifyPath.

PMERR_INV_MULTIPLIER An invalid multiplier parameter was specified with GpiPartialArc or GpiFullArc.

PMERR_INV_NESTED_FIGURES Nested figures have been detected within a path definition.

PMERR_INV_OR_INCOMPAT_OPTIONS An invalid or incompatible (with micro presentation space) options parameter was specified with GpiCreatePS or GpiSetPS.

PMERR_INV_ORDER_LENGTH An invalid order length was detected during GpiPutData or segment drawing.

PMERR_INV_ORDERING_PARM An invalid order parameter was specified with GpiSetSegmentPriority.

PMERR_INV_OUTSIDE_DRAW_MODE An attempt was made to issue a GpiSavePS or GpiRestorePS function, or an output only function (for example, GpiPaintRegion) from GpiPlayMetaFile without the drawing mode set to DM_DRAW.

PMERR_INV_PAGE_VIEWPORT An invalid viewport parameter was specified with GpiSetPageViewport.

PMERR_INV_PATH_ID An invalid path identifier parameter was specified.

PMERR_INV_PATTERN_ATTR An invalid pattern symbol attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_PATTERN_REF_PT_ATTR An invalid refpoint attribute value was specified.

PMERR_INV_PATTERN_SET_ATTR An invalid pattern set attribute value was specified or the default value was explicitly specified with GpiSetAttrs instead of using the defaults mask.

PMERR_INV_PATTERN_SET_FONT An attempt was made to use an unsuitable font as a pattern set.

PMERR_INV_PICK_APERTURE_OPTION An invalid options parameter was specified with GpiSetPickApertureSize.

PMERR_INV_PICK_APERTURE_POSN An invalid pick aperture position was specified.

PMERR_INV_PICK_APERTURE_SIZE An invalid size parameter was specified with GpiSetPickApertureSize.

PMERR_INV_PLAY_METAFILE_OPTION An invalid option parameter was specified with GpiPlayMetaFile.

PMERR_INV_PRIMITIVE_TYPE An invalid primitive type parameter was specified with GpiSetAttrs or GpiQueryAttrs.

PMERR_INV_PS_SIZE An invalid size parameter was specified with GpiCreatePS or GpiSetPS.

PMERR_INV_PUTDATA_FORMAT An invalid format parameter was specified with GpiPutData.

PMERR_INV_QUERY_ELEMENT_NO An invalid start parameter was specified with DevQueryCaps.

PMERR_INV_RECT An invalid rectangle parameter was specified.

PMERR_INV_REGION_CONTROL An invalid control parameter was specified with GpiQueryRegionRects.

PMERR_INV_REGION_MIX_MODE An invalid mode parameter was specified with GpiCombineRegion.

PMERR_INV_REPLACE_MODE_FUNC An attempt was made to issue GpiPutData with the editing mode set to SEGEM_REPLACE.

PMERR_INV_RESERVED_FIELD An invalid reserved field was specified.

PMERR_INV_RESET_OPTIONS An invalid options parameter was specified with GpiResetPS.

PMERR_INV_RGBCOLOR An invalid rgb color parameter was specified with GpiQueryNearestColor or GpiQueryColor.

PMERR_INV_SCAN_START An invalid scanstart parameter was specified with a bit-map function.

PMERR_INV_SEG_ATTR An invalid attribute parameter was specified with GpiSetSegmentAttrs, GpiQuerySegmentAttrs, GpiSetInitialSegmentAttrs, or GpiQueryInitialSegmentAttrs.

PMERR_INV_SEG_ATTR_VALUE An invalid attribute value parameter was specified with GpiSetSegmentAttrs or GpiSetInitialSegmentAttrs.

PMERR_INV_SEG_NAME An invalid segment identifier was specified.

PMERR_INV_SEG_OFFSET An invalid offset parameter was specified with GpiPutData.

PMERR_INV_SEGLEN An order length exceeds the remaining segment length in the input PIF.

PMERR_INV_SETID An invalid setid parameter was specified.

PMERR_INV_SHARPNESS_PARM An invalid sharpness parameter was specified with GpiPolyFilletSharp.

PMERR_INV_STOP_DRAW_VALUE An invalid value parameter was specified with GpiSetStopDraw.

PMERR_INV_TRANSFORM_TYPE An invalid options parameter was specified with a transform matrix function.

PMERR_INV_TYPE Invalid file-type parameter.

PMERR_INV_USAGE_PARM An invalid options parameter was specified with GpiCreateBitmap.

PMERR_INV_VIEWING_LIMITS An invalid limits parameter was specified with GpiSetViewingLimits.

PMERR_INV_VIEWLIM A set viewing limits order has an inconsistent mask and order length in the input PIF.

PMERR_INV_XFORM A set (default) viewing transform order has an inconsistent mask and order length in the input PIF.

PMERR_INVALID_APPL Attempted to start an application whose type is not recognized by OS/2.

PMERR_INVALID_ARRAY_COUNT An array has an invalid count, that is, less than or equal to zero.

PMERR_INVALID_ARRAY_SIZE A control data type array size is invalid.

PMERR_INVALID_ASCIIZ The profile string is not a valid zero-terminated string.

PMERR_INVALID_ATOM The specified atom does not exist in the atom table.

PMERR_INVALID_ATOM_NAME An invalid atom name string was passed.

PMERR_INVALID_BUNDLE_TYPE An invalid bundle type was passed.

PMERR_INVALID_CHARACTER_INDEX On WinNextChar or WinPrevChar, a character index is invalid, that is, it is less than 1 or is greater than the string length+1.

PMERR_INVALID_CONTROL_DATATYPE An invalid control data type was specified.

PMERR_INVALID_DATATYPE An invalid data type was specified.

PMERR_INVALID_DST_CODEPAGE The destination code page parameter is invalid.

PMERR_INVALID_ERRORINFO_HANDLE On WinFreeErrorInfo, the ERRINFO is not the handle of an ERRINFO structure, that is, it was not created by WinGetErrorInfo.

PMERR_INVALID_FLAG An invalid bit was set for a parameter. Use constants defined by PM for options, and do not set any reserved bits.

PMERR_INVALID_FREE_MESSAGE_ID An invalid message identifier was specified. The call has completed by assuming the message parameter and reply data types to be ULONG.

PMERR_INVALID_GROUP_HANDLE An invalid program-group handle was specified.

PMERR_INVALID_HACCEL An invalid accelerator-table handle was specified.

PMERR_INVALID_HAPP The application handle passed to WinTerminateApp does not correspond to a valid session.

PMERR_INVALID_HATOMTBL An invalid atom-table handle was specified.

PMERR_INVALID_HEAP_POINTER An invalid pointer was found within the heap.

PMERR_INVALID_HEAP_SIZE Invalid data was found within the heap.

PMERR_INVALID_HEAP_SIZE_PARM Invalid data was found within the heap.

PMERR_INVALID_HEAP_SIZE_WORD Invalid data was found within the heap.

PMERR_INVALID_HENUM An invalid enumeration handle was specified.

PMERR_INVALID_HHEAP An invalid heap handle was specified.

PMERR_INVALID_HMQ An invalid message-queue handle was specified.

PMERR_INVALID_HPTR An invalid pointer handle was specified.

PMERR_INVALID_HSTRUCT An invalid (null) structure handle was specified.

PMERR_INVALID_HWND An invalid window handle was specified.

PMERR_INVALID_INI_FILE_HANDLE An invalid initialization-file handle was specified.

PMERR_INVALID_INTEGER The specified atom is not a valid integer atom.

PMERR_INVALID_INTEGER_ATOM The specified atom is not a valid integer atom.

PMERR_INVALID_MESSAGE_ID A message identifier is invalid.

PMERR_INVALID_NUMBER_OF_PARMS The number of parameters is invalid.

PMERR_INVALID_NUMBER_OF_TYPES The function call has an invalid number (zero) of types.

PMERR_INVALID_PARAMETER An application parameter value is invalid for its converted PM type. For example: a 4-byte value outside the range -32,768 to +32,767 cannot be converted to a SHORT, and a negative number cannot be converted to a ULONG or USHORT.

PMERR_INVALID_PARAMETER_TYPE A parameter type is invalid for a bundle mask.

PMERR_INVALID_PARAMETERS An application parameter value is invalid for its converted PM type. For example: a 4-byte value outside the range -32 768 to +32 767 cannot be converted to a SHORT, and a negative number cannot be converted to a ULONG or USHORT.

PMERR_INVALID_PARAMETERS

PMERR_INVALID_PARM A parameter to the function contained invalid data.

PMERR_INVALID_PROGRAM_HANDLE An invalid program handle was specified.

PMERR_INVALID_SESSION_ID The specified session identifier is invalid.
                         Either zero (for the application`s own session)
                         or a valid identifier must be specified.

PMERR_INVALID_SRC_CODEPAGE The source code page parameter is invalid.

PMERR_INVALID_STRING_PARM The specified string parameter is invalid.

PMERR_INVALID_SWITCH_HANDLE An invalid Window List entry handle was specified.

PMERR_INVALID_TARGET_HANDLE An invalid target program-group handle was specified.

PMERR_INVALID_TITLE The specified program or group title is too long or contains invalid characters.

PMERR_INVALID_TYPE_FOR_LENGTH The data type for a control length is invalid.

PMERR_INVALID_TYPE_FOR_MPARAM The message parameter type for a control MPARAM is invalid, that is, not mparam1, mparam2 or mreply.

PMERR_INVALID_TYPE_FOR_OFFSET The data type for a control offset is invalid.

PMERR_INVALID_WINDOW The window specified with a Window List call is not a valid frame window.

PMERR_KERNING_NOT_SUPPORTED Kerning was requested on GpiCreateLogFont call to a presentation space associated with a device context that does not support kerning.

PMERR_LABEL_NOT_FOUND The specified element label did not exist.

PMERR_MATRIX_OVERFLOW An internal overflow error occurred during matrix multiplication. This can occur if coordinates or matrix transformation elements (or both) are invalid or too large.

PMERR_MEMORY_ALLOC An error occurred during memory management.

PMERR_MEMORY_ALLOCATION_ERR An error occurred during memory management.

PMERR_MEMORY_DEALLOCATION_ERR An error occurred during memory management.

PMERR_METAFILE_IN_USE An attempt has been made to access a metafile that is in use by another thread.

PMERR_METAFILE_INTERNAL_ERROR An internal inconsistency has been detected during metafile unlock processing.

PMERR_METAFILE_LIMIT_EXCEEDED The maximum permitted metafile size limit was exceeded during metafile recording.

PMERR_MSGID_TOO_SMALL The message identifier specified is too small.

PMERR_NEGATIVE_STRCOND_DIM A negative array dimension was passed for a data type length.

PMERR_NO_BITMAP_SELECTED An attempt has been made to operate on a memory device context that has no bit map selected.

PMERR_NO_CURRENT_ELEMENT An attempt has been made to issue GpiQueryElementType or GpiQueryElement while there is no currently open element.

PMERR_NO_CURRENT_SEG An attempt has been made to issue GpiQueryElementType or GpiQueryElement while there is no currently open segment.

PMERR_NO_FILL No flood fill occurred because either the starting point color was the same as the input color when a boundary fill was requested, or the starting point color was not the same as the input color when a surface fill was requested.

PMERR_NO_METAFILE_RECORD_HANDLE The metafile record handle was not found during metafile recording, or DevEscape (DEVESC_STARTDOC) was not issued when drawing to a OD_QUEUED device context with a pszDataType field of PM_Q_STD.

PMERR_NO_MSG_QUEUE

PMERR_NO_PALETTE_SELECTED An attempt to realize a palette failed because no palette was previously selected into the Presentation Space.

PMERR_NO_SPACE The limit on the number of Window List entries has been reached with WinAddSwitchEntry.

PMERR_NOT_CREATED_BY_DEVOPENDC An attempt has been made to destroy a device context using DevCloseDC that was not created using DevOpenDC.

PMERR_NOT_CURRENT_PL_VERSION An unexpected data format was found in the initialization file.

PMERR_NOT_DRAGGING A drag operation is not in progress at this time.

PMERR_NOT_IN_A_PM_SESSION An attempt was made to access function that is only available from PM programs from a non-PM session.

PMERR_NOT_IN_AREA An attempt was made to end an area using GpiEndArea or during segment drawing while not in an area bracket.

PMERR_NOT_IN_DRAW_MODE An attempt was made to issue GpiSavePS or GpiRestorePS while the drawing mode was not set to DM_DRAW.

PMERR_NOT_IN_ELEMENT An attempt was made to end an element using GpiEndElement or during segment drawing while not in an element bracket.

PMERR_NOT_IN_IDX The application name, key-name or program handle was not found.

PMERR_NOT_IN_IMAGE An attempt was made to end an image during segment drawing while not in an image bracket.

PMERR_NOT_IN_PATH An attempt was made to end a path using GpiEndPath or during segment drawing while not in a path bracket.

PMERR_NOT_IN_RETAIN_MODE An attempt was made to issue a segment editing element function that is invalid when the actual drawing mode is not set to retain.

PMERR_NOT_IN_SEG An attempt was made to end a segment using GpiCloseSegment while not in a segment bracket.

PMERR_NOT_SELF_DESCRIBING_DTYP A data type is not self-describing.

PMERR_OPENING_INI_FILE Unable to open initialization file (due to lack of disk space for example).

PMERR_ORDER_TOO_BIG An internal size limit was exceeded while converting orders from short to long format during GpiPutData processing. An order was too long to convert.

PMERR_OWN_SET_ID_REFS An attempt to unload a font failed because the setid is still being referenced.

PMERR_PALETTE_BUSY An attempt has been made to reset the owner of a palette when it was busy.

PMERR_PALETTE_SELECTED Color palette operations cannot be performed on a presentation space while a palette is selected.

PMERR_PARAMETER_OUT_OF_RANGE The value of a parameter was not within the defined valid range for that parameter.

PMERR_PATH_INCOMPLETE An attempt was made to open or close a segment either directly or during segment drawing, or to issue GpiAssociate while there is an open path bracket.

PMERR_PATH_LIMIT_EXCEEDED An internal size limit was exceeded during path or area processing.

PMERR_PATH_UNKNOWN An attempt was made to perform a path function on a path that did not exist.

PMERR_PEL_IS_CLIPPED An attempt was made to query a pel that had been clipped using GpiQueryPel.

PMERR_PEL_NOT_AVAILABLE An attempt was made to query a pel that did not exist in GpiQueryPel (for example, a memory device context with no selected bit map).

PMERR_PRINTER_DD_NOT_DEFINED The Presentation Manager device driver has not been defined.

PMERR_PRINTER_QUEUE_NOT_DEFINED The spooler queue for the printer has not been defined.

PMERR_PRN_ADDR_IN_USE A printer is already defined on the port.

PMERR_PRN_ADDR_NOT_DEFINED The printer port has not been defined.

PMERR_PRN_NAME_NOT_DEFINED The printer has not been defined.

PMERR_PROLOG_ERROR A prolog error was detected during drawing.  Segment prologs are used internally within retained segments and also appear in metafiles. This error can also arise from an End Prolog order that is outside a prolog.

PMERR_PS_BUSY An attempt was made to access the presentation space from more than one thread simultaneously.

PMERR_PS_IS_ASSOCIATED An attempt was made to destroy a presentation or associate a presentation space that is still associated with a device context.

PMERR_PS_NOT_ASSOCIATED An attempt was made to access a presentation space that is not associated with a device context.

PMERR_QUEUE_TOO_LARGE An attempt to create a message queue has failed because the value specified for the size of the message queue is too large.

PMERR_RASTER_FONT A request was made for the outline of a bit-map font.  Outlines can only be returned for vector font characters.

PMERR_REALIZE_NOT_SUPPORTED An attempt was made to create a realizable logical color table on a device driver that does not support this function.

PMERR_REGION_IS_CLIP_REGION An attempt was made to perform a region operation on a region that is selected as a clip region.

PMERR_RESOURCE_DEPLETION An internal resource depletion error has occurred.

PMERR_RESOURCE_NOT_FOUND The specified resource identity could not be found.

PMERR_SEG_AND_REFSEG_ARE_SAME The segid and refsegid specified with GpiSetSegmentPriority were the same.

PMERR_SEG_CALL_STACK_EMPTY A call stack empty condition was detected when attempting a pop function during GpiPop or segment drawing.

PMERR_SEG_CALL_STACK_FULL A call stack full condition was detected when attempting to call a segment using GpiCallSegmentMatrix, attempting to preserve an attribute, or during segment drawing.

PMERR_SEG_IS_CURRENT An attempt was made to issue GpiGetData to a segment that was currently open.

PMERR_SEG_NOT_CHAINED An attempt was made to issue GpiDrawFrom, GpiCorrelateFrom or GpiQuerySegmentPriority for a segment that was not chained.

PMERR_SEG_NOT_FOUND The specified segment identifier did not exist.

PMERR_SEG_OVFLOW The input PIF has more than 1000 called segments. This has overflowed an internal buffer.

PMERR_SEG_STORE_LIMIT_EXCEEDED The maximum permitted retained segment store size limit was exceeded.

PMERR_SETID_IN_USE An attempt was made to specify a setid that was already in use as the currently selected character, marker or pattern set.

PMERR_SETID_NOT_FOUND An attempt was made to delete a setid that did not exist.

PMERR_SMB_OVFLOW The input PIF has more than 100 symbol sets defined. This has overflowed an internal buffer.

PMERR_SOMDD_IS_ACTIVE The DSOM daemon is already active.

PMERR_SOMDD_NOT_STARTED The DSOM daemon failed to start.

PMERR_SOURCE_SAME_AS_TARGET The direct manipulation source and target process are the same.

PMERR_SPL_CANNOT_OPEN_FILE Unable to open the file.

PMERR_SPL_DD_NOT_FOUND The Presentation Manager device driver definition could not be found.

PMERR_SPL_DEVICE_ALREADY_EXISTS The device already exists.

PMERR_SPL_DEVICE_LIMIT_REACHED The limit on the number of devices has been reached.

PMERR_SPL_DEVICE_NOT_INSTALLED The device has not been installed.

PMERR_SPL_DRIVER_ERROR No Presentation Manager device driver supplied or found.

PMERR_SPL_DRIVER_NOT_INSTALLED The Presentation Manager device driver has not been installed.

PMERR_SPL_FILE_NOT_FOUND Unable to find the file.

PMERR_SPL_HARD_NETWORK_ERROR Hard network error.

PMERR_SPL_INI_FILE_ERROR Error accessing the initialization file.

PMERR_SPL_INV_DATATYPE The spool file data type is invalid.

PMERR_SPL_INV_DRIVER_DATATYPE The data type is invalid for the Presentation Manager device driver.

PMERR_SPL_INV_FORMS_CODE The forms code for the job is invalid.

PMERR_SPL_INV_HSPL The spooler handle is invalid.

PMERR_SPL_INV_JOB_ID The job id is invalid.

PMERR_SPL_INV_LENGTH_OR_COUNT The length or count is invalid.

PMERR_SPL_INV_PRIORITY The priority for the job is invalid.

PMERR_SPL_INV_PROCESSOR_DATTYPE The data type is invalid for the spooler queue processor.

PMERR_SPL_INV_QUEUE_NAME The spooler queue name is invalid.

PMERR_SPL_INV_TOKEN The token is invalid.

PMERR_SPL_JOB_NOT_PRINTING The print job is not printing.

PMERR_SPL_JOB_PRINTING The print job is already printing.

PMERR_SPL_MANY_QUEUES_ASSOC More than one queue has been associated with the printer.

PMERR_SPL_NO_CURRENT_FORMS_CODE There is no current forms code defined to the Presentation Manager device driver.

PMERR_SPL_NO_DATA No data supplied or found.

PMERR_SPL_NO_DEFAULT_QUEUE There is no default spooler queue for the printer.

PMERR_SPL_NO_DISK_SPACE There is not enough free disk space.

PMERR_SPL_NO_FREE_JOB_ID There is no free job id available.

PMERR_SPL_NO_MEMORY There is not enough free memory.

PMERR_SPL_NO_QUEUES_ASSOCIATED A queue has not been associated with the printer.

PMERR_SPL_NO_SUCH_LOG_ADDRESS The logical address does not exist (that is, it is not defined in the initialization file).

PMERR_SPL_NOT_AUTHORISED Not authorized to perform the operation.

PMERR_SPL_PRINT_ABORT The job has already been aborted.

PMERR_SPL_PRINTER_NOT_FOUND The printer definition could not be found.

PMERR_SPL_PROCESSOR_ERROR No spooler queue processor supplied or found.

PMERR_SPL_PROCESSOR_NOT_INST The spooler queue processor has not been installed.

PMERR_SPL_QUEUE_ALREADY_EXISTS The spooler queue already exists.

PMERR_SPL_QUEUE_ERROR No spooler queue supplied or found.

PMERR_SPL_QUEUE_NOT_EMPTY The spooler queue contains print jobs.

PMERR_SPL_QUEUE_NOT_FOUND The spooler queue definition could not be found.

PMERR_SPL_SPOOLER_NOT_INSTALLED The spooler is not installed.

PMERR_SPL_STATUS_STRING_TRUNC The print job status string has been truncated.

PMERR_SPL_TEMP_NETWORK_ERROR Temporary network error.

PMERR_SPL_TOO_MANY_OPEN_FILES Too many open files.

PMERR_SPOOLER_QP_NOT_DEFINED The spooler queue processor has not been defined.

PMERR_START_POINT_CLIPPED The starting point specified for flood fill is outside the current clipping path or region.

PMERR_STARTDOC_NOT_ISSUED A request to write spooled output without first issuing a STARTDOC was attempted.

PMERR_STARTED_IN_BACKGROUND The application started a new session in the background.

PMERR_STOP_DRAW_OCCURRED Segment drawing or GpiPlayMetaFile was stopped prematurely in response to a GpiSetStopDraw request.

PMERR_TOO_MANY_METAFILES_IN_USE The maximum number of metafiles allowed for a given process was exceeded.

PMERR_TRUNCATED_ORDER An incomplete order was detected during segment processing.

PMERR_UNABLE_TO_CLOSE_DEVICE Unable to close the print device (for example, powered off or offline).

PMERR_UNCHAINED_SEG_ZERO_INV An attempt was made to open segment with segment identifier zero and the ATTR_CHAINED segment attribute not specified.

PMERR_UNSUPPORTED_ATTR An unsupported attribute was specified in the attrmask with GpiSetAttrs or GpiQueryAttrs.

PMERR_UNSUPPORTED_ATTR_VALUE An attribute value was specified with GpiSetAttrs that is not supported.

PMERR_WINDOW_LOCK_OVERFLOW An overflow occurred for the use count of a window.

PMERR_WINDOW_LOCK_UNDERFLOW An attempt was made to decrement the use count of a window below zero.

PMERR_WINDOW_NOT_LOCKED The window specified in WinSendMsg was not locked.

PMERR_WPDSERVER_IS_ACTIVE The Workplace Shell DSOM Server is already active.

PMERR_WPDSERVER_NOT_STARTED The Workplace Shell DSOM Server could not be started.

WPERR_INVALID_FLAGS An invalid flag was specified.

WPERR_INVALID_OBJECTID An invalid object ID was specified.

WPERR_INVALID_TARGET_OBJECT An invalid target object was specified.

#endif
   //POKA_FREEPM_ERR

#ifdef __cplusplus
      }
#endif

#endif
  //FREEPM_ERR_H
