#
# (c) osFree project,
#

PROJ = test05
DESC = test application
#defines object file names in format objname.$(O)
srcfiles = $(p)test05$(e)
# defines additional options for C compiler
ADD_COPT    = -i=$(MYDIR)..$(SEP)include
STUB=$(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)os2stub.exe

!include $(%ROOT)/mk/appsos2.mk
