#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

srcfiles = $(p)habmgr$(e)
ADD_COPT = -i=$(MYDIR).. -bd
DEST = none

!include $(%ROOT)/mk/appsos2_fpm.mk

TARGETS = $(OBJS)
