#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

srcfiles = $(p)habmgr$(e)
ADD_COPT = -i=$(MYDIR)..$(SEP)include -bd
DEST = none

!include $(%ROOT)/mk/appsos2.mk

TARGETS = $(OBJS)
