#
# A Makefile for MSGBIND
# (c) osFree project,
# author, date
#

PROJ = msgbind
TRGT = $(PROJ).exe
DESC = Message binder
#defines object file names in format $(p)objname$(e)
srcfiles = $(p)loader$(e)
# defines additional options for C compiler

!include $(%ROOT)tools/mk/tools.mk
