 
DEST = os2tk45$(SEP)som$(SEP)include

!include $(%ROOT)SOM/common.mk


TARGETS =       $(PATH)somobj.h &
                $(PATH)somcls.h &
                $(PATH)somcm.h &
                $(PATH)attribdf.h &
                $(PATH)constdef.h &
                $(PATH)containd.h &
                $(PATH)containr.h &
                $(PATH)excptdef.h &
                $(PATH)intfacdf.h &
                $(PATH)moduledf.h &
                $(PATH)operatdf.h &
                $(PATH)paramdef.h &
                $(PATH)repostry.h &
                $(PATH)typedef.h &
                $(PATH)boa.h &
                $(PATH)cntxt.h &
                $(PATH)impldef.h &
                $(PATH)implrep.h &
                $(PATH)nvlist.h &
                $(PATH)om.h &
                $(PATH)orb.h &
                $(PATH)poa.h &
                $(PATH)principl.h &
                $(PATH)request.h &
                $(PATH)rhborbst.h &
                $(PATH)rhbtypes.h &
                $(PATH)servmgr.h &
                $(PATH)servreq.h &
                $(PATH)somdcprx.h &
                $(PATH)somdfenc.h &
                $(PATH)somdmprx.h &
                $(PATH)somdobj.h &
                $(PATH)somdom.h &
                $(PATH)somdserv.h &
                $(PATH)somdstub.h &
                $(PATH)somdtcdt.h &
                $(PATH)somdtype.h &
                $(PATH)somoa.h &
                $(PATH)stexcep.h &
                $(PATH)unotypes.h &
                $(PATH)clientev.h &
                $(PATH)eman.h &
                $(PATH)emregdat.h &
                $(PATH)event.h &
                $(PATH)sinkev.h &
                $(PATH)timerev.h &
                $(PATH)workprev.h &
                $(PATH)defedidl.h &
                $(PATH)eda.h &
                $(PATH)fma.h &
                $(PATH)fmi.h &
                $(PATH)fmib.h &
                $(PATH)fsagm.h &
                $(PATH)fsgm.h &
                $(PATH)iogma.h &
                $(PATH)iogrp.h &
                $(PATH)mia.h &
                $(PATH)nsma.h &
                $(PATH)objset.h &
                $(PATH)pid.h &
                $(PATH)po.h &
                $(PATH)poid.h &
                $(PATH)poida.h &
                $(PATH)psma.h &
                $(PATH)somp.h &
                $(PATH)somperr.h &
                $(PATH)somperrd.h &
                $(PATH)sompstad.h &
                $(PATH)sompstat.h &
                $(PATH)srkset.h &
                $(PATH)snglicls.h &
                $(PATH)sombacls.h &
                $(PATH)somida.h &
                $(PATH)somproxy.h &
                $(PATH)somsid.h &
                $(PATH)scattrib.h &
                $(PATH)scbase.h &
                $(PATH)scclass.h &
                $(PATH)sccommon.h &
                $(PATH)scconst.h &
                $(PATH)scdata.h &
                $(PATH)scemit.h &
                $(PATH)scentry.h &
                $(PATH)scenum.h &
                $(PATH)scenumnm.h &
                $(PATH)scmeta.h &
                $(PATH)scmethod.h &
                $(PATH)scmodule.h &
                $(PATH)scparm.h &
                $(PATH)scpass.h &
                $(PATH)scseqnce.h &
                $(PATH)scstring.h &
                $(PATH)scstruct.h &
                $(PATH)sctdef.h &
                $(PATH)sctmplt.h &
                $(PATH)scunion.h &
                $(PATH)scusrtyp.h &
                $(PATH)somstrt.h &
                $(PATH)somssock.h &
                $(PATH)tcpsock.h &
                $(PATH)omgestio.h &
                $(PATH)somestio.h &
                $(PATH)biter.h &
                $(PATH)lname.h &
                $(PATH)lnamec.h &
                $(PATH)naming.h &
                $(PATH)xnaming.h &
                $(PATH)xnamingf.h &
                $(PATH)omgidobj.h &
                $(PATH)somref.h &
                $(PATH)somap.h &
                $(PATH)somos.h &
                $(PATH)xmscssae.h &
                $(PATH)somtdm.h &
                $(PATH)somcls.api &
                $(PATH)mlink.h &
                $(PATH)tpll.h &
                $(PATH)tpllitr.h


$(PATH)attribdf.h: $(DEST)$(SEP)attribdf.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)constdef.h: $(DEST)$(SEP)constdef.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)containd.h: $(DEST)$(SEP)containd.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)containr.h: $(DEST)$(SEP)containr.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)excptdef.h: $(DEST)$(SEP)excptdef.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)intfacdf.h: $(DEST)$(SEP)intfacdf.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)moduledf.h: $(DEST)$(SEP)moduledf.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)operatdf.h: $(DEST)$(SEP)operatdf.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)paramdef.h: $(DEST)$(SEP)paramdef.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)repostry.h: $(DEST)$(SEP)repostry.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)typedef.h: $(DEST)$(SEP)typedef.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)boa.h: $(DEST)$(SEP)boa.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)cntxt.h: $(DEST)$(SEP)cntxt.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)impldef.h: $(DEST)$(SEP)impldef.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)implrep.h: $(DEST)$(SEP)implrep.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)nvlist.h: $(DEST)$(SEP)nvlist.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)om.h: $(DEST)$(SEP)om.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)orb.h: $(DEST)$(SEP)orb.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)poa.h: $(DEST)$(SEP)poa.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)principl.h: $(DEST)$(SEP)principl.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)request.h: $(DEST)$(SEP)request.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)rhborbst.h: $(DEST)$(SEP)rhborbst.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)rhbtypes.h: $(DEST)$(SEP)rhbtypes.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)servmgr.h: $(DEST)$(SEP)servmgr.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)servreq.h: $(DEST)$(SEP)servreq.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdcprx.h: $(DEST)$(SEP)somdcprx.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdfenc.h: $(DEST)$(SEP)somdfenc.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdmprx.h: $(DEST)$(SEP)somdmprx.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdobj.h: $(DEST)$(SEP)somdobj.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdom.h: $(DEST)$(SEP)somdom.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdserv.h: $(DEST)$(SEP)somdserv.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdstub.h: $(DEST)$(SEP)somdstub.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdtcdt.h: $(DEST)$(SEP)somdtcdt.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdtype.h: $(DEST)$(SEP)somdtype.idl
 $(verbose)$(SC) -DEMIT_SOMDTYPES -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somoa.h: $(DEST)$(SEP)somoa.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)stexcep.h: $(DEST)$(SEP)stexcep.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)unotypes.h: $(DEST)$(SEP)unotypes.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)clientev.h: $(DEST)$(SEP)clientev.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)eman.h: $(DEST)$(SEP)eman.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)emregdat.h: $(DEST)$(SEP)emregdat.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)event.h: $(DEST)$(SEP)event.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sinkev.h: $(DEST)$(SEP)sinkev.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)timerev.h: $(DEST)$(SEP)timerev.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)workprev.h: $(DEST)$(SEP)workprev.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)defedidl.h: $(DEST)$(SEP)defedidl.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)eda.h: $(DEST)$(SEP)eda.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fma.h: $(DEST)$(SEP)fma.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fmi.h: $(DEST)$(SEP)fmi.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fmib.h: $(DEST)$(SEP)fmib.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fsagm.h: $(DEST)$(SEP)fsagm.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fsgm.h: $(DEST)$(SEP)fsgm.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)iogma.h: $(DEST)$(SEP)iogma.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)iogrp.h: $(DEST)$(SEP)iogrp.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)mia.h: $(DEST)$(SEP)mia.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)nsma.h: $(DEST)$(SEP)nsma.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)objset.h: $(DEST)$(SEP)objset.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)pid.h: $(DEST)$(SEP)pid.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)po.h: $(DEST)$(SEP)po.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)poid.h: $(DEST)$(SEP)poid.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)poida.h: $(DEST)$(SEP)poida.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)psma.h: $(DEST)$(SEP)psma.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somp.h: $(DEST)$(SEP)somp.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somperr.h: $(DEST)$(SEP)somperr.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somperrd.h: $(DEST)$(SEP)somperrd.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sompstad.h: $(DEST)$(SEP)sompstad.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sompstat.h: $(DEST)$(SEP)sompstat.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)srkset.h: $(DEST)$(SEP)srkset.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)snglicls.h: $(DEST)$(SEP)snglicls.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sombacls.h: $(DEST)$(SEP)sombacls.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somida.h: $(DEST)$(SEP)somida.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somproxy.h: $(DEST)$(SEP)somproxy.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somsid.h: $(DEST)$(SEP)somsid.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scattrib.h: $(DEST)$(SEP)scattrib.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scbase.h: $(DEST)$(SEP)scbase.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scclass.h: $(DEST)$(SEP)scclass.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sccommon.h: $(DEST)$(SEP)sccommon.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scconst.h: $(DEST)$(SEP)scconst.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scdata.h: $(DEST)$(SEP)scdata.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scemit.h: $(DEST)$(SEP)scemit.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scentry.h: $(DEST)$(SEP)scentry.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scenum.h: $(DEST)$(SEP)scenum.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scenumnm.h: $(DEST)$(SEP)scenumnm.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scmeta.h: $(DEST)$(SEP)scmeta.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scmethod.h: $(DEST)$(SEP)scmethod.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scmodule.h: $(DEST)$(SEP)scmodule.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scparm.h: $(DEST)$(SEP)scparm.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scpass.h: $(DEST)$(SEP)scpass.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scseqnce.h: $(DEST)$(SEP)scseqnce.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scstring.h: $(DEST)$(SEP)scstring.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scstruct.h: $(DEST)$(SEP)scstruct.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sctdef.h: $(DEST)$(SEP)sctdef.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sctmplt.h: $(DEST)$(SEP)sctmplt.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scunion.h: $(DEST)$(SEP)scunion.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scusrtyp.h: $(DEST)$(SEP)scusrtyp.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somstrt.h: $(DEST)$(SEP)somstrt.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somssock.h: $(DEST)$(SEP)somssock.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)tcpsock.h: $(DEST)$(SEP)tcpsock.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)omgestio.h: $(DEST)$(SEP)omgestio.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somestio.h: $(DEST)$(SEP)somestio.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)biter.h: $(DEST)$(SEP)biter.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)lname.h: $(DEST)$(SEP)lname.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)lnamec.h: $(DEST)$(SEP)lnamec.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)naming.h: $(DEST)$(SEP)naming.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)xnaming.h: $(DEST)$(SEP)xnaming.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)xnamingf.h: $(DEST)$(SEP)xnamingf.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)omgidobj.h: $(DEST)$(SEP)omgidobj.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)corba.h: $(DEST)$(SEP)corba.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somref.h: $(DEST)$(SEP)somref.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somap.h: $(DEST)$(SEP)somap.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somos.h: $(DEST)$(SEP)somos.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)xmscssae.h: $(DEST)$(SEP)xmscssae.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somtdm.h: $(DEST)$(SEP)somtdm.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somobj.h: $(DEST)$(SEP)somobj.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somcls.h: $(DEST)$(SEP)somcls.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somcm.h: $(DEST)$(SEP)somcm.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somcls.api: $(DEST)$(SEP)somcls.idl
 $(verbose)$(SC) -sapi -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)mlink.h: $(DEST)$(SEP)mlink.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)tpll.h: $(DEST)$(SEP)tpll.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)tpllitr.h: $(DEST)$(SEP)tpllitr.idl
 $(verbose)$(SC) -sh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)
