/* STLSUP.H  */

/*+--------------------------------------------------------------------------+*/
/*| Menu item identifiers.                                                   |*/
/*+--------------------------------------------------------------------------+*/
#define MYM_ENDTHREAD        (WM_USER+1)
#define MYM_SHOWMESSAGE      (WM_USER+2)
#define MYM_FAST_WMPAINT     (WM_USER+3)

#define IDM_EXIT             257
#define IDM_EXITPROG         258
#define IDM_DEMO             259
#define IDD_HELP             260
#define IDM_HELP             261
#define IDM_HELPABOUT        263

/* About Dialog */
#define DID_VERSION          264



#define IDM_FILE            1000
  #define IDM_FILEOPEN        1001


#define ID_NULL              9999
#define ID_WINDOW            256
#define ID_WINDOW_CHECK      257

/*+--------------------------------------------------------------------------+*/
/*| String identifiers.                                                      |*/
/*+--------------------------------------------------------------------------+*/

#define IDS_APPNAME          10
#define IDS_NOREGISTER       11
#define IDS_NOSTDWINDOWS     12
#define IDS_NOTHREAD         13
#define IDS_SEMERROR         14

