
SRC = $(MYDIR)
OS2TK = $(%OS2TK)
DEST = none

SOM_DIR=$(SRC)
SOMIDL_IDL=$(OS2TK)$(SEP)som$(SEP)include
SOMIDL_HEADERS=$(SOMIDL_IDL)

SOM_IDL=$(SOM_DIR)$(SEP)scattrib.idl &
		$(SOM_DIR)$(SEP)scbase.idl &
		$(SOM_DIR)$(SEP)scclass.idl &
		$(SOM_DIR)$(SEP)sccommon.idl &
		$(SOM_DIR)$(SEP)scconst.idl &
		$(SOM_DIR)$(SEP)scdata.idl &
		$(SOM_DIR)$(SEP)scemit.idl &
		$(SOM_DIR)$(SEP)scentry.idl &
		$(SOM_DIR)$(SEP)scenum.idl &
		$(SOM_DIR)$(SEP)scenumnm.idl &
		$(SOM_DIR)$(SEP)scmeta.idl &
		$(SOM_DIR)$(SEP)scmethod.idl &
		$(SOM_DIR)$(SEP)scmodule.idl &
		$(SOM_DIR)$(SEP)scparm.idl &
		$(SOM_DIR)$(SEP)scpass.idl &
		$(SOM_DIR)$(SEP)scseqnce.idl &
		$(SOM_DIR)$(SEP)scstring.idl &
		$(SOM_DIR)$(SEP)scstruct.idl &
		$(SOM_DIR)$(SEP)sctdef.idl &
		$(SOM_DIR)$(SEP)sctmplt.idl &
		$(SOM_DIR)$(SEP)scunion.idl &
		$(SOM_DIR)$(SEP)scusrtyp.idl &
		$(SOM_DIR)$(SEP)sctypes2.idl &
		$(SOM_DIR)$(SEP)somstrt.idl

PRODUCTS_SC= &
			$(SOMIDL_HEADERS)$(SEP)sctypes2.h &
			$(SOMIDL_HEADERS)$(SEP)sctypes2.xh &
			$(SOMIDL_HEADERS)$(SEP)scattrib.h &
			$(SOMIDL_HEADERS)$(SEP)scattrib.xh &
			$(SOMIDL_HEADERS)$(SEP)scbase.h &
			$(SOMIDL_HEADERS)$(SEP)scbase.xh &
			$(SOMIDL_HEADERS)$(SEP)scclass.h &
			$(SOMIDL_HEADERS)$(SEP)scclass.xh &
			$(SOMIDL_HEADERS)$(SEP)sccommon.h &
			$(SOMIDL_HEADERS)$(SEP)sccommon.xh &
			$(SOMIDL_HEADERS)$(SEP)scconst.h &
			$(SOMIDL_HEADERS)$(SEP)scconst.xh &
			$(SOMIDL_HEADERS)$(SEP)scdata.h &
			$(SOMIDL_HEADERS)$(SEP)scdata.xh &
			$(SOMIDL_HEADERS)$(SEP)scemit.h &
			$(SOMIDL_HEADERS)$(SEP)scemit.xh &
			$(SOMIDL_HEADERS)$(SEP)scentry.h &
			$(SOMIDL_HEADERS)$(SEP)scentry.xh &
			$(SOMIDL_HEADERS)$(SEP)scenum.h &
			$(SOMIDL_HEADERS)$(SEP)scenum.xh &
			$(SOMIDL_HEADERS)$(SEP)scenumnm.h &
			$(SOMIDL_HEADERS)$(SEP)scenumnm.xh &
			$(SOMIDL_HEADERS)$(SEP)scmeta.h &
			$(SOMIDL_HEADERS)$(SEP)scmeta.xh &
			$(SOMIDL_HEADERS)$(SEP)scmethod.h &
			$(SOMIDL_HEADERS)$(SEP)scmethod.xh &
			$(SOMIDL_HEADERS)$(SEP)scmodule.h &
			$(SOMIDL_HEADERS)$(SEP)scmodule.xh &
			$(SOMIDL_HEADERS)$(SEP)scparm.h &
			$(SOMIDL_HEADERS)$(SEP)scparm.xh &
			$(SOMIDL_HEADERS)$(SEP)scpass.h &
			$(SOMIDL_HEADERS)$(SEP)scpass.xh &
			$(SOMIDL_HEADERS)$(SEP)scseqnce.h &
			$(SOMIDL_HEADERS)$(SEP)scseqnce.xh &
			$(SOMIDL_HEADERS)$(SEP)scstring.h &
			$(SOMIDL_HEADERS)$(SEP)scstring.xh &
			$(SOMIDL_HEADERS)$(SEP)scstruct.h &
			$(SOMIDL_HEADERS)$(SEP)scstruct.xh &
			$(SOMIDL_HEADERS)$(SEP)sctdef.h &
			$(SOMIDL_HEADERS)$(SEP)sctdef.xh &
			$(SOMIDL_HEADERS)$(SEP)sctmplt.h &
			$(SOMIDL_HEADERS)$(SEP)sctmplt.xh &
			$(SOMIDL_HEADERS)$(SEP)scunion.h &
			$(SOMIDL_HEADERS)$(SEP)scunion.xh &
			$(SOMIDL_HEADERS)$(SEP)scusrtyp.h &
			$(SOMIDL_HEADERS)$(SEP)scusrtyp.xh &
			$(SOMIDL_HEADERS)$(SEP)somstrt.h &
			$(SOMIDL_HEADERS)$(SEP)somstrt.xh

PRODUCTS_PDL=$(SOMIDL_IDL)$(SEP)scattrib.idl &
			$(SOMIDL_IDL)$(SEP)scbase.idl &
			$(SOMIDL_IDL)$(SEP)scclass.idl &
			$(SOMIDL_IDL)$(SEP)sccommon.idl &
			$(SOMIDL_IDL)$(SEP)scconst.idl &
			$(SOMIDL_IDL)$(SEP)scdata.idl &
			$(SOMIDL_IDL)$(SEP)scemit.idl &
			$(SOMIDL_IDL)$(SEP)scentry.idl &
			$(SOMIDL_IDL)$(SEP)scenum.idl &
			$(SOMIDL_IDL)$(SEP)scenumnm.idl &
			$(SOMIDL_IDL)$(SEP)scmeta.idl &
			$(SOMIDL_IDL)$(SEP)scmethod.idl &
			$(SOMIDL_IDL)$(SEP)scmodule.idl &
			$(SOMIDL_IDL)$(SEP)scparm.idl &
			$(SOMIDL_IDL)$(SEP)scpass.idl &
			$(SOMIDL_IDL)$(SEP)scseqnce.idl &
			$(SOMIDL_IDL)$(SEP)scstring.idl &
			$(SOMIDL_IDL)$(SEP)scstruct.idl &
			$(SOMIDL_IDL)$(SEP)sctdef.idl &
			$(SOMIDL_IDL)$(SEP)sctmplt.idl &
			$(SOMIDL_IDL)$(SEP)scunion.idl &
			$(SOMIDL_IDL)$(SEP)sctypes2.idl &
			$(SOMIDL_IDL)$(SEP)scusrtyp.idl &
			$(SOMIDL_IDL)$(SEP)somstrt.idl

ADD_SCOPT = -I$(SOMIDL_IDL) 

!include $(%ROOT)tools/mk/all.mk

TARGETS= $(SOMIDL_HEADERS)$(SEP)sctypes.h $(SOMIDL_HEADERS)$(SEP)sctypes.xh $(PRIVATE_HEADERS) $(PRODUCTS_PDL) $(PRODUCTS_SC) 

$(PRODUCTS_SC): $(SOM_IDL)

$(PRODUCTS_PDL): $(SOM_IDL)
 @$(SAY) PDL      $^. $(LOG)
 @$(MDHIER) $(SOMIDL_IDL)
 @$(MDHIER) $(SOMIDL_HEADERS)
 @pdl.exe -d $(SOMIDL_IDL) $<

$(SOMIDL_HEADERS)$(SEP)sctypes.h: $(SOM_DIR)$(SEP)sctypes.h
 $(verbose)$(CP) $< $^@ $(BLACKHOLE)

$(SOMIDL_HEADERS)$(SEP)sctypes.xh: $(SOM_DIR)$(SEP)sctypes.xh
 $(verbose)$(CP) $< $^@ $(BLACKHOLE)



.idl: $(SOM_DIR)

