/**************************************************************************
 *
 *  Copyright 2015, 2017, 2018, Yuri Prokushev
 *
 *  This file is part of osFree project
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */


#ifndef scpass_idl
#define scpass_idl

#include <scentry.idl>
interface SOMTPassthruEntryC : SOMTEntryC
{
  readonly attribute string somtPassthruBody;
  // The source content text of this passthru entry without
  // any modification. Newlines that were present in the source will
  // still be present.

  readonly attribute string somtPassthruLanguage;
  // Returns the name of the language for which this passthru entry
  // is intended. Language names are always all upper case.

  readonly attribute string somtPassthruTarget;
  // Returns the target for this passthru entry.

  boolean somtIsBeforePassthru();
  // Returns 1 (true) if this passthru entry is to be put at the
  // beginning of the file or 0 (false) if this passthru entry is to
  // go later in the file.

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_somtPassthruBody,_get_somtPassthruTarget,
		_get_somtPassthruLanguage, somtIsBeforePassthru;
  
    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = scpass;
    dllname = "some.dll";
    callstyle = oidl;
  
    //# Method Modifiers
    //somtSetSymbolsOnEntry: override;
    //somDumpSelfInt: override;
  
    //# Attribute Modifiers
    somtPassthruTarget: nodata;
    somtPassthruLanguage: nodata;
    somtPassthruBody: nodata;
  };
#endif /* __SOMIDL__ */
};


#endif  /* scpass_idl */
