#
#
#

#DIRS    =
PROJ    = exh
TRGT    = $(PROJ).msg
DEST    = os2$(SEP)system

!include $(%ROOT)tools/mk/appsos2.mk

TARGETS = $(PATH)exh.msg 

$(PATH)exh.msg:

#$(PATH)exh.rsf: .always
# @$(MAKE) $(MAKEOPT) T=$^. rsf
