#
# A Makefile for LOGO.LGO
# (c) osFree project,
# author, date
#

PROJ       = logo
TRGT       = $(PROJ).bin
DESC       = Windows Boot Logo screen
srcfiles   = $(p)logo$(e)
JWASM      = 1
COM        = 1

!include $(%ROOT)/mk/appsdos.mk

