#
# A main Makefile for OS/3 boot sequence project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = rexxtry pmrexx rxqueue

!include $(%ROOT)/mk/all.mk

#TARGETS = subdirs
#TARGET = all
