PKGDIR  ?= ../../..
REP_DIR ?= $(PKGDIR)/../../..

include $(REP_DIR)/mk/osfree.mk

# the name of your library
TARGET	= libos2server.a

# list your .c files here
SRC_C	=

# if your library implements the client side of an idl defined in an
# idl-file of your package, list the idl file name(s) here (no path needed)
CLIENTIDL = os2server.idl

include $(L4DIR)/mk/lib.mk
