/* -*- c -*- */ 
import <l4/sys/types.h>
import <l4/l4vfs/types.h>

import <l4/l4vfs/common_io_notify.idl>
import <l4/l4vfs/object_server.idl>
import <l4/l4vfs/select_notify.idl>

library l4vfs_term_server
{
    /* This interface describes the functions provided
     * by the term server for internal use only.
     */
    [uuid(64)]
    interface main : l4vfs::object_server,
	                 l4vfs::common_io_notify,
					 l4vfs::select_notify
    {
    };
};
