#
# A Makefile for ANSI
# (c) osFree project,
# author, date
#

PROJ = somipc
DESC = SOM Compiler IPC
#defines object file names in format objname.$(O)
srcfiles = $(p)somipc$(e)
# defines additional options for C compiler
ADD_COPT    = -i=$(%ROOT)$(SEP)tools$(SEP)include -sg
ADD_LINKOPT = lib libidl

!include $(%ROOT)/mk/tools.mk
