# $Id: makefile,v 1.3 2004/08/16 04:51:12 prokushev Exp $

PROJ = keystack
DESC = KEYSTACK.EXE
srcfiles = $(p)keystack$(e)
ADD_COPT = -i=$(MYDIR)..$(SEP)include -ox
STUB        = $(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)os2stub.exe

!include $(%ROOT)/mk/appsos2.mk
