DESCRIPTION = SDPX SBOM generator

ADD_COPT = -i=..$(SEP)include
ADD_LINKOPT = lib reuse_parser.lib, spdx.lib, sha1.lib, omf.lib, res.lib, json.lib, git.lib, dep5.lib

!include $(%ROOT)tools/mk/build.mk
