#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

#srcfiles = $(p)errors$(e) $(p)f_errors$(e)
ADD_COPT = -i=$(MYDIR)..$(SEP)include

!include $(%ROOT)/mk/appsos2_fpm.mk

#DEST = none
TARGETS = $(OBJS)
TARGET = all
