#####################################################################
#
#  makefile for ctrldemo 
#
#  Copyright (c) 1995, Willows Software Inc.  All rights reserved.
#
#####################################################################

include $(TWINDIR)/Makefile.config

project		= ctrldemo
components	= ctrldemo.o proppage.o ctrldemo.res.o
linklibs	= -lcommctrl32 -lshell32
resource	= ctrldemo
resource_depend	= willows.ico toolbar.bmp

include $(TWINDIR)/makeinclude/makefile32.inc

#####################################################################
# user makefile definitions for libraries are placed below
#####################################################################

clean-libs:
