#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS =   attrib    &
         help      &
         find      &
         diskcomp  &
         label     &
         mem       &
         xcopy     &
         basic     &
         more      &
         subst     &
         stub      &
         command

!include $(%ROOT)/mk/all.mk

TARGETS=subdirs
TARGET=all
