/**************************************************************************
 *
 *  Copyright 2015, 2017, 2018, Yuri Prokushev
 *
 *  This file is part of osFree project
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */


#ifndef scdata_idl
#define scdata_idl

#include <sccommon.idl>
interface SOMTDataEntryC : SOMTCommonEntryC
{
  readonly attribute boolean somtIsSelfRef;
  // Whether a declarator of a struct is self-referential.

#ifdef __SOMIDL__

  implementation {

    releaseorder: _get_somtIsSelfRef;

    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = scdata;
#ifdef _WIN32
    dllname = "some.dll";
#endif
    callstyle = oidl;
  
    //# Method Modifiers
    //somtSetSymbolsOnEntry: override;
    //somDumpSelfInt: override;
  
    //# attribute modifiers
    somtIsSelfRef: nodata;
  };
#endif /* __SOMIDL__ */
};


#endif  /* scdata_idl */
