/**************************************************************************
 *
 *  Copyright 2015, 2017, 2018, Yuri Prokushev
 *
 *  This file is part of osFree project
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

#ifndef scstruct_idl
#define scstruct_idl

#include <scentry.idl>

interface SOMTTypedefEntryC;
interface SOMTClassEntryC;

interface SOMTStructEntryC : SOMTEntryC
{
  SOMTTypedefEntryC somtGetFirstMember();
  // The first member of the struct.
  SOMTTypedefEntryC somtGetNextMember();
  // The next member of the struct, relative to the previous call
  // to this method or somtGetFirstMember.

  readonly attribute SOMTClassEntryC somtStructClass;
  // The class in which the structure was defined.

  readonly attribute boolean somtIsException;
  // Whether the structure is really an exception.
#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_somtStructClass, _get_somtIsException,
		somtGetFirstMember, somtGetNextMember;
  
    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = scstruct;
    dllname = "some.dll";
    callstyle = oidl;
  
    //# Method Modifiers
    //somDumpSelfInt: override;
    //somtSetSymbolsOnEntry: override;
  
    //# Attribute Modifiers
    somtIsException: nodata;
    somtStructClass: nodata;

  };
#endif /* __SOMIDL__ */
};


#endif  /* scstruct_idl */
