/**************************************************************************
 *
 *  Copyright 2015, 2017, 2018, Yuri Prokushev
 *
 *  This file is part of osFree project
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */


#ifndef scusrtyp_idl
#define scusrtyp_idl

#include <sccommon.idl>
interface SOMTUserDefinedTypeEntryC : SOMTCommonEntryC
{

  readonly attribute SOMTTypedefEntryC somtOriginalTypedef;
  // The typedef that defined the user-defined type.

  readonly attribute SOMTEntryC somtBaseTypeObj;
  // The object representing the base type 
  // (eg. short, float, unsigned long) of a user-defined type, 
  // skipping over any intermediate user-defined types.

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_somtOriginalTypedef, _get_somtBaseTypeObj;
  
    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = scusrtyp;
#ifdef _WIN32
    dllname = "some.dll";
#endif
    callstyle = oidl;
  
    //# Method Modifiers
    somtSetSymbolsOnEntry: override;
    somDumpSelfInt: override;
    _get_somtTypeObj: override;
  
    //# attribute modifiers
    somtOriginalTypedef: nodata;
    somtBaseTypeObj: nodata;
  };
#endif /* __SOMIDL__ */
};


#endif  /* scusrtyp_idl */
