#
# A Makefile for RXQUEUE
# (c) osFree project,
# author, date
#

PROJ = rxqueue
DESC = REXX queue tool
srcfiles = $(p)rxqueue$(e)
UNI2H=1
IMPORTS      = RexxAddQueue     REXXAPI.3, &
    	       RexxPullQueue    REXXAPI.4, &
    	       RexxQueryQueue   REXXAPI.5

!include $(%ROOT)tools/mk/appsos2_cmd.mk
