/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#ifdef __CRTRSXNT__
#include <crtrsxnt.h>
#endif
#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define __IDL_const const
#else
#define __IDL_const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN __IDL__start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((__IDL__start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE __IDL_restart( __IDL_in )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct __IDL__buffer_state *YY_BUFFER_STATE;

extern int __IDL_leng;
extern FILE *__IDL_in, *__IDL_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		__IDL_less( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the __IDL_less() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define __IDL_less(n) \
	do \
		{ \
		/* Undo effects of setting up __IDL_text. */ \
		*__IDL__cp = __IDL__hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		__IDL__c_buf_p = __IDL__cp = __IDL__bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up __IDL_text again */ \
		} \
	while ( 0 )

#define unput(c) __IDL_unput( c, __IDL_text_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int __IDL__size_t;


struct __IDL__buffer_state
	{
	FILE *__IDL__input_file;

	char *__IDL__ch_buf;		/* input buffer */
	char *__IDL__buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	__IDL__size_t __IDL__buf_size;

	/* Number of characters read into __IDL__ch_buf, not including EOB
	 * characters.
	 */
	int __IDL__n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int __IDL__is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int __IDL__is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int __IDL__at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int __IDL__fill_buffer;

	int __IDL__buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via __IDL_restart()), so that the user can continue scanning by
	 * just pointing __IDL_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE __IDL__current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER __IDL__current_buffer


/* __IDL__hold_char holds the character lost when __IDL_text is formed. */
static char __IDL__hold_char;

static int __IDL__n_chars;		/* number of characters read into __IDL__ch_buf */


int __IDL_leng;

/* Points to current character in buffer. */
static char *__IDL__c_buf_p = (char *) 0;
static int __IDL__init = 1;		/* whether we need to initialize */
static int __IDL__start = 0;	/* start state number */

/* Flag which is used to allow __IDL_wrap()'s to do buffer switches
 * instead of setting up a fresh __IDL_in.  A bit of a hack ...
 */
static int __IDL__did_buffer_switch_on_eof;

void __IDL_restart YY_PROTO(( FILE *input_file ));

void __IDL__switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void __IDL__load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE __IDL__create_buffer YY_PROTO(( FILE *file, int size ));
void __IDL__delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void __IDL__init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void __IDL__flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER __IDL__flush_buffer( __IDL__current_buffer )

YY_BUFFER_STATE __IDL__scan_buffer YY_PROTO(( char *base, __IDL__size_t size ));
YY_BUFFER_STATE __IDL__scan_string YY_PROTO(( __IDL_const char *__IDL__str ));
YY_BUFFER_STATE __IDL__scan_bytes YY_PROTO(( __IDL_const char *bytes, int len ));

static void *__IDL__flex_alloc YY_PROTO(( __IDL__size_t ));
static void *__IDL__flex_realloc YY_PROTO(( void *, __IDL__size_t ));
static void __IDL__flex_free YY_PROTO(( void * ));

#define __IDL__new_buffer __IDL__create_buffer

#define __IDL__set_interactive(is_interactive) \
	{ \
	if ( ! __IDL__current_buffer ) \
		__IDL__current_buffer = __IDL__create_buffer( __IDL_in, YY_BUF_SIZE ); \
	__IDL__current_buffer->__IDL__is_interactive = is_interactive; \
	}

#define __IDL__set_bol(at_bol) \
	{ \
	if ( ! __IDL__current_buffer ) \
		__IDL__current_buffer = __IDL__create_buffer( __IDL_in, YY_BUF_SIZE ); \
	__IDL__current_buffer->__IDL__at_bol = at_bol; \
	}

#define YY_AT_BOL() (__IDL__current_buffer->__IDL__at_bol)

typedef unsigned char YY_CHAR;
FILE *__IDL_in = (FILE *) 0, *__IDL_out = (FILE *) 0;
typedef int __IDL__state_type;
extern char *__IDL_text;
#define __IDL_text_ptr __IDL_text

static __IDL__state_type __IDL__get_previous_state YY_PROTO(( void ));
static __IDL__state_type __IDL__try_NUL_trans YY_PROTO(( __IDL__state_type current_state ));
static int __IDL__get_next_buffer YY_PROTO(( void ));
static void __IDL__fatal_error YY_PROTO(( __IDL_const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up __IDL_text.
 */
#define YY_DO_BEFORE_ACTION \
	__IDL_text_ptr = __IDL__bp; \
	__IDL_leng = (int) (__IDL__cp - __IDL__bp); \
	__IDL__hold_char = *__IDL__cp; \
	*__IDL__cp = '\0'; \
	__IDL__c_buf_p = __IDL__cp;

#define YY_NUM_RULES 68
#define YY_END_OF_BUFFER 69
static __IDL_const short int __IDL__accept[351] =
    {   0,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        3,    3,   69,   67,    7,   64,   67,   67,   67,   67,
       67,    8,    9,   67,   67,   67,   55,   55,   55,   67,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,    7,    6,   67,
       67,   67,   59,   58,   67,    7,   64,   67,    7,    6,
        3,    3,    3,    3,    3,    3,    7,    0,   63,    0,
       62,    0,   12,   66,   65,   12,    8,   11,    0,    0,
        9,   51,   53,   52,   55,   57,   55,   55,   56,   56,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,   28,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
        7,    6,    6,    6,    5,    6,    1,    0,    0,   59,
        0,   61,    7,   66,   65,    7,    6,    6,    6,    6,
        5,    6,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    2,    0,    0,    0,   65,   12,    0,   12,
       10,   55,   55,   56,   15,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   36,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,    5,    5,    6,    1,

       47,   60,   65,   61,    5,    5,    5,    6,    3,    3,
        3,    3,    2,    0,    0,   12,   55,   14,   56,   55,
       55,   18,   19,   55,   55,   55,   55,   24,   55,   55,
       55,   55,   55,   31,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   48,   55,
       55,    6,    6,    3,   13,   56,   55,   55,   20,   55,
       55,   55,   55,   26,   27,   29,   55,   55,   55,   34,
       55,   55,   55,   55,   40,   55,   55,   55,   55,   45,
       55,   49,   55,    6,    6,    3,   56,   55,   55,   55,
       55,   23,   55,   55,   32,   33,   35,   37,   55,   55,

       41,   42,   43,   55,   55,   55,    6,    6,    3,   56,
       55,   17,   21,   22,   55,   55,   55,   55,   44,   55,
       50,    4,    4,    3,   56,   55,   55,   55,   38,   39,
       46,    4,    4,    4,    4,    4,    3,    3,   56,   16,
       25,   30,   56,    0,    0,    0,   54,    0,    0,    0
    } ;

static __IDL_const int __IDL__ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    6,    1,    7,    8,
        9,   10,    1,    1,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
        1,   18,    1,    1,   19,   20,   20,   21,   22,   23,
       24,   24,   24,   24,   24,   25,   24,   24,   24,   24,
       24,   26,   27,   28,   29,   24,   24,   30,   24,   24,
        1,    1,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   24,   24,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   54,
       55,   24,   56,    1,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static __IDL_const int __IDL__meta[58] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    5,    5,    1,    1,    1,    6,    6,
        6,    6,    6,    7,    7,    7,    7,    7,    7,    7,
        1,    8,    6,    6,    6,    6,    6,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    1,    1
    } ;

static __IDL_const short int __IDL__base[379] =
    {   0,
        0,   56,  925,   58,   70,  127,   87,   90,    0,   63,
       95,  104,  936,  938,  933,  938,   63,  108,   90,   98,
       81,  173,  134,  918,  916,  914,  899,  128,   88,  898,
      118,  119,  121,  120,  135,  131,  137,  145,  146,   86,
      161,  143,  167,  142,  154,  168,  176,  119,  200,  873,
      204,    0,    0,  938,  919,  114,  918,  213,  219,  227,
        0,  924,  112,  229,  230,  868,  922,  234,  938,  232,
      938,  235,  238,  938,    0,  243,  269,  938,  240,    0,
      273,  938,  938,  938,  891,    0,  208,  234,    0,  886,
      237,  211,  254,  240,  235,  238,  264,  150,  246,  266,

      261,  268,  271,  275,  272,  279,  280,  285,  282,  286,
      291,  230,  288,  293,  294,  160,  296,  299,  302,  304,
      341,  336,    0,  342,  333,  873,    0,  908,  910,    0,
      909,  938,  350,  908,  346,  356,  360,  357,  369,    0,
      376,  361,    0,  914,    0,    0,  371,  366,    0,  384,
      378,  867,    0,  380,  390,  399,    0,  403,  382,  393,
        0,  395,  345,  877,  881,  355,  387,  391,  388,  399,
      400,  403,  357,  406,  409,  412,  402,  410,  418,  419,
      420,  422,  423,  880,  424,  426,  428,  432,  431,  433,
      434,  436,  437,  452,  442,  445,    0,  471,  878,    0,

      938,  938,  486,    0,  487,    0,  488,  489,    0,    0,
      485,  877,    0,  490,  492,  494,  488,  877,  873,  480,
      481,  875,  874,  469,  491,  482,  483,  873,  307,  495,
      484,  485,  492,  872,  497,  435,  498,  504,  506,  500,
      509,  510,  512,  515,  517,  519,  521,  522,  871,  525,
      526,  863,  559,  862,  868,  857,  532,  537,  866,  527,
      540,  539,  542,  865,  864,  863,  545,  543,  547,  862,
      531,  546,  553,  555,  861,  557,  556,  561,  568,  860,
      558,  859,  559,  847,  601,  846,  839,  562,  575,  576,
      577,  855,  579,  582,  854,  853,  852,  851,  580,  586,

      848,  839,  823,  585,  592,  593,  814,  625,  806,  785,
      598,  775,  767,  753,  601,  603,  584,  599,  745,  605,
      737,  740,  640,  731,  644,  608,  615,  618,  647,  646,
      636,    0,  654,  648,  651,    0,    0,  650,  459,  389,
      216,   27,  659,  661,  663,  668,  938,  671,  673,  938,
      682,  690,  698,  706,  714,  718,  722,  730,  738,  742,
      750,  758,  766,  774,  782,  786,  788,  796,  804,  812,
      820,  828,  836,  844,  852,  860,  868,  875
    } ;

static __IDL_const short int __IDL__def[379] =
    {   0,
      350,    1,    1,    1,  351,  351,  352,  352,    1,    1,
      353,  353,  350,  350,  350,  350,  354,  355,  350,  350,
      350,  350,  350,  350,  350,  350,  356,  356,  356,  357,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  350,  358,  350,
      350,  359,  360,  350,  361,  361,  361,  361,  361,  362,
      363,  363,  363,  363,  364,  363,  350,  354,  350,  355,
      350,  350,  350,  350,  365,  350,  350,  350,  350,  366,
      350,  350,  350,  350,  356,  367,  356,  356,  357,  357,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      350,  358,  358,  358,  368,  358,  369,  350,  359,  360,
      361,  350,  361,  361,  370,  361,  362,  362,  362,  358,
      371,  362,  363,  363,  363,  372,  363,  364,  364,  364,
      373,  364,  374,  350,  350,  350,  365,  350,  350,  350,
      366,  356,  356,  357,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  368,  368,  358,  369,

      350,  350,  370,  365,  371,  368,  371,  362,  372,  373,
      373,  364,  374,  350,  350,  350,  356,  356,  357,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  358,  362,  364,  356,  357,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  358,  362,  364,  357,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  358,  362,  364,  357,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  375,  376,  377,  357,  356,  356,  356,  356,  356,
      356,  375,  375,  376,  376,  375,  377,  377,  357,  356,
      356,  356,  357,  350,  378,  378,  350,  378,  350,    0,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350
    } ;

static __IDL_const short int __IDL__nxt[996] =
    {   0,
       14,   15,   16,   17,   14,   14,   18,   14,   14,   14,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   27,
       27,   27,   28,   27,   27,   27,   27,   29,   27,   27,
       14,   30,   31,   32,   33,   34,   35,   36,   27,   27,
       37,   38,   39,   40,   41,   27,   27,   42,   43,   44,
       45,   46,   47,   27,   27,   14,   14,   48,   86,   48,
       49,   50,   49,   50,   48,   69,   69,   49,   50,   51,
       14,   15,   16,   14,   14,   14,   14,   52,   14,   14,
       14,   14,   21,   14,   14,   14,   14,   14,   56,   57,
       74,   59,   57,   75,   60,   14,   62,   16,   14,   58,

       54,   14,   58,   72,   72,   64,   16,   63,   65,   66,
       71,   73,   73,   88,   71,  133,   63,   86,  106,   86,
      121,  145,  132,  122,  146,   14,   14,   14,   48,   16,
       14,   49,   14,   14,   52,   14,   14,   14,   14,   21,
       14,   14,   14,   14,   14,   76,   87,   81,   81,   86,
       86,   86,   86,   94,   78,   79,   97,   54,   14,   86,
       95,   91,   86,   93,   98,   96,   86,   92,   86,   78,
       79,  101,  102,   86,   86,  110,   86,   86,   99,  111,
      103,   86,   14,   14,   76,   86,   77,   77,  100,  104,
      105,   86,   86,   78,   79,  107,  116,  117,   86,   86,

      172,  124,   80,  112,  108,  191,  113,   86,   78,   79,
      119,  109,  118,  125,  125,  128,  114,   73,   73,  115,
      136,  132,  134,  137,  120,  135,   80,  132,  139,  131,
      147,  150,  162,  148,   71,  140,   69,   69,   71,   86,
      141,  141,   86,  151,  151,  126,  154,   86,  155,  155,
      159,   73,   73,  160,  160,   78,  158,  158,   78,  156,
      166,   86,  163,   78,   79,   86,   86,  169,   86,   86,
       78,   86,  142,   78,  156,  152,  187,   86,   78,   79,
       76,  170,   77,   77,   76,   86,   81,   81,  168,   78,
       79,  165,   86,   78,   79,   86,  173,   86,  167,   86,

      174,  171,   86,   86,   78,   79,   86,  180,   78,   79,
       86,   86,  176,   86,  175,  177,   86,   86,  179,   86,
      178,  183,   86,  186,   86,   86,  185,   86,  181,  182,
       86,  184,  188,   86,  190,   86,  192,  124,   86,  194,
      189,  195,  121,  124,  193,  122,  198,  198,  131,  125,
      125,  133,  263,  196,  204,  125,  125,  136,  132,  131,
      137,  139,  131,  131,  132,  140,  218,  150,  140,  140,
      139,  131,  147,  141,  141,  148,   86,  140,  131,  151,
      151,  126,  141,  141,  206,  150,   86,  126,   86,  207,
      207,  211,  211,  214,  214,  160,  160,  151,  151,  228,

       78,  154,  220,  155,  155,  142,  160,  160,  208,  215,
       78,  152,  216,  216,  142,   78,  158,  158,   86,   86,
       86,  217,   86,   78,  156,   78,   86,  222,  221,  152,
       86,   86,  226,   86,   86,  223,  227,   86,   78,  156,
       86,   86,  229,   86,  231,  230,  233,  224,  225,   86,
       86,   86,  232,   86,   86,   86,  234,   86,  237,   86,
      236,  240,   86,   86,   86,   86,   86,   86,   86,  235,
      246,  243,  239,   86,  250,  238,   86,  248,  241,  242,
      247,  244,  245,   86,  198,  198,  269,  249,  131,  131,
      131,  131,  251,  343,  204,  206,  206,  140,  211,  211,

       86,  207,  207,  214,  214,  216,  216,  216,  216,  255,
       78,   86,   86,   86,   86,   86,   86,  258,  259,   86,
      257,  253,   86,   86,  262,   78,   86,  260,   86,   86,
      264,   86,  261,  265,  266,   86,  271,   86,  268,  267,
       86,   86,  272,   86,  273,  274,   86,  270,   86,  277,
       86,  278,   86,   86,  279,  276,   86,   86,   86,  275,
      281,  131,   86,   86,  280,  288,  283,  140,   86,  289,
       86,   86,  282,   86,   86,  292,   86,   86,   86,  295,
      290,  291,  294,  296,   86,  297,   86,   86,   86,   86,
       86,  293,   86,   86,  298,  301,  299,  285,  300,   86,

      303,  305,  306,  131,  304,  302,   86,   86,   86,  140,
       86,   86,  311,   86,  316,   86,   86,   86,  312,  315,
      318,  317,  319,   86,   86,  313,  314,  131,  320,   86,
       86,  321,   86,  140,   86,  330,   86,  328,  329,   86,
      331,  335,  131,  308,  340,  327,   86,  326,  336,   86,
      131,  338,  335,  131,  342,  333,  336,  323,  341,  336,
      344,  344,  344,  344,  346,  346,  345,   86,  345,  346,
      346,  347,  349,  349,  349,  349,  347,   86,   86,  347,
      339,  347,   53,   53,   53,   53,   53,   53,   53,   53,
       55,   55,   55,   55,   55,   55,   55,   55,   61,   61,

       61,   61,   61,   61,   61,   61,   68,   68,   68,   68,
       68,   68,   68,   68,   70,   70,   70,   70,   70,   70,
       70,   70,   85,   85,   85,   85,   89,   89,   89,   89,
      123,  123,  338,  123,  123,  123,  123,  123,  129,  129,
      129,  333,  129,  129,  129,  129,  130,  130,  130,  130,
      131,  131,  131,  131,  131,  131,  131,  131,  138,  138,
      138,  138,  138,  138,  138,  138,  143,  143,   86,  143,
      143,  143,  143,  143,  149,  149,   86,  149,  149,  149,
      149,  149,  157,  157,   86,  157,  157,  157,  157,  157,
      161,  161,   86,   86,   86,   86,  197,  197,   86,  197,

      197,  197,  197,  197,  200,  200,   86,  200,  200,  200,
      200,  200,  203,  203,  203,  203,  203,  203,  203,  203,
      205,  205,  205,  205,  205,  205,  205,  205,  209,  209,
      325,  209,  209,  209,  209,  209,  210,  210,  324,  210,
      210,  210,  210,  210,  213,  213,  322,  213,  213,  213,
      213,  213,  332,  332,   86,  332,  332,  332,  332,  332,
      334,  334,  334,  334,  334,  334,  334,  334,  337,  337,
       86,  337,  337,  337,  337,  337,  348,  348,  348,   86,
      348,  348,   86,   86,   86,   86,   86,  310,  309,  307,
       86,   86,   86,   86,   86,   86,   86,   86,  287,   86,

      286,  284,   86,   86,   86,   86,   86,  256,   86,  254,
      252,   86,   86,  219,  212,  144,  132,  132,  202,  201,
      199,  164,   86,   67,  153,  144,  132,  132,  127,   90,
       86,   84,   83,   82,   67,  350,   51,   13,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350

    } ;

static __IDL_const short int __IDL__chk[996] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,  342,    4,
        2,    2,    4,    4,   10,   17,   17,   10,   10,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    7,    7,
       21,    8,    8,   21,    8,    7,   11,   11,    8,    7,

        5,    5,    8,   19,   19,   12,   12,   11,   12,   12,
       18,   20,   20,   29,   18,   56,   12,   40,   40,   29,
       48,   63,   56,   48,   63,    5,    5,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,   23,   28,   23,   23,   31,
       32,   34,   33,   33,   23,   23,   34,    6,    6,   28,
       33,   31,   36,   32,   34,   33,   35,   31,   37,   23,
       23,   36,   36,   44,   42,   42,   38,   39,   35,   42,
       37,   98,    6,    6,   22,   45,   22,   22,   35,   38,
       39,  116,   41,   22,   22,   41,   44,   45,   43,   46,

       98,   49,   22,   43,   41,  116,   43,   47,   22,   22,
       47,   41,   46,   49,   49,   51,   43,   51,   51,   43,
       59,   58,   58,   59,   47,   58,   22,   59,   60,   60,
       64,   65,   87,   64,   70,   60,   68,   68,   70,   87,
       60,   60,   92,   65,   65,   49,   72,  341,   72,   72,
       79,   73,   73,   79,   79,   72,   76,   76,   73,   73,
       92,  112,   88,   76,   76,   88,   95,   95,   91,   96,
       72,   94,   60,   73,   73,   65,  112,   99,   76,   76,
       77,   96,   77,   77,   81,   93,   81,   81,   94,   77,
       77,   91,  101,   81,   81,   97,   99,  100,   93,  102,

      100,   97,  103,  105,   77,   77,  104,  105,   81,   81,
      106,  107,  102,  109,  101,  103,  108,  110,  104,  113,
      103,  108,  111,  111,  114,  115,  110,  117,  106,  107,
      118,  109,  113,  119,  115,  120,  117,  122,  229,  118,
      114,  119,  121,  124,  117,  121,  125,  125,  135,  122,
      122,  133,  229,  120,  135,  124,  124,  136,  133,  138,
      136,  137,  137,  142,  136,  138,  163,  148,  137,  142,
      139,  139,  147,  137,  137,  147,  163,  139,  141,  148,
      148,  122,  139,  139,  141,  150,  166,  124,  173,  141,
      141,  151,  151,  154,  154,  159,  159,  150,  150,  173,

      154,  155,  166,  155,  155,  137,  160,  160,  142,  156,
      155,  148,  156,  156,  139,  154,  158,  158,  167,  169,
      340,  162,  168,  158,  158,  155,  162,  168,  167,  150,
      170,  171,  171,  177,  172,  169,  172,  174,  158,  158,
      175,  178,  174,  176,  176,  175,  178,  170,  170,  179,
      180,  181,  177,  182,  183,  185,  179,  186,  182,  187,
      181,  186,  189,  188,  190,  191,  236,  192,  193,  180,
      191,  189,  185,  195,  195,  183,  196,  193,  187,  188,
      192,  189,  190,  194,  198,  198,  236,  194,  203,  205,
      207,  208,  196,  339,  203,  205,  207,  208,  211,  211,

      224,  207,  207,  214,  214,  215,  215,  216,  216,  217,
      214,  220,  221,  226,  227,  231,  232,  221,  224,  217,
      220,  208,  225,  233,  227,  214,  230,  225,  235,  237,
      230,  240,  226,  231,  232,  238,  238,  239,  235,  233,
      241,  242,  239,  243,  240,  241,  244,  237,  245,  244,
      246,  245,  247,  248,  246,  243,  250,  251,  260,  242,
      248,  253,  271,  257,  247,  257,  251,  253,  258,  258,
      262,  261,  250,  263,  268,  262,  267,  272,  269,  268,
      260,  261,  267,  269,  273,  271,  274,  277,  276,  281,
      283,  263,  278,  288,  272,  276,  273,  253,  274,  279,

      278,  281,  283,  285,  279,  277,  289,  290,  291,  285,
      293,  299,  288,  294,  294,  317,  304,  300,  289,  293,
      300,  299,  304,  305,  306,  290,  291,  308,  305,  311,
      318,  306,  315,  308,  316,  318,  320,  316,  317,  326,
      320,  323,  323,  285,  326,  315,  327,  311,  323,  328,
      334,  338,  335,  335,  328,  333,  334,  308,  327,  335,
      343,  343,  344,  344,  345,  345,  343,  331,  344,  346,
      346,  345,  348,  348,  349,  349,  346,  330,  329,  348,
      325,  349,  351,  351,  351,  351,  351,  351,  351,  351,
      352,  352,  352,  352,  352,  352,  352,  352,  353,  353,

      353,  353,  353,  353,  353,  353,  354,  354,  354,  354,
      354,  354,  354,  354,  355,  355,  355,  355,  355,  355,
      355,  355,  356,  356,  356,  356,  357,  357,  357,  357,
      358,  358,  324,  358,  358,  358,  358,  358,  359,  359,
      359,  322,  359,  359,  359,  359,  360,  360,  360,  360,
      361,  361,  361,  361,  361,  361,  361,  361,  362,  362,
      362,  362,  362,  362,  362,  362,  363,  363,  321,  363,
      363,  363,  363,  363,  364,  364,  319,  364,  364,  364,
      364,  364,  365,  365,  314,  365,  365,  365,  365,  365,
      366,  366,  367,  367,  367,  367,  368,  368,  313,  368,

      368,  368,  368,  368,  369,  369,  312,  369,  369,  369,
      369,  369,  370,  370,  370,  370,  370,  370,  370,  370,
      371,  371,  371,  371,  371,  371,  371,  371,  372,  372,
      310,  372,  372,  372,  372,  372,  373,  373,  309,  373,
      373,  373,  373,  373,  374,  374,  307,  374,  374,  374,
      374,  374,  375,  375,  303,  375,  375,  375,  375,  375,
      376,  376,  376,  376,  376,  376,  376,  376,  377,  377,
      302,  377,  377,  377,  377,  377,  378,  378,  378,  301,
      378,  378,  298,  297,  296,  295,  292,  287,  286,  284,
      282,  280,  275,  270,  266,  265,  264,  259,  256,  255,

      254,  252,  249,  234,  228,  223,  222,  219,  218,  212,
      199,  184,  165,  164,  152,  144,  134,  131,  129,  128,
      126,   90,   85,   67,   66,   62,   57,   55,   50,   30,
       27,   26,   25,   24,   15,   13,    3,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350

    } ;

static __IDL__state_type __IDL__last_accepting_state;
static char *__IDL__last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define __IDL_more() __IDL_more_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *__IDL_text;
#line 1 "lexer.l"
#define INITIAL 0
/***************************************************************************

    lexer.l (IDL lex scanner)

    Copyright (C) 1998, 1999 Andrew T. Veliath

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public
    License along with this library; if not, write to the Free
    Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

    $Id: lexer.l,v 1.83 2003/05/09 15:19:06 jody Exp $

***************************************************************************/
#line 25 "lexer.l"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include "rename.h"
#include "util.h"
#include "parser.h"

#ifdef XP_MAC
#  include <unix.h>
#  define YY_NEVER_INTERACTIVE 1
#endif

/* Eliminate warning */
#define YY_NO_UNPUT 1

#define YY_INPUT(buf,result,the_max_size)	do {				\
	if (__IDL_inputcb == NULL) {						\
		if ((result = fread (buf, 1, the_max_size, __IDL_in)) == YY_NULL &&	\
		    ferror (__IDL_in))						\
			YY_FATAL_ERROR ("input in scanner failed");		\
	} else {								\
		union IDL_input_data data;					\
										\
		data.fill.buffer = buf;						\
		data.fill.max_size = the_max_size;				\
		result = (*__IDL_inputcb) (IDL_INPUT_REASON_FILL, &data,	\
					   __IDL_inputcb_user_data);		\
		if (result < 0)							\
			YY_FATAL_ERROR ("input callback returned failure");	\
	}									\
} while (0)

#define tokreturn(token)			do {	\
	__IDL_prev_token_line = __IDL_cur_token_line;	\
	__IDL_cur_token_line = __IDL_cur_line;		\
	return token;					\
} while (0)

#define SELECT_START				\
	/* Parser driven start conditions */	\
	if (__IDL_flagsi & IDLFP_PROPERTIES)	\
		BEGIN (PROP);			\
	else if (__IDL_flagsi & IDLFP_NATIVE)	\
		BEGIN (NATIVE);			\
	/* Global syntax start conditions */	\
	else if (__IDL_flags & IDLF_XPIDL)	\
		BEGIN (XP);			\
	else if (__IDL_flags & IDLF_CODEFRAGS)	\
		BEGIN (CFRG);

#define SELECT_RESTART				\
	SELECT_START				\
	else					\
		BEGIN (INITIAL);

static int		count_nl			(const char *s);

#ifdef YYDEBUG
extern int				__IDL_debug;
#endif
int					__IDL_prev_token_line;
int					__IDL_cur_token_line;
static int				warn_underscores;
static char *				codefrag_desc;
static GSList *				codefrag_list;
static GSList *				codefrag_list_tail;
#define XP 1

#define PROP 2

#define NATIVE 3

#define CFRG 4

#define CFRGX 5


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int __IDL_wrap YY_PROTO(( void ));
#else
extern int __IDL_wrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void __IDL_unput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef __IDL_text_ptr
static void __IDL__flex_strncpy YY_PROTO(( char *, __IDL_const char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int __IDL__flex_strlen YY_PROTO(( __IDL_const char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int __IDL_input YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int __IDL__start_stack_ptr = 0;
static int __IDL__start_stack_depth = 0;
static int *__IDL__start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void __IDL__push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void __IDL__pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int __IDL__top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( __IDL_text, __IDL_leng, 1, __IDL_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( __IDL__current_buffer->__IDL__is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( __IDL_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( __IDL_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, __IDL_in )) == 0) \
		  && ferror( __IDL_in ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "__IDL_terminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef __IDL_terminate
#define __IDL_terminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) __IDL__fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int __IDL_lex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after __IDL_text and __IDL_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( __IDL_leng > 0 ) \
		__IDL__current_buffer->__IDL__at_bol = \
				(__IDL_text[__IDL_leng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register __IDL__state_type __IDL__current_state;
	register char *__IDL__cp, *__IDL__bp;
	register int __IDL__act;

#line 126 "lexer.l"


	SELECT_START;


	if ( __IDL__init )
		{
		__IDL__init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! __IDL__start )
			__IDL__start = 1;	/* first start state */

		if ( ! __IDL_in )
			__IDL_in = stdin;

		if ( ! __IDL_out )
			__IDL_out = stdout;

		if ( ! __IDL__current_buffer )
			__IDL__current_buffer =
				__IDL__create_buffer( __IDL_in, YY_BUF_SIZE );

		__IDL__load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		__IDL__cp = __IDL__c_buf_p;

		/* Support of __IDL_text. */
		*__IDL__cp = __IDL__hold_char;

		/* __IDL__bp points to the position in __IDL__ch_buf of the start of
		 * the current run.
		 */
		__IDL__bp = __IDL__cp;

		__IDL__current_state = __IDL__start;
		__IDL__current_state += YY_AT_BOL();
__IDL__match:
		do
			{
			register YY_CHAR __IDL__c = __IDL__ec[YY_SC_TO_UI(*__IDL__cp)];
			if ( __IDL__accept[__IDL__current_state] )
				{
				__IDL__last_accepting_state = __IDL__current_state;
				__IDL__last_accepting_cpos = __IDL__cp;
				}
			while ( __IDL__chk[__IDL__base[__IDL__current_state] + __IDL__c] != __IDL__current_state )
				{
				__IDL__current_state = (int) __IDL__def[__IDL__current_state];
				if ( __IDL__current_state >= 351 )
					__IDL__c = __IDL__meta[(unsigned int) __IDL__c];
				}
			__IDL__current_state = __IDL__nxt[__IDL__base[__IDL__current_state] + (unsigned int) __IDL__c];
			++__IDL__cp;
			}
		while ( __IDL__base[__IDL__current_state] != 938 );

__IDL__find_action:
		__IDL__act = __IDL__accept[__IDL__current_state];
		if ( __IDL__act == 0 )
			{ /* have to back up */
			__IDL__cp = __IDL__last_accepting_cpos;
			__IDL__current_state = __IDL__last_accepting_state;
			__IDL__act = __IDL__accept[__IDL__current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( __IDL__act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*__IDL__cp = __IDL__hold_char;
			__IDL__cp = __IDL__last_accepting_cpos;
			__IDL__current_state = __IDL__last_accepting_state;
			goto __IDL__find_action;

case 1:
YY_RULE_SETUP
#line 130 "lexer.l"
{
	char *s = __IDL_text + 2;

	while (g_ascii_isspace (*s)) ++s;
	codefrag_desc = g_strdup (s);
	codefrag_list = codefrag_list_tail = NULL;

	if (!(__IDL_flags & IDLF_XPIDL || __IDL_flags & IDLF_CODEFRAGS))
		__IDL_error ("Code fragment syntax not enabled");
	else
		BEGIN (CFRGX);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 142 "lexer.l"
{
	__IDL_lval.tree = IDL_codefrag_new (codefrag_desc, codefrag_list);
	tokreturn (TOK_CODEFRAG);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 146 "lexer.l"
{
	char *s;
	GSList *slist;

	s = g_strdup (__IDL_text);
	slist = g_slist_alloc ();
	slist->data = s;

	if (codefrag_list == NULL) {
		codefrag_list = slist;
		codefrag_list_tail = slist;
	} else {
		codefrag_list_tail->next = slist;
		codefrag_list_tail = slist;
	}
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 162 "lexer.l"
{
	int n;
	char *p = __IDL_text;
	char *s, *t;

	while (g_ascii_isspace (*p) || *p == '#') ++p;
	s = p;
	sscanf (p, "%*6s%n", &n); s += n;
	while (g_ascii_isspace (*s)) ++s;

	t = s + strlen(s) - 1;
	while(g_ascii_isspace(*t) && t > s) *(t--) = '\0'; /* Chomp trailing spaces */

	__IDL_do_pragma (s);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 177 "lexer.l"
{
	gchar *mytext = __IDL_text;
	gint   line;

	while (g_ascii_isspace (*mytext))
		mytext++;

	g_assert (mytext [0] == '#' && mytext [1] == ' ');

	mytext += 2;

	line = atoi (mytext);

	while (g_ascii_isdigit (*mytext))
		mytext++;

	if (g_ascii_isspace (*mytext)) {
		mytext++;

		if (mytext [0] == '"') {
			gchar *p = ++mytext;

			while (*p && *p != '"') p++;

			*p = '\0';
		}

		if (mytext [0] ==  '<' &&
		    (!strcmp (mytext, "<builtin>")  ||
		     !strcmp (mytext, "<built-in>") ||
		     !strcmp (mytext, "<stdin>")    ||
		     !strcmp (mytext, "<command-line>") ||
		     !strcmp (mytext, "<command line>")))
		    
			__IDL_lval.tree = IDL_file_set ("", line);
		else {
			gchar *filename = g_strdup (mytext);

			__IDL_lval.tree = IDL_file_set (filename, line);

			g_free (filename);
		}
	}
	else
		__IDL_lval.tree = IDL_file_set ("", line);

	if (__IDL_lval.tree)
	 	tokreturn (TOK_SRCFILE);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 226 "lexer.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 227 "lexer.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 228 "lexer.l"
{
	__IDL_lval.integer = 0;
	sscanf (__IDL_text, "%" IDL_LL "o", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 233 "lexer.l"
{
	__IDL_lval.integer = 0;
	sscanf (__IDL_text, "%" IDL_LL "u", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 238 "lexer.l"
{
	__IDL_lval.integer = 0;
	sscanf (__IDL_text + 2, "%" IDL_LL "x", &__IDL_lval.integer);
	tokreturn (TOK_INTEGER);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 243 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_FIXEDP);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 247 "lexer.l"
{
	__IDL_lval.floatp = atof (__IDL_text);
	tokreturn (TOK_FLOATP);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 251 "lexer.l"
tokreturn (TOK_FALSE);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 252 "lexer.l"
tokreturn (TOK_TRUE);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 253 "lexer.l"
tokreturn (TOK_ANY);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 254 "lexer.l"
tokreturn (TOK_ATTRIBUTE);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 255 "lexer.l"
tokreturn (TOK_BOOLEAN);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 256 "lexer.l"
tokreturn (TOK_CASE);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 257 "lexer.l"
tokreturn (TOK_CHAR);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 258 "lexer.l"
tokreturn (TOK_CONST);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 259 "lexer.l"
tokreturn (TOK_CONTEXT);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 260 "lexer.l"
tokreturn (TOK_DEFAULT);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 261 "lexer.l"
tokreturn (TOK_DOUBLE);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 262 "lexer.l"
tokreturn (TOK_ENUM);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 263 "lexer.l"
tokreturn (TOK_EXCEPTION);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 264 "lexer.l"
tokreturn (TOK_FIXED);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 265 "lexer.l"
tokreturn (TOK_FLOAT);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 266 "lexer.l"
tokreturn (TOK_IN);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 267 "lexer.l"
tokreturn (TOK_INOUT);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 268 "lexer.l"
tokreturn (TOK_INTERFACE);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 269 "lexer.l"
tokreturn (TOK_LONG);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 270 "lexer.l"
tokreturn (TOK_MODULE);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 271 "lexer.l"
tokreturn (TOK_NATIVE);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 272 "lexer.l"
tokreturn (TOK_OCTET);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 273 "lexer.l"
tokreturn (TOK_ONEWAY);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 274 "lexer.l"
tokreturn (TOK_OUT);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 275 "lexer.l"
tokreturn (TOK_RAISES);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 276 "lexer.l"
tokreturn (TOK_READONLY);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 277 "lexer.l"
tokreturn (TOK_SEQUENCE);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 278 "lexer.l"
tokreturn (TOK_SHORT);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 279 "lexer.l"
tokreturn (TOK_STRING);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 280 "lexer.l"
tokreturn (TOK_STRUCT);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 281 "lexer.l"
tokreturn (TOK_SWITCH);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 282 "lexer.l"
tokreturn (TOK_TYPEDEF);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 283 "lexer.l"
tokreturn (TOK_UNION);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 284 "lexer.l"
tokreturn (TOK_UNSIGNED);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 285 "lexer.l"
tokreturn (TOK_VARARGS);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 286 "lexer.l"
tokreturn (TOK_VOID);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 287 "lexer.l"
tokreturn (TOK_WCHAR);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 288 "lexer.l"
tokreturn (TOK_WSTRING);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 289 "lexer.l"
tokreturn (TOK_OP_SCOPE);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 290 "lexer.l"
tokreturn (TOK_OP_SHR);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 291 "lexer.l"
tokreturn (TOK_OP_SHL);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 292 "lexer.l"
{
	char *s = g_strdup (__IDL_text);

	/* Get the parenthesized expression (ignoring whitespace) */
	sscanf (__IDL_text, "__declspec %*[(] %[A-Za-z_] %*[)]", s);
	__IDL_lval.str = s;
	__IDL_cur_line += count_nl (__IDL_text);
	tokreturn (TOK_DECLSPEC);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 301 "lexer.l"
{
#if 0
	if ((__IDL_flags & IDLF_TYPECODES) && strcmp (__IDL_text, "TypeCode") == 0)
		tokreturn (TOK_TYPECODE);
#endif
	if (__IDL_typecodes_as_tok>0 && strcmp (__IDL_text, "TypeCode") == 0)
		tokreturn (TOK_TYPECODE);
	if ( (__IDL_pidl <= 0) && strcmp(__IDL_text, "Object")==0 )
		tokreturn (TOK_OBJECT);
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_IDENT);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 313 "lexer.l"
{
	__IDL_lval.str = g_strdup (&__IDL_text[1]);
	tokreturn (TOK_IDENT);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 317 "lexer.l"
{
	if (!warn_underscores) {
		__IDL_warningv (IDL_WARNING2,
			   "`%s' underscores within identifiers are discouraged for use "
			   "with C-language IDL mappings", __IDL_text);
		warn_underscores = 1;
	}
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_IDENT);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 327 "lexer.l"
{
	__IDL_flagsi &= ~IDLFP_PROPERTIES;
	SELECT_RESTART;
	tokreturn (__IDL_text[0]);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 332 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text);
	tokreturn (TOK_PROP_KEY);
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 336 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text + 1);
	__IDL_lval.str[strlen (__IDL_lval.str) - 1] = 0;
	tokreturn (TOK_PROP_VALUE);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 341 "lexer.l"
{
	__IDL_flagsi &= ~IDLFP_NATIVE;
	__IDL_lval.str = g_strdup (__IDL_text);
	__IDL_lval.str[strlen (__IDL_lval.str) - 1] = 0;
	tokreturn (TOK_NATIVE_TYPE);
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 347 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text + 1);
	__IDL_lval.str[strlen (__IDL_text) - 2] = 0;
	tokreturn (TOK_SQSTRING);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 352 "lexer.l"
{
	__IDL_lval.str = g_strdup (__IDL_text + 1);
	__IDL_lval.str[strlen (__IDL_text) - 2] = 0;
	tokreturn (TOK_DQSTRING);
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 357 "lexer.l"
++__IDL_cur_line;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 358 "lexer.l"
;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 359 "lexer.l"
{
	int c;

	while (1) {
		while ((c = input ()) != '*' && c != EOF)
			if (c == '\n') ++__IDL_cur_line;
		if (c == '*') {
			while ((c = input ()) == '*') ;
			if (c == '/') break;
		}
		if (c == '\n') ++__IDL_cur_line;
		if (c == EOF) {
			__IDL_warning (IDL_WARNING1, "End of file in comment");
			break;
		}
	}
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 376 "lexer.l"
tokreturn (__IDL_text[0]);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 378 "lexer.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(XP):
case YY_STATE_EOF(PROP):
case YY_STATE_EOF(NATIVE):
case YY_STATE_EOF(CFRG):
case YY_STATE_EOF(CFRGX):
	__IDL_terminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int __IDL__amount_of_matched_text = (int) (__IDL__cp - __IDL_text_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*__IDL__cp = __IDL__hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( __IDL__current_buffer->__IDL__buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed __IDL_in at a new source and called
			 * __IDL_lex().  If so, then we have to assure
			 * consistency between __IDL__current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			__IDL__n_chars = __IDL__current_buffer->__IDL__n_chars;
			__IDL__current_buffer->__IDL__input_file = __IDL_in;
			__IDL__current_buffer->__IDL__buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for __IDL__c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since __IDL__c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( __IDL__c_buf_p <= &__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars] )
			{ /* This was really a NUL. */
			__IDL__state_type __IDL__next_state;

			__IDL__c_buf_p = __IDL_text_ptr + __IDL__amount_of_matched_text;

			__IDL__current_state = __IDL__get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * __IDL__get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			__IDL__next_state = __IDL__try_NUL_trans( __IDL__current_state );

			__IDL__bp = __IDL_text_ptr + YY_MORE_ADJ;

			if ( __IDL__next_state )
				{
				/* Consume the NUL. */
				__IDL__cp = ++__IDL__c_buf_p;
				__IDL__current_state = __IDL__next_state;
				goto __IDL__match;
				}

			else
				{
				__IDL__cp = __IDL__c_buf_p;
				goto __IDL__find_action;
				}
			}

		else switch ( __IDL__get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				__IDL__did_buffer_switch_on_eof = 0;

				if ( __IDL_wrap() )
					{
					/* Note: because we've taken care in
					 * __IDL__get_next_buffer() to have set up
					 * __IDL_text, we can now set up
					 * __IDL__c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					__IDL__c_buf_p = __IDL_text_ptr + YY_MORE_ADJ;

					__IDL__act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! __IDL__did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				__IDL__c_buf_p =
					__IDL_text_ptr + __IDL__amount_of_matched_text;

				__IDL__current_state = __IDL__get_previous_state();

				__IDL__cp = __IDL__c_buf_p;
				__IDL__bp = __IDL_text_ptr + YY_MORE_ADJ;
				goto __IDL__match;

			case EOB_ACT_LAST_MATCH:
				__IDL__c_buf_p =
				&__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars];

				__IDL__current_state = __IDL__get_previous_state();

				__IDL__cp = __IDL__c_buf_p;
				__IDL__bp = __IDL_text_ptr + YY_MORE_ADJ;
				goto __IDL__find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of __IDL_lex */


/* __IDL__get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int __IDL__get_next_buffer()
	{
	register char *dest = __IDL__current_buffer->__IDL__ch_buf;
	register char *source = __IDL_text_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( __IDL__c_buf_p > &__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( __IDL__current_buffer->__IDL__fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( __IDL__c_buf_p - __IDL_text_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (__IDL__c_buf_p - __IDL_text_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( __IDL__current_buffer->__IDL__buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		__IDL__current_buffer->__IDL__n_chars = __IDL__n_chars = 0;

	else
		{
		int num_to_read =
			__IDL__current_buffer->__IDL__buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = __IDL__current_buffer;

			int __IDL__c_buf_p_offset =
				(int) (__IDL__c_buf_p - b->__IDL__ch_buf);

			if ( b->__IDL__is_our_buffer )
				{
				int new_size = b->__IDL__buf_size * 2;

				if ( new_size <= 0 )
					b->__IDL__buf_size += b->__IDL__buf_size / 8;
				else
					b->__IDL__buf_size *= 2;

				b->__IDL__ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					__IDL__flex_realloc( (void *) b->__IDL__ch_buf,
							 b->__IDL__buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->__IDL__ch_buf = 0;

			if ( ! b->__IDL__ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			__IDL__c_buf_p = &b->__IDL__ch_buf[__IDL__c_buf_p_offset];

			num_to_read = __IDL__current_buffer->__IDL__buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&__IDL__current_buffer->__IDL__ch_buf[number_to_move]),
			__IDL__n_chars, num_to_read );

		__IDL__current_buffer->__IDL__n_chars = __IDL__n_chars;
		}

	if ( __IDL__n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			__IDL_restart( __IDL_in );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			__IDL__current_buffer->__IDL__buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	__IDL__n_chars += number_to_move;
	__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars] = YY_END_OF_BUFFER_CHAR;
	__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	__IDL_text_ptr = &__IDL__current_buffer->__IDL__ch_buf[0];

	return ret_val;
	}


/* __IDL__get_previous_state - get the state just before the EOB char was reached */

static __IDL__state_type __IDL__get_previous_state()
	{
	register __IDL__state_type __IDL__current_state;
	register char *__IDL__cp;

	__IDL__current_state = __IDL__start;
	__IDL__current_state += YY_AT_BOL();

	for ( __IDL__cp = __IDL_text_ptr + YY_MORE_ADJ; __IDL__cp < __IDL__c_buf_p; ++__IDL__cp )
		{
		register YY_CHAR __IDL__c = (*__IDL__cp ? __IDL__ec[YY_SC_TO_UI(*__IDL__cp)] : 1);
		if ( __IDL__accept[__IDL__current_state] )
			{
			__IDL__last_accepting_state = __IDL__current_state;
			__IDL__last_accepting_cpos = __IDL__cp;
			}
		while ( __IDL__chk[__IDL__base[__IDL__current_state] + __IDL__c] != __IDL__current_state )
			{
			__IDL__current_state = (int) __IDL__def[__IDL__current_state];
			if ( __IDL__current_state >= 351 )
				__IDL__c = __IDL__meta[(unsigned int) __IDL__c];
			}
		__IDL__current_state = __IDL__nxt[__IDL__base[__IDL__current_state] + (unsigned int) __IDL__c];
		}

	return __IDL__current_state;
	}


/* __IDL__try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = __IDL__try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static __IDL__state_type __IDL__try_NUL_trans( __IDL__state_type __IDL__current_state )
#else
static __IDL__state_type __IDL__try_NUL_trans( __IDL__current_state )
__IDL__state_type __IDL__current_state;
#endif
	{
	register int __IDL__is_jam;
	register char *__IDL__cp = __IDL__c_buf_p;

	register YY_CHAR __IDL__c = 1;
	if ( __IDL__accept[__IDL__current_state] )
		{
		__IDL__last_accepting_state = __IDL__current_state;
		__IDL__last_accepting_cpos = __IDL__cp;
		}
	while ( __IDL__chk[__IDL__base[__IDL__current_state] + __IDL__c] != __IDL__current_state )
		{
		__IDL__current_state = (int) __IDL__def[__IDL__current_state];
		if ( __IDL__current_state >= 351 )
			__IDL__c = __IDL__meta[(unsigned int) __IDL__c];
		}
	__IDL__current_state = __IDL__nxt[__IDL__base[__IDL__current_state] + (unsigned int) __IDL__c];
	__IDL__is_jam = (__IDL__current_state == 350);

	return __IDL__is_jam ? 0 : __IDL__current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void __IDL_unput( int c, register char *__IDL__bp )
#else
static void __IDL_unput( c, __IDL__bp )
int c;
register char *__IDL__bp;
#endif
	{
	register char *__IDL__cp = __IDL__c_buf_p;

	/* undo effects of setting up __IDL_text */
	*__IDL__cp = __IDL__hold_char;

	if ( __IDL__cp < __IDL__current_buffer->__IDL__ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = __IDL__n_chars + 2;
		register char *dest = &__IDL__current_buffer->__IDL__ch_buf[
					__IDL__current_buffer->__IDL__buf_size + 2];
		register char *source =
				&__IDL__current_buffer->__IDL__ch_buf[number_to_move];

		while ( source > __IDL__current_buffer->__IDL__ch_buf )
			*--dest = *--source;

		__IDL__cp += (int) (dest - source);
		__IDL__bp += (int) (dest - source);
		__IDL__current_buffer->__IDL__n_chars =
			__IDL__n_chars = __IDL__current_buffer->__IDL__buf_size;

		if ( __IDL__cp < __IDL__current_buffer->__IDL__ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--__IDL__cp = (char) c;


	__IDL_text_ptr = __IDL__bp;
	__IDL__hold_char = *__IDL__cp;
	__IDL__c_buf_p = __IDL__cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int __IDL_input()
#else
static int input()
#endif
	{
	int c;

	*__IDL__c_buf_p = __IDL__hold_char;

	if ( *__IDL__c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* __IDL__c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( __IDL__c_buf_p < &__IDL__current_buffer->__IDL__ch_buf[__IDL__n_chars] )
			/* This was really a NUL. */
			*__IDL__c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = __IDL__c_buf_p - __IDL_text_ptr;
			++__IDL__c_buf_p;

			switch ( __IDL__get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because __IDL__g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					__IDL_restart( __IDL_in );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( __IDL_wrap() )
						return EOF;

					if ( ! __IDL__did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return __IDL_input();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					__IDL__c_buf_p = __IDL_text_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) __IDL__c_buf_p;	/* cast for 8-bit char's */
	*__IDL__c_buf_p = '\0';	/* preserve __IDL_text */
	__IDL__hold_char = *++__IDL__c_buf_p;

	__IDL__current_buffer->__IDL__at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void __IDL_restart( FILE *input_file )
#else
void __IDL_restart( input_file )
FILE *input_file;
#endif
	{
	if ( ! __IDL__current_buffer )
		__IDL__current_buffer = __IDL__create_buffer( __IDL_in, YY_BUF_SIZE );

	__IDL__init_buffer( __IDL__current_buffer, input_file );
	__IDL__load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void __IDL__switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void __IDL__switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( __IDL__current_buffer == new_buffer )
		return;

	if ( __IDL__current_buffer )
		{
		/* Flush out information for old buffer. */
		*__IDL__c_buf_p = __IDL__hold_char;
		__IDL__current_buffer->__IDL__buf_pos = __IDL__c_buf_p;
		__IDL__current_buffer->__IDL__n_chars = __IDL__n_chars;
		}

	__IDL__current_buffer = new_buffer;
	__IDL__load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (__IDL_wrap()) processing, but the only time this flag
	 * is looked at is after __IDL_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	__IDL__did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void __IDL__load_buffer_state( void )
#else
void __IDL__load_buffer_state()
#endif
	{
	__IDL__n_chars = __IDL__current_buffer->__IDL__n_chars;
	__IDL_text_ptr = __IDL__c_buf_p = __IDL__current_buffer->__IDL__buf_pos;
	__IDL_in = __IDL__current_buffer->__IDL__input_file;
	__IDL__hold_char = *__IDL__c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE __IDL__create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) __IDL__flex_alloc( sizeof( struct __IDL__buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__create_buffer()" );

	b->__IDL__buf_size = size;

	/* __IDL__ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->__IDL__ch_buf = (char *) __IDL__flex_alloc( b->__IDL__buf_size + 2 );
	if ( ! b->__IDL__ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__create_buffer()" );

	b->__IDL__is_our_buffer = 1;

	__IDL__init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void __IDL__delete_buffer( YY_BUFFER_STATE b )
#else
void __IDL__delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == __IDL__current_buffer )
		__IDL__current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->__IDL__is_our_buffer )
		__IDL__flex_free( (void *) b->__IDL__ch_buf );

	__IDL__flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void __IDL__init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void __IDL__init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	__IDL__flush_buffer( b );

	b->__IDL__input_file = file;
	b->__IDL__fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->__IDL__is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->__IDL__is_interactive = 0;
#else
	b->__IDL__is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void __IDL__flush_buffer( YY_BUFFER_STATE b )
#else
void __IDL__flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->__IDL__n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->__IDL__ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->__IDL__ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->__IDL__buf_pos = &b->__IDL__ch_buf[0];

	b->__IDL__at_bol = 1;
	b->__IDL__buffer_status = YY_BUFFER_NEW;

	if ( b == __IDL__current_buffer )
		__IDL__load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__scan_buffer( char *base, __IDL__size_t size )
#else
YY_BUFFER_STATE __IDL__scan_buffer( base, size )
char *base;
__IDL__size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) __IDL__flex_alloc( sizeof( struct __IDL__buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__scan_buffer()" );

	b->__IDL__buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->__IDL__buf_pos = b->__IDL__ch_buf = base;
	b->__IDL__is_our_buffer = 0;
	b->__IDL__input_file = 0;
	b->__IDL__n_chars = b->__IDL__buf_size;
	b->__IDL__is_interactive = 0;
	b->__IDL__at_bol = 1;
	b->__IDL__fill_buffer = 0;
	b->__IDL__buffer_status = YY_BUFFER_NEW;

	__IDL__switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__scan_string( __IDL_const char *__IDL__str )
#else
YY_BUFFER_STATE __IDL__scan_string( __IDL__str )
__IDL_const char *__IDL__str;
#endif
	{
	int len;
	for ( len = 0; __IDL__str[len]; ++len )
		;

	return __IDL__scan_bytes( __IDL__str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE __IDL__scan_bytes( __IDL_const char *bytes, int len )
#else
YY_BUFFER_STATE __IDL__scan_bytes( bytes, len )
__IDL_const char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	__IDL__size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) __IDL__flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in __IDL__scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = __IDL__scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in __IDL__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->__IDL__is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void __IDL__push_state( int new_state )
#else
static void __IDL__push_state( new_state )
int new_state;
#endif
	{
	if ( __IDL__start_stack_ptr >= __IDL__start_stack_depth )
		{
		__IDL__size_t new_size;

		__IDL__start_stack_depth += YY_START_STACK_INCR;
		new_size = __IDL__start_stack_depth * sizeof( int );

		if ( ! __IDL__start_stack )
			__IDL__start_stack = (int *) __IDL__flex_alloc( new_size );

		else
			__IDL__start_stack = (int *) __IDL__flex_realloc(
					(void *) __IDL__start_stack, new_size );

		if ( ! __IDL__start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	__IDL__start_stack[__IDL__start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void __IDL__pop_state()
	{
	if ( --__IDL__start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(__IDL__start_stack[__IDL__start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int __IDL__top_state()
	{
	return __IDL__start_stack[__IDL__start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void __IDL__fatal_error( __IDL_const char msg[] )
#else
static void __IDL__fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine __IDL_less() so it works in section 3 code. */

#undef __IDL_less
#define __IDL_less(n) \
	do \
		{ \
		/* Undo effects of setting up __IDL_text. */ \
		__IDL_text[__IDL_leng] = __IDL__hold_char; \
		__IDL__c_buf_p = __IDL_text + n; \
		__IDL__hold_char = *__IDL__c_buf_p; \
		*__IDL__c_buf_p = '\0'; \
		__IDL_leng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef __IDL_text_ptr
#ifdef YY_USE_PROTOS
static void __IDL__flex_strncpy( char *s1, __IDL_const char *s2, int n )
#else
static void __IDL__flex_strncpy( s1, s2, n )
char *s1;
__IDL_const char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int __IDL__flex_strlen( __IDL_const char *s )
#else
static int __IDL__flex_strlen( s )
__IDL_const char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *__IDL__flex_alloc( __IDL__size_t size )
#else
static void *__IDL__flex_alloc( size )
__IDL__size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *__IDL__flex_realloc( void *ptr, __IDL__size_t size )
#else
static void *__IDL__flex_realloc( ptr, size )
void *ptr;
__IDL__size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void __IDL__flex_free( void *ptr )
#else
static void __IDL__flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	__IDL_lex();
	return 0;
	}
#endif
#line 378 "lexer.l"


void __IDL_lex_init (void)
{
	__IDL_inputcb = NULL;
	__IDL_cur_line = 1;
	__IDL_cur_token_line = 0;
	__IDL_prev_token_line = 0;
	__IDL_cur_filename = NULL;
	__IDL_cur_fileinfo = NULL;
	warn_underscores = 0;
}

void __IDL_lex_cleanup (void)
{
	__IDL_cur_filename = NULL;
#ifdef YY_NEW_FILE
	YY_NEW_FILE; /* obsolete with newer versions of flex */
#endif
}

int __IDL_wrap (void)
{
	return 1;
}

static int count_nl (const char *s)
{
	int i;

	for (i = 0;
	     (s = strchr (s, '\n')) != NULL;
	     ++s, ++i) ;

	return i;
}

/*
 * Local variables:
 * mode: C
 * c-basic-offset: 8
 * tab-width: 8
 * indent-tabs-mode: t
 * End:
 */
