# $Id: makefile,v 1.1.1.1 2003/05/21 13:35:28 pasha Exp $
#
#  JFS Makefile for the src directory.
#

allall: all

all dep clean:
    @cd jfs
    @echo Entering directory: .\src\jfs
    $(MAKE) /nologo $@
    @cd ..
    @echo Entering directory: .\src

