/*!
 * @file hpj.c
 * @brief HPJ (WinHelp project) output emitter for emxdoc.
 *
 * Emits an HPJ project file for the Microsoft Windows Help
 * Compiler (HC30.EXE).  HPJ is a small config file, not a document
 * format, so the emitter does not interpret normal document tags:
 * paragraphs, headings, lists and so on are all ignored except for
 * headings, which are collected for [MAP].
 *
 * The output consists of:
 *
 *   - a header comment;
 *   - [OPTIONS] with TITLE from %title;
 *   - [FILES] referring to <basename>.rtf, where <basename> is
 *     taken from the input file name;
 *   - [MAP] associating each visible heading's context string
 *     (topic_<ref>) with a numeric ID (0x1000+ref);
 *   - [WINDOWS] with a single default window.
 *
 * Additional sections ([ALIAS], [BUILDTAGS], ...) can be appended
 * by the author with %hpj ... %endhpj blocks.  The core writes
 * those lines verbatim, using the same raw-block mechanism as for
 * every other emitter.
 *
 * @copyright Copyright (C) 2026 osFree Project.
 *            License - see LICENSE in the project root.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "emxdoc.h"
#include "emitter.h"
#include "hpj.h"

/*!
 * @brief One entry of the [MAP] section.
 */
struct hpj_map
{
  int ref;                      /*!< Reference number. */
  struct hpj_map *next;         /*!< Next entry. */
};

/*! @brief Head of the [MAP] list. */
static struct hpj_map *hpj_maps = NULL;

/*! @brief Ref of the heading currently being emitted. */
static int hpj_ref;

/*! @brief Flags of the heading currently being emitted. */
static unsigned int hpj_flags;

/*!
 * @brief Extract the base name of a path, without directory and
 *        without extension.
 *
 * @param[out] dst  Destination buffer.  Not NULL.
 * @param[in]  size Size of @p dst in bytes.  Must be > 0.
 * @param[in]  src  Source path.  Not NULL.
 */
static void hpj_basename (char *dst, size_t size, const char *src)
{
  const char *slash1 = strrchr (src, '/');
  const char *slash2 = strrchr (src, '\\');
  const char *slash  = slash1;
  const char *dot;
  size_t n;

  if (slash2 != NULL && (slash == NULL || slash2 > slash))
    slash = slash2;

  src = (slash != NULL) ? slash + 1 : src;
  dot = strrchr (src, '.');
  n = (dot != NULL) ? (size_t)(dot - src) : strlen (src);
  if (n >= size)
    n = size - 1;
  memcpy (dst, src, n);
  dst[n] = 0;
}

/*!
 * @brief Add one entry to the [MAP] list.
 *
 * Duplicates (same ref) are ignored, so repeated passes over the
 * same heading do not produce duplicate lines.
 *
 * @param[in] ref Reference number of the heading.
 */
static void hpj_add_map (int ref)
{
  struct hpj_map *m;

  for (m = hpj_maps; m != NULL; m = m->next)
    if (m->ref == ref)
      return;

  m = xmalloc (sizeof (*m));
  m->ref = ref;
  m->next = hpj_maps;
  hpj_maps = m;
}

/*!
 * @brief Initializes HPJ output.
 *
 * Emits the header comment, [OPTIONS] and [FILES].  [MAP] and
 * [WINDOWS] are emitted later by hpj_end(), after all headings
 * have been seen.
 */
void hpj_start (void)
{
  char base[512];

  write_line ("; HPJ project file generated by emxdoc");
  write_line ("; Adjust as needed and compile with HC30.EXE");
  write_nl ();

  write_line ("[OPTIONS]");
  write_string ("TITLE=");
  if (title != NULL)
    write_string (title);
  else
    write_string ("Help");
  write_nl ();
  write_line ("COMPRESS=true");
  write_line ("WARNING=3");
  write_line ("REPORT=yes");
  write_nl ();

  hpj_basename (base, sizeof (base),
                input_fname != NULL ? input_fname : "help");

  write_line ("[FILES]");
  write_string (base);
  write_string (".rtf");
  write_nl ();
  write_nl ();

  hpj_maps = NULL;
  hpj_ref = 0;
  hpj_flags = 0;
}

/*!
 * @brief Finalizes HPJ output.
 *
 * Emits the [MAP] section from the collected headings, then the
 * fixed [WINDOWS] section.
 */
void hpj_end (void)
{
  struct hpj_map *m;

  if (hpj_maps != NULL)
    {
      write_line ("[MAP]");
      for (m = hpj_maps; m != NULL; m = m->next)
        {
          write_fmt ("topic_%d=0x%04x", m->ref, 0x1000 + m->ref);
          write_nl ();
        }
      write_nl ();
    }

  write_line ("[WINDOWS]");
  write_line ("main=0,0,1024,768,,,(r1)");
}

/*!
 * @brief Remember the ref and flags of the heading being started.
 *
 * @param[in] level  Heading level (unused).
 * @param[in] ref    Reference number of the heading.
 * @param[in] global Non-zero if the section is global (unused).
 * @param[in] flags  HF_* flags.
 */
void hpj_heading1 (int level, int ref, int global, unsigned int flags)
{
  (void)level;
  (void)global;
  hpj_ref = ref;
  hpj_flags = flags;
}

/*!
 * @brief Record the heading's context string in the [MAP] list.
 *
 * Hidden headings are not included, so that the [MAP] section only
 * lists topics that can actually be reached by context-sensitive
 * help.
 *
 * @param[in] s Heading text (unused; the context string is
 *              derived from the ref number).
 */
void hpj_heading2 (const uchar *s)
{
  (void)s;
  if (hpj_ref != 0 && !(hpj_flags & HF_HIDE))
    hpj_add_map (hpj_ref);
}
