#
# A Makefile for EMXDOC
# (c) osFree project,
# author, date
#

PROJ = emxdoc
TRGT = $(PROJ).exe
DESC = docs converter
srcfiles = $(p)emxdoc$(e) $(p)input$(e) $(p)cond$(e) $(p)html$(e) $(p)ipf$(e) $(p)latex$(e) $(p)text$(e) $(p)xref$(e) $(p)lb$(e)

!include $(%ROOT)tools/mk/tools.mk


