/*! @file man.c
 *  @brief man (roff) backend for emxdoc.
 *
 *  Emits a man page using plain roff macros (.TH, .SH, .SS, .TP,
 *  .IP, .RS/.RE, .nf/.fi).  Escapes backslash, hyphen, and a
 *  leading period or apostrophe.
 *
 *  @copyright Copyright (C) 2026 osFree Project.
 *             License — see LICENSE in the project root.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "emxdoc.h"
#include "man.h"

/*!
 *  @brief Emits a line with roff special characters escaped.
 *  @param[in] p Pointer to a zero-terminated string.
 */
static void man_escape (const uchar *p)
{
  int at_start = (output_x == 0);

  while (*p != 0)
    {
      uchar c = *p++;

      switch (c)
        {
        case '\\':
          write_string ("\\\\");
          break;
        case '-':
          write_string ("\\-");
          break;
        case '.':
        case '\'':
          if (at_start)
            write_string ("\\&");
          write_nstring (&c, 1);
          break;
        default:
          write_nstring (&c, 1);
          break;
        }
      at_start = 0;
    }
}

/*! @brief Opens highlighting according to hl_stack. */
void man_start_hilite (void)
{
  int hl = hl_stack[hl_sp];

  if (hl & HL_BF)                         write_string ("\\fB");
  else if (hl & HL_TT)                    write_string ("\\f(CW");
  else if (hl & (HL_SL | HL_EM | HL_UL))  write_string ("\\fI");
  else                                    write_string ("\\fP");
}

/*! @brief Closes highlighting according to hl_stack. */
void man_end_hilite (void)
{
  int hl = hl_stack[hl_sp - 1];

  if (hl & HL_BF)                         write_string ("\\fB");
  else if (hl & HL_TT)                    write_string ("\\f(CW");
  else if (hl & (HL_SL | HL_EM | HL_UL))  write_string ("\\fI");
  else                                    write_string ("\\fP");
}

/*!
 *  @brief Builds the man-page name from the input file name.
 *  @param[out] out   Receiver.  Not NULL.
 *  @param[in]  outsz Size of the buffer.
 */
static void man_th_name (char *out, size_t outsz)
{
  const char *base = input_fname ? input_fname : "DOC";
  const char *s = base + strlen (base);
  size_t n = 0;

  while (s > base && s[-1] != '/' && s[-1] != '\\')
    --s;
  while (s[n] != 0 && s[n] != '.' && n + 1 < outsz)
    {
      out[n] = (char)toupper ((unsigned char)s[n]);
      ++n;
    }
  out[n] = 0;
  if (n == 0)
    strcpy (out, "DOC");
}

/*! @brief Initializes man-page output and prints .TH. */
void man_start (void)
{
  char name[64];

  man_th_name (name, sizeof (name));
  write_string (".\\\" Generated by emxdoc (man backend)\n");
  write_fmt (".TH \"%s\" 1\n", name);
  write_string (".nh\n");
  write_string (".ad l\n");
}

/*! @brief Finalizes man-page output. */
void man_end (void)
{
}

/*!
 *  @brief Emits a text fragment with roff escaping.
 *  @param[in] p         Pointer to a zero-terminated string.
 *  @param[in] may_break Non-zero if a line break is allowed.
 */
void man_output (const uchar *p, int may_break)
{
  (void)may_break;
  man_escape (p);
}

/*! @brief Starts a section heading (.SH or .SS). */
void man_heading1 (void)
{
  if (output_x > 0)
    write_nl ();
  if (tg_level >= 2)
    write_string (".SS ");
  else
    write_string (".SH ");
}

/*!
 *  @brief Finishes a section heading.
 *  @param[in] s Heading text.
 */
void man_heading2 (uchar *s)
{
  man_escape (s);
  write_nl ();
}

/*!
 *  @brief Emits one TOC line.
 *  @param[in] s  Section number with alignment padding.
 *  @param[in] tp TOC node.  Not NULL.
 */
void man_toc_line (const uchar *s, const struct toc *tp)
{
  write_string (s);
  man_escape (tp->title);
  write_nl ();
}

/*! @brief Starts the description environment. */
void man_description (void)
{
  if (output_x > 0) write_nl ();
  write_string (".RS 6\n");
}

/*! @brief Starts the enumerate environment. */
void man_enumerate (void)
{
  if (output_x > 0) write_nl ();
  write_string (".RS 4\n");
}

/*! @brief Starts the itemize environment. */
void man_itemize (void)
{
  if (output_x > 0) write_nl ();
  write_string (".RS 4\n");
}

/*! @brief Starts the indent environment. */
void man_indent (void)
{
  if (output_x > 0) write_nl ();
  write_string (".RS 4\n");
}

/*! @brief Starts the list environment. */
void man_list (void)
{
  if (output_x > 0) write_nl ();
  write_string (".RS 6\n");
}

/*! @brief Closes the current environment. */
void man_end_env (void)
{
  switch (env_stack[env_sp].env)
    {
    case ENV_DESCRIPTION:
    case ENV_ENUMERATE:
    case ENV_ITEMIZE:
    case ENV_LIST:
    case ENV_INDENT:
    case ENV_TYPEWRITER:
      if (output_x > 0) write_nl ();
      write_string (".RE\n");
      break;
    default:
      break;
    }
}

/*!
 *  @brief Starts a description-list item.
 *  @param[in] s Term.
 */
void man_description_item (const uchar *s)
{
  if (output_x > 0) write_nl ();
  write_string (".TP\n");
  man_escape (s);
  write_nl ();
}

/*! @brief Starts an ordered-list item. */
void man_enumerate_item (void)
{
  int n = ++env_stack[env_sp].counter;

  if (output_x > 0) write_nl ();
  write_fmt (".IP \"%d.\" 4\n", n);
}

/*! @brief Starts an unordered-list item. */
void man_itemize_item (void)
{
  if (output_x > 0) write_nl ();
  write_string (".IP \\(bu 2\n");
}

/*!
 *  @brief Starts a description-list item (list environment).
 *  @param[in] s Term.
 */
void man_list_item (const uchar *s)
{
  if (output_x > 0) write_nl ();
  write_string (".TP\n");
  man_escape (s);
  write_nl ();
}

/*!
 *  @brief Starts a verbatim/example/samplecode block.
 *  @param[in]  tag_end  End tag of the block.
 *  @param[out] ptmargin Receiver of the current margin.  Not NULL.
 */
void man_verbatim_start (enum tag tag_end, int *ptmargin)
{
  (void)ptmargin;
  if (output_x > 0) write_nl ();
  if (tag_end == TAG_ENDSAMPLECODE)
    write_string (".PP\n\\fBExample:\\fP\n");
  write_string (".nf\n");
}

/*!
 *  @brief Emits one verbatim-block line.
 *  @param[in] tag_end End tag of the block.
 *  @param[in] tmargin Current margin.
 *  @param[in] compat  Compatibility string (unused).
 */
void man_verbatim_line (enum tag tag_end, int tmargin, uchar *compat)
{
  (void)tag_end; (void)tmargin; (void)compat;
  man_escape (input);
  write_nl ();
}

/*!
 *  @brief Finishes a verbatim/example/samplecode block.
 *  @param[in] tag_end End tag of the block.
 */
void man_verbatim_end (enum tag tag_end)
{
  (void)tag_end;
  if (output_x > 0) write_nl ();
  write_string (".fi\n");
  para_flag = TRUE;
}

/*!
 *  @brief Starts a prototype block.
 *  @param[in] compat Compatibility string (unused).
 */
void man_prototype_start (uchar *compat)
{
  (void)compat;
  if (output_x > 0) write_nl ();
  write_string (".nf\n");
}

/*! @brief Finishes a prototype block. */
void man_prototype_end (void)
{
  man_copy ();
  if (output_x > 0) write_nl ();
  write_string (".fi\n");
  para_flag = TRUE;
}

/*! @brief Emits the accumulated elements. */
void man_copy (void)
{
  enum style style_stack[STYLE_STACK_SIZE];
  int style_sp = 0;
  const struct element *ep;

  style_stack[0] = STYLE_NORMAL;
  for (ep = elements; ep->el != EL_END; ++ep)
    {
      switch (ep->el)
        {
        case EL_WORD:
        case EL_PUNCT:
          {
            enum style sty;

            if (style_sp == 0 || style_stack[style_sp] == STYLE_NORMAL)
              sty = (ep->wp->style != STYLE_NORMAL
                     ? ep->wp->style : STYLE_NORMAL);
            else
              sty = style_stack[style_sp];
            if (ep->wp->special != NULL && ep->wp->special->text != NULL)
              format_output (ep->wp->special->text, FALSE);
            else
              format_string (ep->wp->str, sty, FALSE);
          }
          break;

        case EL_SPACE:
          {
            int n;
            for (n = 0; n < ep->n; ++n)
              write_string (" ");
          }
          break;

        case EL_STYLE:
          if (style_sp + 1 >= STYLE_STACK_SIZE)
            fatal ("%s:%d: Style stack overflow", input_fname, line_no);
          style_stack[++style_sp] = (enum style)ep->n;
          break;

        case EL_ENDSTYLE:
          if (style_sp == 0)
            fatal ("%s:%d: Style stack underflow", input_fname, line_no);
          --style_sp;
          break;

        case EL_BREAK:
          if (ep->n) write_nl ();
          else       write_string (" ");
          break;

        default:
          abort ();
        }
    }
}

/*!
 *  @brief Emits the function-section heading.
 *  @param[in] tp TOC node.  Not NULL.
 */
void man_function (const struct toc *tp)
{
  if (output_x > 0) write_nl ();
  write_string (".SS ");
  man_escape (tp->title);
  write_nl ();
}

/*! @brief Starts the "See also" block. */
void man_see_also_start (void)
{
  if (output_x > 0) write_nl ();
  write_string (".SH SEE ALSO\n");
}

/*!
 *  @brief Finishes the "See also" block.
 *  @param[in] s Ready-made string with the link list.
 */
void man_see_also_end (const uchar *s)
{
  man_escape (s);
  write_nl ();
  para_flag = TRUE;
}

/*!
 *  @brief Emits the reference to a sample file.
 *  @param[in] s File name.
 */
void man_sample_file (const uchar *s)
{
  if (para_flag) write_nl ();
  write_string ("\\fBExample:\\fP See ");
  man_escape (s);
  write_nl ();
}

/*!
 *  @brief Emits a libref section heading.
 *  @param[in] s Section title.
 */
void man_libref_section (const uchar *s)
{
  if (output_x > 0) write_nl ();
  write_string (".PP\n\\fB");
  man_escape (s);
  write_string (":\\fP\n");
  para_flag = TRUE;
}
