#!/bin/sh

set -e

TMP_FILE=./file-list

for TMPDIR; do
   find debian/${TMPDIR}/* -type f ! -regex "^debian/${TMPDIR}/DEBIAN/.*" \
                                 ! -regex "^debian/${TMPDIR}/etc/.*" | \
                          sed s@debian/${TMPDIR}/@@g | sort > ${TMP_FILE}
   cd debian/${TMPDIR}
   xargs < ../../${TMP_FILE} md5sum > DEBIAN/md5sums
   cd ../../
   rm -f ${TMP_FILE}
   chown root.root debian/${TMPDIR}/DEBIAN/md5sums
done

