/* $Id: mmph.h,v 1.1 2000/04/21 10:58:00 ktk Exp $ */

/*
 *  dummy definitions form MMPH* macros
 */

#ifndef _mmph_h_
#define _mmph_h_



#define MMPHPostFS32_OPENCREATE()
#define MMPHPostFS32_READ()
#define MMPHPostFS32_READFAC()
#define MMPHPostFS32_RETURNFILECACHE()
#define MMPHPostFS32_WRITE()
#define MMPHPostIREAD_LOCK()
#define MMPHPostIREAD_UNLOCK()
#define MMPHPostIWRITE_LOCK()
#define MMPHPostIWRITE_LOCK_TRY()
#define MMPHPostIxWRITE_UNLOCK()
#define MMPHPostbmAssign()
#define MMPHPostbmLazyWrite()
#define MMPHPostbmRead()
#define MMPHPostbmWrite()
#define MMPHPostbmWrite()
#define MMPHPostcmAsyncWrite()
#define MMPHPostcmDeviceStartIO()
#define MMPHPostcmFlush()
#define MMPHPostcmGet()
#define MMPHPostcmGet()
#define MMPHPostcmGetE()
#define MMPHPostcmKickStart()
#define MMPHPostcmPut()
#define MMPHPostcmRead()
#define MMPHPostcmReadAhead()
#define MMPHPostcmReadWR()
#define MMPHPostcmWrite()
#define MMPHPostdtFind()
#define MMPHPostdtSearch()
#define MMPHPostdtSplitUp()
#define MMPHPostlbmStartIO()
#define MMPHPostncSearch()
#define MMPHPostreaddir()
#define MMPHPostsyncDaemon()
#define MMPHPosttxBegin()
#define MMPHPosttxCommit()
#define MMPHPosttxEnd()
#define MMPHPreFS32_OPENCREATE()
#define MMPHPreFS32_READ()
#define MMPHPreFS32_READFAC()
#define MMPHPreFS32_RETURNFILECACHE()
#define MMPHPreFS32_WRITE()
#define MMPHPreIREAD_LOCK(a)
#define MMPHPreIREAD_UNLOCK(a)
#define MMPHPreIWRITE_LOCK(a)
#define MMPHPreIWRITE_LOCK_TRY()
#define MMPHPreIWRITE_UNLOCK(a)
#define MMPHPrebmAssign()
#define MMPHPrebmLazyWrite()
#define MMPHPrebmRead()
#define MMPHPrebmWrite()
#define MMPHPrecmAsyncWrite()
#define MMPHPrecmDeviceStartIO()
#define MMPHPrecmFlush()
#define MMPHPrecmGet()
#define MMPHPrecmGetE()
#define MMPHPrecmKickStart()
#define MMPHPrecmPut()
#define MMPHPrecmRead()
#define MMPHPrecmReadAhead()
#define MMPHPrecmReadWR()
#define MMPHPrecmWrite()
#define MMPHPredtFind()
#define MMPHPredtSearch()
#define MMPHPredtSplitUp()
#define MMPHPrelbmStartIO()
#define MMPHPrencSearch()
#define MMPHPrereaddir()
#define MMPHPresyncDaemon()
#define MMPHPretxBegin()
#define MMPHPretxCommit()
#define MMPHPretxEnd()
#define MMPHdioStartIO()
#define MMPHphysIOReq()
#define MPHPostdioRead()
#define MPHPostdioWrite()
#define MPHPredioRead()
#define MPHPredioWrite()
#define MMPHPredioRead()
#define MMPHPostdioRead()
#define MMPHPredioWrite()
#define MMPHPostdioWrite()

#endif
