.TH ASSIGN 1 "08 August 1995"
.\"		$Id: assign.1 1.1 1995/08/10 11:47:50 ska Exp ska $
.\"    Assign a drive letter to a different drive
.\"    Copyright (C) 1995  Steffen Kaiser
.\"
.\"    This program is free software; you can redistribute it and/or modify
.\"    it under the terms of the GNU General Public License as published by
.\"    the Free Software Foundation; either version 2 of the License, or
.\"    (at your option) any later version.
.\"
.\"    This program is distributed in the hope that it will be useful,
.\"    but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"    GNU General Public License for more details.
.\"
.\"    You should have received a copy of the GNU General Public License
.\"    along with this program; if not, write to the Free Software
.\"    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.SH NAME
assign \- Assign a drive letter to a different drive

.SH SYNOPSIS
\fBassign\fP [/\fBm\fP] [/\fBshadow\fP] /\fB?\fP
.br
\fBassign\fP [/\fBm\fP] [/\fBshadow\fP] /\fBstatus\fP
.br
\fBassign\fP [/\fBm\fP] [/\fBshadow\fP] /\fBu\fP
.br
\fBassign\fP [/\fBm\fP] [/\fBshadow\fP] [{ \fBdr1\fP[:]=\fBdr2\fP[:] }]

.SH DESCRIPTION
\fIAssign\fP maps a drive letter to a different drive. This mapping
effects only the drive letter, but not the path, what makes
\fIAssign\fP different to \fISubst\fP, e.g.:
.br
With the current working paths "C:\FREEDOS" and "B:\TEMP" after the
commands "assign B=C" and "cd C:\", the path "B:" also points to
the directory "C:\".
.br
Whereas after the commands "subst B: ." and "cd C:\", the path "B:"
still points to "C:\FREEDOS".

Because this program is no TSR, do not load it via the "LOADHIGH" or the
"LH" command.
.SH OPTIONS
.IP \fB/?\fP 
Display a little help screen.
.IP \fB/SHADOW\fP
This option hides the resident portion of \fIAssign\fP from being
detected easily. That includes:
.br
1) The memory block containing the resident portion is marked as
a part of the system.
.br
2) The installation check interrupt returns "Not installed, but
not allowed to install" rather than "Installed" or "Not installed".
.br

If the resident portion is installed with this option, but subsequent
invokations are made without this option, a warning pops up, but
the action is performed.

The option may be abbreviated down to \fB/SH\fP.
.IP \fB/STATUS\fP
Display all assigned drive letters in the form:
.br
dr1: => dr2:
.br
where \fBdr1\fP is the assigned drive letter and \fBdr2\fP the 
drive, where dr1 points to.

If there is no assigment at all, no output will be displayed.

This option prevents the loading of the resident portion, if it
has not already been installed.

The option may be abbreviated down to \fB/S\fP.
.IP \fB/u\fP
Uninstall a previously installed \fIAssign\fP.
.IP "\fBdr1\fP[:]=\fBdr2\fP[:]"
This defines a drive letter assignment, where \fBdr1\fP shall
point to \fBdr2\fP. The colons ":" are optional. There are no
whitespaces allowed between the drive letters, the colons and
the equal sign '='.

If the resident portion is not already loaded, it will be loaded
without further notice.
.IP \fB/m\fP
Move the resident portion into the UMB area, if possible. This
option is ignored, when the resident portion is already installed.
.IP "no option"
If there is neither \fB/STATUS\fP nor \fB/u\fP nor an assignment
specified on the command line, all existing assignments are broken, so
that all letters point to themselfs in result.
.SH "KNOWN BUGS"
.IP \(bu
Because \fIAssign\fP is no TSR itself, a loading with one of the
commands "LOADHIGH" or "LH" may fail. If you want to load the
resident portion high, you must specify the \fB/m\fP option.
.IP \(bu
The options \fB/STATUS\fP and \fB/SHADOW\fP do not follow the
option standard because of compatibly to the original \fIAssign\fP.
.IP \(bu
Later installed TSR's or a secondary command processor (shell) mostly
prevent the uninstall process. In this case, \fIAssign\fP is not
suspended, but remains active in memory. Use \fBASSIGN\fP without
any option to clear the assignment table instead.
.IP \(bu
Some shells don't let
.ul
ASSIGN
find its resident copy.
.SH "SEE ALSO"
Subst, Join
.SH CONTRIBUTERS
    Steffen Kaiser
.br
Ernst-Th\("almann-Stra\("se 2
.br
     D-09126 Iden
.br
 Deutschland - Germany
