#
# A Makefile for ASSIGN
# (c) osFree project,
# author, date
#

PROJ      = assign
TRGT      = $(PROJ).com
DESC      = Assign
srcfiles  = $(p)asgn_tsr$(e) $(p)assign$(e)
COM       = 1

!include $(%ROOT)/mk/appsdos.mk

