# RegMath, math libraries for Regina
# Copyright 1998-2001 Patrick TJ McPhee
# Distributed under the terms of the Mozilla Public Licence
# You can obtain a copy of the licence at http://www.mozilla.org/MPL
# The Original Code is regmath
# The Initial Developer is Patrick TJ McPhee
# $Header: C:/ptjm/rexx/math/tmp/RCS/Makefile.doc 1.2 2001/11/04 19:06:24 ptjm Exp $

# this makefile produces the .pdf documentation. It requires pdflatex
# (v.14g or later), metapost, and ghostscript (v6.5 or later for best results)


# need to do this three times to get congruence
regmath.pdf : regmath.tex rat.pdf sincos.pdf exp.pdf
	-makeindex regmath
	pdflatex regmath
	makeindex regmath
	pdflatex regmath
	makeindex regmath
	pdflatex regmath

# note that the -g setting is taken from the bounding box of regmath.1 (i.e., may
# change on each run)
rat.pdf : regmath.1
	gs -sDEVICE=pdfwrite -sOutputFile=rat.pdf -r720 -g3060x830 -dNOPAUSE -dBATCH -- regmath.1

sincos.pdf : regmath.2
	gs -sDEVICE=pdfwrite -sOutputFile=sincos.pdf -r720 -g3860x1100 -dNOPAUSE -dBATCH -- regmath.2

exp.pdf : regmath.3
	gs -sDEVICE=pdfwrite -sOutputFile=exp.pdf -r720 -g2340x2250 -dNOPAUSE -dBATCH -- regmath.3

regmath.1 regmath.2 regmath.3 : regmath.mp
	mpost regmath

clean :
	-rm regmath.1 regmath.2 regmath.3 *.pdf *.log *.aux *.idx *.ilg *.ind *.toc regmath.out
