#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

srcfiles = $(p)windlgbox$(e)
ADD_COPT = -i=$(MYDIR).. -bd

!include $(%ROOT)/mk/appsos2_fpm.mk

DEST = none
TARGETS = $(OBJS)
