.TH RXQUEUE "1" "June 2013" "Regina Rexx Interpreter" "User Commands"

.SH NAME
rxqueue \- The Regina Rexx Interpreter external queue filter

.SH SYNOPSIS
.B rxqueue
[\fB\-h\fR, \fB\-\-help\fR] [\fB\-D\fR, \fB\-\-debug\fR]
[\fB\-t\fR string, \fB\-\-text\fR string] [queue] [/fifo | /lifo | /clear | /pull | /queued]

.SH DESCRIPTION
.B rxqueue
is a utility that provides access to the Regian Rexx external queue daemon (rxstack).
It acts as a filter by placing lines onto a queue
via
.I stdin
or a single line with the \fB\-t\fR or \fB\-\-text\fR switches. Lines can be pulled off the queue to
.I stdout
.

.SH OPTIONS
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Displays short help.
.TP
\fB\-D\fR, \fB\-\-debug\fR
Turns debugging on
\fB\-t\fR string, \fB\-\-text\fR string
Places the single line specified in
.I string
onto an optional queue in the order specified by
.I /fifo
or
.I /lifo
.TP
\fBqueue\fR
The name of the queue to use. Format is queuename[@machine][:port]. If not specified the queue name
used is SESSION on localhost using the default port.

.SH ACTIONS
.
.TP
\fB/fifo\fR
Stacks the contents of
.I stdin
onto the queue in first in, first out order.
.TP
\fB/lifo\fR
Stacks the contents of
.I stdin
onto the queue in last in, first out order.
.TP
\fB/clear\fR
Removes all lines currently stacked in the queue.
.TP
\fB/pull\fR
Extracts the next line from the queue to
.I stdout
and removes it from the queue.
.TP
\fB/queued\fR
Returns the number of lines stacked on the queue to
.I stdout
.
.SH ENVIRONMENT
\fBrxqueue\fR uses the following environment variables if set.

.IP RXDEBUG
Enables debugging. Same as specifying \-D or \-\-debug option.

.IP RXSTACK
The port number on which \fBrxstack\fR listens. By default this is \fI5757\fR.

.IP RXQUEUE
The name of the queue to be used if not specified by the client using rxqueue.
By default this is \fISESSION\fR.

.SH COPYRIGHT
The Regina Rexx interpreter is distributed under the GNU Library
General Public License, see the file `COPYING-LIB' in the source code
distribution.

.SH AUTHOR
Anders Christensen, University of Trondheim, Norway
<anders (at) pvv.unit.no>.

.SH MAINTAINER
Changes to Regina since 0.07a, Mark Hessling
<mark (at) rexx.org>
with significant assistance from Florian Grosse-Coosmann.

.SH SEE ALSO
.BR rxstack (1)

There are several good reference books on Rexx. The most famous is
"The Rexx Language" by Mike Cowlishaw.
Visit http://www.rexxla.org (The Rexx Language Association) for any Rexx
related information.

