#  Makefile for pmshell
#
#  valerius Mar 24 '2012

PROJ = pmshell
TRGT = $(PROJ).exe
DESC = PM/WPS starter program
srcfiles = $(p)pmshell$(e)

ADD_COPT     = -i=. -bm -od -mf -sg -d2 -mf
# ADD_LINKOPT  = lib os2386.lib lib clib3r.lib
UNI2H        = 1

!include $(%ROOT)/mk/appsos2_pm.mk

#TARGETS = subdirs $(PATH)$(PROJ).exe
#TARGET  = all
