#####################################################################
#
#  makefile for mdidemo
#
#  Copyright (c) 1995, Willows Software Inc.  All rights reserved.
#
#####################################################################

include $(TWINDIR)/Makefile.config

project		= mdidemo
components	= mdidemo.o mdidemo.res.o 
libraries	= 
linklibs	= -lshell$(TWIN_APISIZE)
resource	= mdidemo
resource_depend	= willows.ico

include $(TWINDIR)/makeinclude/makefile$(TWIN_APISIZE).inc

#####################################################################
# user makefile definitions for libraries are placed below
#####################################################################

clean-libs:
