#
# A Makefile for APPEND
# (c) osFree project,
# author, date
#

PROJ      = append
TRGT      = $(PROJ).com
DESC      = Binary comparison of files
srcfiles  = $(p)segs$(e) $(p)environ$(e) $(p)cmdline$(e) $(p)int2f$(e) $(p)int21$(e) $(p)append$(e)
COM       = 1

!include $(%ROOT)/mk/appsdos.mk
