#
# A Makefile for BIND
# (c) osFree project,
# author, date
#

PROJ = loader
TRGT = $(PROJ).exe
DESC = Binded Familty API loader
#defines object file names in format $(p)objname$(e)
srcfiles = $(p)loader$(e) $(p)ginterf$(e) $(p)file$(e) $(p)strings$(e) #$(p)imptable$(e)
# defines additional options for C compiler
#ADD_COPT = -i=$(%WATCOM)$(SEP)h$(SEP)os21x


!include $(%ROOT)tools/mk/appsdos.mk
