/*!
 *  @file ytab.h
 *  @brief Token definitions and semantic value type for the awk grammar.
 *
 *  Generated by yacc from awkgram.y. Defines the YYSTYPE semantic
 *  value union, the external yylval variable and every token
 *  number used by the parser and the lexer. Do not edit by hand:
 *  the file is regenerated whenever awkgram.y changes.
 *
 *  @copyright Copyright (C) Lucent Technologies 1997.
 */

/*!
 *  @brief Semantic value union passed between the lexer and the parser.
 */
typedef union  {
	Node	*p;   /*!< Node pointer. */
	Cell	*cp;  /*!< Cell pointer. */
	int	i;    /*!< Integer value. */
	char	*s;   /*!< String value. */
}	YYSTYPE;

/*!< Current semantic value returned by the lexer. */
extern	YYSTYPE	yylval;

/*!
 *  @brief First token of the grammar.
 *  @def FIRSTTOKEN
 */
#define	FIRSTTOKEN	57346
/*!
 *  @brief Token PROGRAM.
 *  @def PROGRAM
 */
#define	PROGRAM	57347
/*!
 *  @brief Token PASTAT.
 *  @def PASTAT
 */
#define	PASTAT	57348
/*!
 *  @brief Token PASTAT2.
 *  @def PASTAT2
 */
#define	PASTAT2	57349
/*!
 *  @brief Token XBEGIN.
 *  @def XBEGIN
 */
#define	XBEGIN	57350
/*!
 *  @brief Token XEND.
 *  @def XEND
 */
#define	XEND	57351
/*!
 *  @brief Token NL (newline).
 *  @def NL
 */
#define	NL	57352
/*!
 *  @brief Token ARRAY.
 *  @def ARRAY
 */
#define	ARRAY	57353
/*!
 *  @brief Token MATCH.
 *  @def MATCH
 */
#define	MATCH	57354
/*!
 *  @brief Token NOTMATCH.
 *  @def NOTMATCH
 */
#define	NOTMATCH	57355
/*!
 *  @brief Token MATCHOP.
 *  @def MATCHOP
 */
#define	MATCHOP	57356
/*!
 *  @brief Token FINAL.
 *  @def FINAL
 */
#define	FINAL	57357
/*!
 *  @brief Token DOT.
 *  @def DOT
 */
#define	DOT	57358
/*!
 *  @brief Token ALL.
 *  @def ALL
 */
#define	ALL	57359
/*!
 *  @brief Token CCL (character class).
 *  @def CCL
 */
#define	CCL	57360
/*!
 *  @brief Token NCCL (negated character class).
 *  @def NCCL
 */
#define	NCCL	57361
/*!
 *  @brief Token CHAR.
 *  @def CHAR
 */
#define	CHAR	57362
/*!
 *  @brief Token OR.
 *  @def OR
 */
#define	OR	57363
/*!
 *  @brief Token STAR.
 *  @def STAR
 */
#define	STAR	57364
/*!
 *  @brief Token QUEST.
 *  @def QUEST
 */
#define	QUEST	57365
/*!
 *  @brief Token PLUS.
 *  @def PLUS
 */
#define	PLUS	57366
/*!
 *  @brief Token AND.
 *  @def AND
 */
#define	AND	57367
/*!
 *  @brief Token BOR.
 *  @def BOR
 */
#define	BOR	57368
/*!
 *  @brief Token APPEND.
 *  @def APPEND
 */
#define	APPEND	57369
/*!
 *  @brief Token EQ.
 *  @def EQ
 */
#define	EQ	57370
/*!
 *  @brief Token GE.
 *  @def GE
 */
#define	GE	57371
/*!
 *  @brief Token GT.
 *  @def GT
 */
#define	GT	57372
/*!
 *  @brief Token LE.
 *  @def LE
 */
#define	LE	57373
/*!
 *  @brief Token LT.
 *  @def LT
 */
#define	LT	57374
/*!
 *  @brief Token NE.
 *  @def NE
 */
#define	NE	57375
/*!
 *  @brief Token IN.
 *  @def IN
 */
#define	IN	57376
/*!
 *  @brief Token ARG.
 *  @def ARG
 */
#define	ARG	57377
/*!
 *  @brief Token BLTIN (built-in function).
 *  @def BLTIN
 */
#define	BLTIN	57378
/*!
 *  @brief Token BREAK.
 *  @def BREAK
 */
#define	BREAK	57379
/*!
 *  @brief Token CLOSE.
 *  @def CLOSE
 */
#define	CLOSE	57380
/*!
 *  @brief Token CONTINUE.
 *  @def CONTINUE
 */
#define	CONTINUE	57381
/*!
 *  @brief Token DELETE.
 *  @def DELETE
 */
#define	DELETE	57382
/*!
 *  @brief Token DO.
 *  @def DO
 */
#define	DO	57383
/*!
 *  @brief Token EXIT.
 *  @def EXIT
 */
#define	EXIT	57384
/*!
 *  @brief Token FOR.
 *  @def FOR
 */
#define	FOR	57385
/*!
 *  @brief Token FUNC.
 *  @def FUNC
 */
#define	FUNC	57386
/*!
 *  @brief Token SUB.
 *  @def SUB
 */
#define	SUB	57387
/*!
 *  @brief Token GSUB.
 *  @def GSUB
 */
#define	GSUB	57388
/*!
 *  @brief Token IF.
 *  @def IF
 */
#define	IF	57389
/*!
 *  @brief Token INDEX.
 *  @def INDEX
 */
#define	INDEX	57390
/*!
 *  @brief Token LSUBSTR.
 *  @def LSUBSTR
 */
#define	LSUBSTR	57391
/*!
 *  @brief Token MATCHFCN.
 *  @def MATCHFCN
 */
#define	MATCHFCN	57392
/*!
 *  @brief Token NEXT.
 *  @def NEXT
 */
#define	NEXT	57393
/*!
 *  @brief Token NEXTFILE.
 *  @def NEXTFILE
 */
#define	NEXTFILE	57394
/*!
 *  @brief Token ADD.
 *  @def ADD
 */
#define	ADD	57395
/*!
 *  @brief Token MINUS.
 *  @def MINUS
 */
#define	MINUS	57396
/*!
 *  @brief Token MULT.
 *  @def MULT
 */
#define	MULT	57397
/*!
 *  @brief Token DIVIDE.
 *  @def DIVIDE
 */
#define	DIVIDE	57398
/*!
 *  @brief Token MOD.
 *  @def MOD
 */
#define	MOD	57399
/*!
 *  @brief Token ASSIGN.
 *  @def ASSIGN
 */
#define	ASSIGN	57400
/*!
 *  @brief Token ASGNOP (assignment operator).
 *  @def ASGNOP
 */
#define	ASGNOP	57401
/*!
 *  @brief Token ADDEQ.
 *  @def ADDEQ
 */
#define	ADDEQ	57402
/*!
 *  @brief Token SUBEQ.
 *  @def SUBEQ
 */
#define	SUBEQ	57403
/*!
 *  @brief Token MULTEQ.
 *  @def MULTEQ
 */
#define	MULTEQ	57404
/*!
 *  @brief Token DIVEQ.
 *  @def DIVEQ
 */
#define	DIVEQ	57405
/*!
 *  @brief Token MODEQ.
 *  @def MODEQ
 */
#define	MODEQ	57406
/*!
 *  @brief Token POWEQ.
 *  @def POWEQ
 */
#define	POWEQ	57407
/*!
 *  @brief Token PRINT.
 *  @def PRINT
 */
#define	PRINT	57408
/*!
 *  @brief Token PRINTF.
 *  @def PRINTF
 */
#define	PRINTF	57409
/*!
 *  @brief Token SPRINTF.
 *  @def SPRINTF
 */
#define	SPRINTF	57410
/*!
 *  @brief Token ELSE.
 *  @def ELSE
 */
#define	ELSE	57411
/*!
 *  @brief Token INTEST.
 *  @def INTEST
 */
#define	INTEST	57412
/*!
 *  @brief Token CONDEXPR.
 *  @def CONDEXPR
 */
#define	CONDEXPR	57413
/*!
 *  @brief Token POSTINCR.
 *  @def POSTINCR
 */
#define	POSTINCR	57414
/*!
 *  @brief Token PREINCR.
 *  @def PREINCR
 */
#define	PREINCR	57415
/*!
 *  @brief Token POSTDECR.
 *  @def POSTDECR
 */
#define	POSTDECR	57416
/*!
 *  @brief Token PREDECR.
 *  @def PREDECR
 */
#define	PREDECR	57417
/*!
 *  @brief Token VAR.
 *  @def VAR
 */
#define	VAR	57418
/*!
 *  @brief Token IVAR (indirect variable).
 *  @def IVAR
 */
#define	IVAR	57419
/*!
 *  @brief Token VARNF.
 *  @def VARNF
 */
#define	VARNF	57420
/*!
 *  @brief Token CALL.
 *  @def CALL
 */
#define	CALL	57421
/*!
 *  @brief Token NUMBER.
 *  @def NUMBER
 */
#define	NUMBER	57422
/*!
 *  @brief Token STRING.
 *  @def STRING
 */
#define	STRING	57423
/*!
 *  @brief Token REGEXPR.
 *  @def REGEXPR
 */
#define	REGEXPR	57424
/*!
 *  @brief Token GETLINE.
 *  @def GETLINE
 */
#define	GETLINE	57425
/*!
 *  @brief Token RETURN.
 *  @def RETURN
 */
#define	RETURN	57426
/*!
 *  @brief Token SPLIT.
 *  @def SPLIT
 */
#define	SPLIT	57427
/*!
 *  @brief Token SUBSTR.
 *  @def SUBSTR
 */
#define	SUBSTR	57428
/*!
 *  @brief Token WHILE.
 *  @def WHILE
 */
#define	WHILE	57429
/*!
 *  @brief Token CAT (concatenation).
 *  @def CAT
 */
#define	CAT	57430
/*!
 *  @brief Token NOT.
 *  @def NOT
 */
#define	NOT	57431
/*!
 *  @brief Token UMINUS (unary minus).
 *  @def UMINUS
 */
#define	UMINUS	57432
/*!
 *  @brief Token POWER.
 *  @def POWER
 */
#define	POWER	57433
/*!
 *  @brief Token DECR.
 *  @def DECR
 */
#define	DECR	57434
/*!
 *  @brief Token INCR.
 *  @def INCR
 */
#define	INCR	57435
/*!
 *  @brief Token INDIRECT.
 *  @def INDIRECT
 */
#define	INDIRECT	57436
/*!
 *  @brief Last token of the grammar.
 *  @def LASTTOKEN
 */
#define	LASTTOKEN	57437
