#
# A Makefile for mkmsgf
# (c) osFree project,
# valerius, 2006/10/30
#
# $Id: makefile,v 1.1 2004/08/16 06:27:30 prokushev Exp $
#

PROJ = mapsym
TRGT = $(PROJ).exe
DESC = .SYM file generator from Watcom MAP files

!include $(%ROOT)/mk/toolspas.mk
