#
# A Makefile for mkmsgf
# (c) osFree project,
# valerius, 2006/10/30
#
# $Id: makefile,v 1.1 2004/08/16 06:27:30 prokushev Exp $
#

TARGET_CLASS = APPLICATION
TARGET_LANG = pascal
TARGET_API = HOST
TARGET_BITS = 32

!include $(%ROOT)tools/mk/build.mk
