#include "dog.idl"

    interface LittleDog : Dog
    {
#ifdef __SOMIDL__
      implementation {
         //# Class Modifiers
         functionprefix = littledog_;
         callstyle      = oidl;
         dllname        = "animals.dll";

         //# Method Modifiers
         talk: override;
      };
#endif /* __SOMIDL__ */
    };
