  KbdSetCustXt                .201, &
  KbdGetCp                    .203, &
  KbdCharIn                   .204, &
  KbdSetCp                    .205, &
  KbdSynch                    .207, &
  KbdRegister                 .208, &
  KbdStringIn                 .209, &
  KbdGetStatus                .210, &
  KbdSetStatus                .211, &
  KbdGetFocus                 .212, &
  KbdFlushBuffer              .213, &
  KbdXlate                    .214, &
  KbdClose                    .217, &
  KbdFreeFocus                .218, &
  KbdDeRegister               .220, &
  KbdSetFgnd                  .221, &
  KbdPeek                     .222, &
  KbdOpen                     .223, &
  KbdGetHWID                  .224, &
  KbdSetHWID                  .225, &
