  MouGetPtrShape              .301, &
  MouSetPtrShape              .302, &
  MouGetNumMickeys            .303, &
  MouGetScaleFact             .306, &
  MouFlushQue                 .307, &
  MouGetNumButtons            .308, &
  MouClose                    .309, &
  MouSetScaleFact             .311, &
  MouGetNumQueEl              .313, &
  MouDeRegister               .314, &
  MouGetEventMask             .315, &
  MouSetEventMask             .316, &
  MouOpen                     .317, &
  MouRemovePtr                .318, &
  MouGetPtrPos                .319, &
  MouReadEventQue             .320, &
  MouSetPtrPos                .321, &
  MouGetDevStatus             .322, &
  MouSynch                    .323, &
  MouRegister                 .324, &
  MouSetDevStatus             .325, &
  MouDrawPtr                  .326, &
  MouInitReal                 .327, &
  MouSetThreshold             .329, &
  MouGetThreshold             .330, &
