  WinDefAVioWindowProc        .30, &
  VioEndPopUp                 .101, &
  VioGetPhysBuf               .102, &
  VioGetAnsi                  .103, &
  VioSetAnsi                  .105, &
  VioDeRegister               .106, &
  VioScrollUp                 .107, &
  VioPrtSc                    .108, &
  VioGetCurPos                .109, &
  VioWrtCellStr               .110, &
  VioPopUp                    .111, &
  VioScrollRt                 .112, &
  VioWrtCharStr               .113, &
  VioSetCurPos                .115, &
  VioScrUnLock                .118, &
  VioWrtTTY                   .119, &
  VioGetMode                  .121, &
  VioSetMode                  .122, &
  VioScrLock                  .123, &
  VioReadCellStr              .124, &
  VioSavRedrawWait            .125, &
  VioWrtNAttr                 .126, &
  VioGetCurType               .127, &
  VioSavRedrawUndo            .128, &
  VioGetFont                  .129, &
  VioReadCharStr              .130, &
  VioGetBuf                   .131, &
  VioSetCurType               .132, &
  VioSetFont                  .133, &
  VioModeUndo                 .135, &
  VioModeWait                 .137, &
  VioGetCp                    .140, &
  VioSetCp                    .142, &
  VioShowBuf                  .143, &
  VioScrollLf                 .144, &
  VioRegister                 .145, &
  VioGetConfig                .146, &
  VioScrollDn                 .147, &
  VioWrtCharStrAtt            .148, &
  VioGetState                 .149, &
  VioPrtScToggle              .150, &
  VioSetState                 .151, &
  VioWrtNCell                 .152, &
  VioWrtNChar                 .153, &
  VioAssociate                .155, &
  VioCreatePS                 .156, &
  VioDeleteSetId              .157, &
  VioGetDeviceCellSize        .158, &
  VioGetOrg                   .159, &
  VioCreateLogFont            .160, &
  VioDestroyPS                .161, &
  VioQuerySetIds              .162, &
  VioSetOrg                   .163, &
  VioQueryFonts               .164, &
  VioSetDeviceCellSize        .165, &
  VioShowPS                   .166, &
  VioGlobalReg                .170, &
  VioCheckCharType            .175, &
