/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef constdef_idl
#define constdef_idl
#include <containd.idl>

#ifdef __PRIVATE__
interface M_ConstantDef : M_Contained
{
#ifdef __SOMIDL__
	implementation
	{
		callstyle = idl;
		majorversion = 2;
		minorversion = 1;
		dllname = "somir.dll";
#ifdef __PRIVATE__
	#ifdef SOMRefObject
		somUninit : override;
	#else
		somDefaultInit: override;
		somDestruct : override;
	#endif
		functionprefix = m_constdef_;
#endif
	};
#endif
};
#endif

interface ConstantDef :	Contained
{
	struct ConstantDescription
	{
		Identifier name;
		RepositoryId id;
		RepositoryId defined_in;
		TypeCode type;
		any value;
	};
	attribute TypeCode type;
	attribute any value;

#ifdef __SOMIDL__
	#ifdef __PRIVATE__
	enum enum_t { enum_t_origin }; 
	#endif
	implementation
	{
#ifdef __PRIVATE__
		type : nodata;
		value : nodata;
#endif
		_set_type : caller_owns_parameters="type";
		_set_value : caller_owns_parameters="value";
		_get_type: dual_owned_result;
		_get_value: dual_owned_result;
		releaseorder : 
			_get_type,
			_set_type,
			_get_value,
			_set_value;
		callstyle = idl;
		majorversion = 2;
		minorversion = 1;
		filestem = constdef;
		dllname = "somir.dll";
#ifdef __PRIVATE__
		somInit : override;
	#ifdef SOMRefObject
		somUninit : override;
	#else
		somDestruct: override;
	#endif
		somDumpSelf : override;
		somDumpSelfInt : override;
		functionprefix = "constdef_";
		metaclass=M_ConstantDef;
#endif
	};
#endif /* __SOMIDL__ */
};

#endif /* constdef_idl */
