/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef paramdef_idl
#define paramdef_idl
#include <containd.idl>

#ifdef __PRIVATE__
interface M_ParameterDef : M_Contained
{
#ifdef __SOMIDL__
	implementation
	{
		callstyle = idl;
		majorversion = 2;
		minorversion = 1;
		dllname = "somir.dll";
#ifdef __PRIVATE__
	#ifdef SOMRefObject
		somUninit : override;
	#else
		somDefaultInit: override;
		somDestruct : override;
	#endif
		functionprefix = m_paramdef_;
#endif
	};
#endif
};
#endif

interface ParameterDef :
	Contained
{
	enum ParameterMode {IN,OUT,INOUT};

	struct ParameterDescription
	{
		Identifier name;
		RepositoryId id;
		RepositoryId defined_in;
		TypeCode type;
		ParameterMode mode;
	};
	attribute TypeCode type;
	attribute ParameterMode mode;
#ifdef __SOMIDL__
	implementation
	{
#ifdef __PRIVATE__
		type : nodata;
		mode : nodata;
#endif
		_set_type : caller_owns_parameters="type";
		_get_type: dual_owned_result;
		releaseorder : 
			_get_type,
			_set_type,
			_get_mode,
			_set_mode;
		callstyle = idl;
		majorversion = 2;
		minorversion = 1;
		filestem = paramdef;
		dllname = "somir.dll";
#ifdef __PRIVATE__
		override:
	#ifdef SOMRefObject
				somUninit,
	#else
				somDefaultInit,
				somDestruct,
	#endif
				somDumpSelf,
				somDumpSelfInt;
		functionprefix = "paramdef_";
		metaclass=M_ParameterDef;
#endif
	};
#endif /* __SOMIDL__ */
};

#endif /* paramdef_idl */
