#
# A Makefile for SETCOM40
# (c) osFree project,
# author, date
#

PROJ      = setcom40
TRGT      = $(PROJ).com
DESC      = Setup communication ports
srcfiles  = $(p)setcom40$(e)
COM       = 1

!include $(%ROOT)/mk/appsdos.mk

