
DEST = os2tk45$(SEP)som$(SEP)include

!include $(%ROOT)SOM/common.mk


TARGETS =	$(PATH)somobj.xh &
		$(PATH)somcls.xh &
		$(PATH)somcm.xh &
	 	$(PATH)attribdf.xh &
		$(PATH)constdef.xh &
		$(PATH)containd.xh &
		$(PATH)containr.xh &
		$(PATH)excptdef.xh &
		$(PATH)intfacdf.xh &
		$(PATH)moduledf.xh &
		$(PATH)operatdf.xh &
		$(PATH)paramdef.xh &
		$(PATH)repostry.xh &
		$(PATH)typedef.xh &
		$(PATH)boa.xh &
		$(PATH)cntxt.xh &
		$(PATH)impldef.xh &
		$(PATH)implrep.xh &
		$(PATH)nvlist.xh &
		$(PATH)om.xh &
		$(PATH)orb.xh &
		$(PATH)poa.xh &
		$(PATH)principl.xh &
		$(PATH)request.xh &
		$(PATH)rhborbst.xh &
		$(PATH)rhbtypes.xh &
		$(PATH)servmgr.xh &
		$(PATH)servreq.xh &
		$(PATH)somdcprx.xh &
		$(PATH)somdfenc.xh &
		$(PATH)somdmprx.xh &
		$(PATH)somdobj.xh &
		$(PATH)somdom.xh &
		$(PATH)somdserv.xh &
		$(PATH)somdstub.xh &
		$(PATH)somdtcdt.xh &
		$(PATH)somdtype.xh &
		$(PATH)somoa.xh &
		$(PATH)stexcep.xh &
		$(PATH)unotypes.xh &
		$(PATH)clientev.xh &
		$(PATH)eman.xh &
		$(PATH)emregdat.xh &
		$(PATH)event.xh &
		$(PATH)sinkev.xh &
		$(PATH)timerev.xh &
		$(PATH)workprev.xh &
		$(PATH)defedidl.xh &
		$(PATH)eda.xh &
		$(PATH)fma.xh &
		$(PATH)fmi.xh &
		$(PATH)fmib.xh &
		$(PATH)fsagm.xh &
		$(PATH)fsgm.xh &
		$(PATH)iogma.xh &
		$(PATH)iogrp.xh &
		$(PATH)mia.xh &
		$(PATH)nsma.xh &
		$(PATH)objset.xh &
		$(PATH)pid.xh &
		$(PATH)po.xh &
		$(PATH)poid.xh &
		$(PATH)poida.xh &
		$(PATH)psma.xh &
		$(PATH)somp.xh &
		$(PATH)somperr.xh &
		$(PATH)somperrd.xh &
		$(PATH)sompstad.xh &
		$(PATH)sompstat.xh &
		$(PATH)srkset.xh &
		$(PATH)snglicls.xh &
		$(PATH)sombacls.xh &
		$(PATH)somida.xh &
		$(PATH)somproxy.xh &
		$(PATH)somsid.xh &
		$(PATH)scattrib.xh &
		$(PATH)scbase.xh &
		$(PATH)scclass.xh &
		$(PATH)sccommon.xh &
		$(PATH)scconst.xh &
		$(PATH)scdata.xh &
		$(PATH)scemit.xh &
		$(PATH)scentry.xh &
		$(PATH)scenum.xh &
		$(PATH)scenumnm.xh &
		$(PATH)scmeta.xh &
		$(PATH)scmethod.xh &
		$(PATH)scmodule.xh &
		$(PATH)scparm.xh &
		$(PATH)scpass.xh &
		$(PATH)scseqnce.xh &
		$(PATH)scstring.xh &
		$(PATH)scstruct.xh &
		$(PATH)sctdef.xh &
		$(PATH)sctmplt.xh &
		$(PATH)scunion.xh &
		$(PATH)scusrtyp.xh &
		$(PATH)somstrt.xh &
		$(PATH)somssock.xh &
		$(PATH)tcpsock.xh &
		$(PATH)omgestio.xh &
		$(PATH)somestio.xh &
		$(PATH)biter.xh &
		$(PATH)lname.xh &
		$(PATH)lnamec.xh &
		$(PATH)naming.xh &
		$(PATH)xnaming.xh &
		$(PATH)xnamingf.xh &
		$(PATH)omgidobj.xh &
		$(PATH)somref.xh &
		$(PATH)somap.xh &
		$(PATH)somos.xh &
		$(PATH)xmscssae.xh &
		$(PATH)somtdm.xh


$(PATH)attribdf.xh: $(DEST)$(SEP)attribdf.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)constdef.xh: $(DEST)$(SEP)constdef.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)containd.xh: $(DEST)$(SEP)containd.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)containr.xh: $(DEST)$(SEP)containr.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)excptdef.xh: $(DEST)$(SEP)excptdef.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)intfacdf.xh: $(DEST)$(SEP)intfacdf.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)moduledf.xh: $(DEST)$(SEP)moduledf.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)operatdf.xh: $(DEST)$(SEP)operatdf.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)paramdef.xh: $(DEST)$(SEP)paramdef.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)repostry.xh: $(DEST)$(SEP)repostry.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)typedef.xh: $(DEST)$(SEP)typedef.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)boa.xh: $(DEST)$(SEP)boa.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)cntxt.xh: $(DEST)$(SEP)cntxt.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)impldef.xh: $(DEST)$(SEP)impldef.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)implrep.xh: $(DEST)$(SEP)implrep.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)nvlist.xh: $(DEST)$(SEP)nvlist.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)om.xh: $(DEST)$(SEP)om.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)orb.xh: $(DEST)$(SEP)orb.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)poa.xh: $(DEST)$(SEP)poa.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)principl.xh: $(DEST)$(SEP)principl.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)request.xh: $(DEST)$(SEP)request.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)rhborbst.xh: $(DEST)$(SEP)rhborbst.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)rhbtypes.xh: $(DEST)$(SEP)rhbtypes.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)servmgr.xh: $(DEST)$(SEP)servmgr.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)servreq.xh: $(DEST)$(SEP)servreq.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdcprx.xh: $(DEST)$(SEP)somdcprx.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdfenc.xh: $(DEST)$(SEP)somdfenc.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdmprx.xh: $(DEST)$(SEP)somdmprx.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdobj.xh: $(DEST)$(SEP)somdobj.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdom.xh: $(DEST)$(SEP)somdom.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdserv.xh: $(DEST)$(SEP)somdserv.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdstub.xh: $(DEST)$(SEP)somdstub.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdtcdt.xh: $(DEST)$(SEP)somdtcdt.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somdtype.xh: $(DEST)$(SEP)somdtype.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somoa.xh: $(DEST)$(SEP)somoa.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)stexcep.xh: $(DEST)$(SEP)stexcep.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)unotypes.xh: $(DEST)$(SEP)unotypes.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)clientev.xh: $(DEST)$(SEP)clientev.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)eman.xh: $(DEST)$(SEP)eman.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)emregdat.xh: $(DEST)$(SEP)emregdat.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)event.xh: $(DEST)$(SEP)event.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sinkev.xh: $(DEST)$(SEP)sinkev.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)timerev.xh: $(DEST)$(SEP)timerev.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)workprev.xh: $(DEST)$(SEP)workprev.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)defedidl.xh: $(DEST)$(SEP)defedidl.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)eda.xh: $(DEST)$(SEP)eda.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fma.xh: $(DEST)$(SEP)fma.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fmi.xh: $(DEST)$(SEP)fmi.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fmib.xh: $(DEST)$(SEP)fmib.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fsagm.xh: $(DEST)$(SEP)fsagm.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)fsgm.xh: $(DEST)$(SEP)fsgm.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)iogma.xh: $(DEST)$(SEP)iogma.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)iogrp.xh: $(DEST)$(SEP)iogrp.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)mia.xh: $(DEST)$(SEP)mia.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)nsma.xh: $(DEST)$(SEP)nsma.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)objset.xh: $(DEST)$(SEP)objset.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)pid.xh: $(DEST)$(SEP)pid.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)po.xh: $(DEST)$(SEP)po.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)poid.xh: $(DEST)$(SEP)poid.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)poida.xh: $(DEST)$(SEP)poida.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)psma.xh: $(DEST)$(SEP)psma.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somp.xh: $(DEST)$(SEP)somp.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somperr.xh: $(DEST)$(SEP)somperr.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somperrd.xh: $(DEST)$(SEP)somperrd.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sompstad.xh: $(DEST)$(SEP)sompstad.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sompstat.xh: $(DEST)$(SEP)sompstat.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)srkset.xh: $(DEST)$(SEP)srkset.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)snglicls.xh: $(DEST)$(SEP)snglicls.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sombacls.xh: $(DEST)$(SEP)sombacls.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somida.xh: $(DEST)$(SEP)somida.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somproxy.xh: $(DEST)$(SEP)somproxy.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somsid.xh: $(DEST)$(SEP)somsid.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scattrib.xh: $(DEST)$(SEP)scattrib.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scbase.xh: $(DEST)$(SEP)scbase.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scclass.xh: $(DEST)$(SEP)scclass.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sccommon.xh: $(DEST)$(SEP)sccommon.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scconst.xh: $(DEST)$(SEP)scconst.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scdata.xh: $(DEST)$(SEP)scdata.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scemit.xh: $(DEST)$(SEP)scemit.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scentry.xh: $(DEST)$(SEP)scentry.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scenum.xh: $(DEST)$(SEP)scenum.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scenumnm.xh: $(DEST)$(SEP)scenumnm.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scmeta.xh: $(DEST)$(SEP)scmeta.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scmethod.xh: $(DEST)$(SEP)scmethod.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scmodule.xh: $(DEST)$(SEP)scmodule.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scparm.xh: $(DEST)$(SEP)scparm.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scpass.xh: $(DEST)$(SEP)scpass.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scseqnce.xh: $(DEST)$(SEP)scseqnce.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scstring.xh: $(DEST)$(SEP)scstring.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scstruct.xh: $(DEST)$(SEP)scstruct.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sctdef.xh: $(DEST)$(SEP)sctdef.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)sctmplt.xh: $(DEST)$(SEP)sctmplt.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scunion.xh: $(DEST)$(SEP)scunion.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)scusrtyp.xh: $(DEST)$(SEP)scusrtyp.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somstrt.xh: $(DEST)$(SEP)somstrt.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somssock.xh: $(DEST)$(SEP)somssock.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)tcpsock.xh: $(DEST)$(SEP)tcpsock.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)omgestio.xh: $(DEST)$(SEP)omgestio.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somestio.xh: $(DEST)$(SEP)somestio.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)biter.xh: $(DEST)$(SEP)biter.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)lname.xh: $(DEST)$(SEP)lname.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)lnamec.xh: $(DEST)$(SEP)lnamec.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)naming.xh: $(DEST)$(SEP)naming.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)xnaming.xh: $(DEST)$(SEP)xnaming.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)xnamingf.xh: $(DEST)$(SEP)xnamingf.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)omgidobj.xh: $(DEST)$(SEP)omgidobj.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)corba.xh: $(DEST)$(SEP)corba.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somref.xh: $(DEST)$(SEP)somref.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somap.xh: $(DEST)$(SEP)somap.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somos.xh: $(DEST)$(SEP)somos.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)xmscssae.xh: $(DEST)$(SEP)xmscssae.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somtdm.xh: $(DEST)$(SEP)somtdm.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somobj.xh: $(DEST)$(SEP)somobj.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somcls.xh: $(DEST)$(SEP)somcls.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

$(PATH)somcm.xh: $(DEST)$(SEP)somcm.idl
 $(verbose)sc -sxh -I $(DEST) -v $< -o $(PATH) $(BLACKHOLE)

