/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id: cntxt.idl 3914 2013-01-18 22:11:38Z rogerb $
 */

#ifndef cntxt_idl
#define cntxt_idl
#include <somobj.idl>
#include <somdtype.idl>
#include <containd.idl>
interface NVList;
interface Context :
	SOMObject
{
	ORBStatus set_one_value(in Identifier prop_name,in string value);
	ORBStatus set_values(in NVList values);
	ORBStatus get_values(in Identifier start_scope,in Flags op_flags,in Identifier prop_name,out NVList values);
	ORBStatus delete_values(in Identifier prop_name);
	ORBStatus create_child(in Identifier ctx_name,out Context child_ctx);
	ORBStatus destroy(in Flags flags);
	attribute string context_name;
	attribute Context context_parent;
#ifdef __SOMIDL__
	implementation
	{
		releaseorder : 
			set_one_value,
			set_values,
			get_values,
			delete_values,
			create_child,
			destroy,
			_get_context_name,
			_set_context_name,
			_get_context_parent,
			_set_context_parent,
			private10,
			private11;
		callstyle = idl;
		dllname = "somd.dll";
		majorversion = 2;
		minorversion = 2;
		#define CNTXT_IDL_COMMON_H_PASSTHU \
			"#define CTX_DELETE_DESCENDENTS      0x00000200" \
			"#define CTX_RESTRICT_SCOPE          0x00000400" \
			"#ifndef Context_delete"						 \
			"#define Context_delete Context_destroy"		 \
			"#endif"										 \
			""

		passthru C_xh_after=CNTXT_IDL_COMMON_H_PASSTHU;
		passthru C_h_after=CNTXT_IDL_COMMON_H_PASSTHU;

	};
#endif /* __SOMIDL__ */
};
#endif /* cntxt_idl */
