#ifndef LnkEmitter_idl
#define LnkEmitter_idl

#include <scemit.idl>

interface LnkEmitter : SOMTEmitC
{
#ifdef __SOMIDL__
  implementation {

    //# Class Modifiers
    callstyle = oidl;

    //# Method Modifiers
    somtGenerateSections: override;
  };
#endif /* __SOMIDL__ */
};

#endif  /* LnkEmitter_idl */
