/**************************************************************************
 *
 *  Copyright 2015, 2017, 2018, Yuri Prokushev
 *
 *  This file is part of osFree project
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

#ifndef scmodule_idl
#define scmodule_idl

#include <scentry.idl>

interface SOMTStructEntryC;
interface SOMTTypedefEntryC;
interface SOMTUnionEntryC;
interface SOMTEnumEntryC;
interface SOMTConstEntryC;
interface SOMTSequenceEntryC;
interface SOMTClassEntryC;

interface SOMTModuleEntryC : SOMTEntryC
{
  readonly attribute SOMTModuleEntryC somtOuterModule;
  /* The module enclosing this module, or NULL if there is none. */

  readonly attribute string somtModuleFile;
  /* The name of the file in which the module appears. */

  SOMTStructEntryC somtGetFirstModuleStruct ();
  SOMTStructEntryC somtGetNextModuleStruct ();
  SOMTTypedefEntryC somtGetFirstModuleTypedef ();
  SOMTTypedefEntryC somtGetNextModuleTypedef ();
  SOMTUnionEntryC somtGetFirstModuleUnion ();
  SOMTUnionEntryC somtGetNextModuleUnion ();
  SOMTEnumEntryC somtGetFirstModuleEnum ();
  SOMTEnumEntryC somtGetNextModuleEnum ();
  SOMTConstEntryC somtGetFirstModuleConstant ();
  SOMTConstEntryC somtGetNextModuleConstant ();
  SOMTSequenceEntryC somtGetFirstModuleSequence ();
  SOMTSequenceEntryC somtGetNextModuleSequence ();
  SOMTClassEntryC somtGetFirstInterface ();
  SOMTClassEntryC somtGetNextInterface ();
  SOMTModuleEntryC somtGetFirstModule ();
  SOMTModuleEntryC somtGetNextModule ();
  SOMTEntryC somtGetFirstModuleDef ();
  SOMTEntryC somtGetNextModuleDef ();

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_somtOuterModule, somtGetFirstModuleStruct, 
                  somtGetNextModuleStruct, somtGetFirstModuleTypedef, 
                  somtGetNextModuleTypedef, somtGetFirstModuleUnion, 
                  somtGetNextModuleUnion, somtGetFirstModuleEnum, 
                  somtGetNextModuleEnum, somtGetFirstModuleConstant, 
                  somtGetNextModuleConstant, somtGetFirstModuleSequence, 
                  somtGetNextModuleSequence, somtGetFirstInterface, 
                  somtGetNextInterface, somtGetFirstModule, 
                  somtGetNextModule, somtGetFirstModuleDef, 
		  somtGetNextModuleDef, _get_somtModuleFile;

    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = scmodule;
#ifdef _WIN32
    dllname = "some.dll";
#endif
    callstyle = oidl;
  
    //# Method Modifiers
    //somDumpSelfInt: override;
    //somtSetSymbolsOnEntry: override;
  
    //# Attribute Modifiers
    somtOuterModule: nodata;
    somtModuleFile: nodata;

  };
#endif /* __SOMIDL__ */
};


#endif  /* scmodule_idl */
