//
//   COMPONENT_NAME: some
//
//   ORIGINS: 27
//
//
//    25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1994,1996 
//   All Rights Reserved
//   Licensed Materials - Property of IBM
//   US Government Users Restricted Rights - Use, duplication or
//   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//
//#  @(#) somc/scparm.idl 2.9 5/9/96 15:31:20 [12/22/96 21:12:10]


#ifndef scparm_idl
#define scparm_idl

#include <sccommon.idl>
enum somtParameterDirectionT {somtInE, somtOutE,somtInOutE};
interface SOMTParameterEntryC : SOMTCommonEntryC
{
  readonly attribute somtParameterDirectionT somtParameterDirection;
  // The direction for this parameter. (somtInE, somtOutE, or somtInOutE).

  readonly attribute string somtIDLParameterDeclaration;
  // The IDL declaration of the parameter, including the type and name.

  readonly attribute string somtCParameterDeclaration;
  // The declaration for the parameter within a C method procedure prototype.
  // It includes the parameter's type and name.
  // This may differ from the parameter's IDL declaration.
  // In particular, pointer stars may be added.

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_somtParameterDirection, _get_somtCParameterDeclaration,
		_get_somtIDLParameterDeclaration;
  
    passthru C_h = "typedef enum somtParameterDirectionT {somtInE,somtOutE,somtInOutE} somtParameterDirectionT;";
    passthru C_xh = "typedef enum somtParameterDirectionT {somtInE,somtOutE,somtInOutE} somtParameterDirectionT;";

    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = scparm;
#ifdef _WIN32
    dllname = "some.dll";
#endif
    callstyle = oidl;
  
    //# Method Modifiers
    somtSetSymbolsOnEntry: override;
    somDumpSelfInt: override;
  
    //# Attribute modifiers
    somtParameterDirection: nodata;
    somtCParameterDeclaration: nodata;
    somtIDLParameterDeclaration: nodata;
  };
#endif /* __SOMIDL__ */
};


#endif  /* scparm_idl */
