//
//   COMPONENT_NAME: some
//
//   ORIGINS: 27
//
//
//    25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1994,1996 
//   All Rights Reserved
//   Licensed Materials - Property of IBM
//   US Government Users Restricted Rights - Use, duplication or
//   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//
//#  @(#) somc/scstring.idl 2.8 5/9/96 15:31:26 [12/22/96 21:12:12]


#ifndef scstring_idl
#define scstring_idl

#include <scentry.idl>

interface SOMTStringEntryC : SOMTEntryC
{
  readonly attribute long somtStringLength;
  // The length of the string.
#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_somtStringLength;
  
    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = scstring;
#ifdef _WIN32
    dllname = "some.dll";
#endif
    callstyle = oidl;
  
    //# Method Modifiers
    somDumpSelfInt: override;
    somtSetSymbolsOnEntry: override;
  
    //# Attribute Modifiers
    somtStringLength: nodata;
  };
#endif /* __SOMIDL__ */
};


#endif  /* scstring*/
