/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id: somida.idl 3938 2013-01-18 22:12:25Z rogerb $
 */

#ifndef somida_idl
#define somida_idl
#include <somobj.idl>
interface SOMUTId;
interface SOMUTId :
	SOMObject
{
	void somutSetIdId(
		in SOMUTId otherId);
	boolean somutEqualsId(
		in SOMUTId otherId);
	short somutCompareId(
		in SOMUTId otherId);
	unsigned long somutHashId();
#ifdef __SOMIDL__
	implementation
	{
		callstyle = idl;
		releaseorder : 
			somutSetIdId,
			somutEqualsId,
			somutCompareId,
			somutHashId;
		filestem = somida;
		majorversion = 2;
		minorversion = 1;
		dllname = "somu.dll";
	};
#endif /* __SOMIDL__ */
};
#endif /* somida_idl */
