/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id: somoa.idl 3914 2013-01-18 22:11:38Z rogerb $
 */

#ifndef somoa_idl
#define somoa_idl
#include <somdtype.idl>
#include <unotypes.idl>
#include <boa.idl>
interface SOMOA;


interface SOMDServer;

interface SOMOA : BOA
{
	ORBStatus execute_next_request(in Flags waitFlag);
	ORBStatus execute_request_loop(in Flags waitFlag);
	void change_id(in SOMDObject objref,in ReferenceData id);
	SOMDObject create_constant(in ReferenceData id,in InterfaceDef intf,in ImplementationDef impl);
	SOMDObject create_SOM_ref(in SOMObject somobj,in ImplementationDef impl);
	SOMObject get_SOM_object(in SOMDObject somref);
	void activate_impl_failed(in ImplementationDef impl,in ORBStatus rc);
	void interrupt_server();
	IIOP::SOMDServiceContextList get_service_contexts(in SOMDObject obj);
#ifdef __SOMIDL__
	implementation
	{
		releaseorder : 
			execute_next_request,
			execute_request_loop,
			create_constant,
			change_id,
			create_SOM_ref,
			get_SOM_object,
			activate_impl_failed,
			interrupt_server,
			private8,
			get_service_contexts,
			private10,
			private11,
			_get_default_SOMDServer,
			_set_default_SOMDServer,
			interrupt_server_status,
			notify_somdd;
		callstyle = idl;
		dllname = "somd.dll";
		majorversion = 2;
		minorversion = 2;

    #define SOMOA_IDL_COMMON_PASSTHRU \
		"" \
		"#define SOMD_WAIT					1" \
		"#define SOMD_NO_WAIT				0" \
		"#define SOMD_IMPL_NOT_INITIALIZED	0" \
		"#define SOMD_IMPL_NOT_ACTIVE		1" \
		"#define SOMD_IMPL_ACTIVE			2" \
		""

    passthru C_h_after=SOMOA_IDL_COMMON_PASSTHRU
      "";

    passthru C_xh_after=SOMOA_IDL_COMMON_PASSTHRU
      "";

	};
#endif /* __SOMIDL__ */
};
#endif /* somoa_idl */
