#
# A main Makefile for OS/3 boot sequence project
# (c) osFree project,
# valerius, 2006/10/30
#

# First directory must be UNI which produces C/C++ header files
DIRS = Shared CMD CPI PM MM SOM REXX # UtlAPI #Server

!include $(%ROOT)/mk/all.mk

TARGETS = subdirs
TARGET = all
