#
# A main Makefile for osFree OS/2 Personality
# (c) osFree project,
# valerius, 2006/10/30
#

# First directory must be UNI which produces C/C++ header files
DIRS = Shared CMD REXX CPI # UtlAPI PM MM SOM #Server

!include $(%ROOT)/mk/all.mk

TARGETS = subdirs
TARGET = all
