#
# A Makefile for iswindow
# (c) osFree project,
# author, date
#

PROJ      = ISWINDOW
TRGT      = $(PROJ).com
DESC      = Is windowed session?
srcfiles  = $(p)iswindow$(e)
COM       = 1

!include $(%ROOT)/mk/appsdos.mk

