#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

#srcfiles = $(p)rectangles$(e)
ADD_COPT = -i=$(MYDIR)..$(SEP)include -bd

!include $(%ROOT)/mk/appsos2_fpm.mk

DEST = none
TARGETS = $(OBJS)
TARGET = all
