#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ = attrib
DESC = Changes file attributes
#defines object file names in format objname.$(O)
srcfiles = $(p)attrib$(e)
# defines additional options for C compiler
ADD_COPT = -i=..$(SEP)include
STUB=$(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)$(PROJ).exe

!include $(%ROOT)/mk/appsos2.mk
