/**************************************************************************
 *
 *  Copyright 2015, 2017, 2018, Yuri Prokushev
 *
 *  This file is part of osFree project
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */


#ifndef scattrib_idl
#define scattrib_idl

interface SOMTDataEntryC;
interface SOMTMethodEntryC;

#include <scentry.idl>
interface SOMTAttributeEntryC : SOMTEntryC
{
readonly attribute boolean somtIsReadonly;
// Whether the attribute is readonly.

readonly attribute SOMTEntryC somtAttribType;
// The type of the attribute.  This does not include pointer stars
// or array declarators.  To get the "full" type, get each attribute
// declarator and get the somtType attribute.

SOMTDataEntryC somtGetFirstAttributeDeclarator();
// The first attribute declarator for this attribute declaration.
SOMTDataEntryC somtGetNextAttributeDeclarator();
// The next attribute declarator for this attribute declaration,
// relative to the previous call to this method or 
// somtGetFirstAttributeDeclarator.

SOMTMethodEntryC somtGetFirstGetMethod();
// The first get method for this attribute declaration.
SOMTMethodEntryC somtGetNextGetMethod();
// The next get method for this attribute declaration,
// relative to the previous call to this method or 
// somtGetFirstGetMethod.

SOMTMethodEntryC somtGetFirstSetMethod();
// The first set method for this attribute declaration.
SOMTMethodEntryC somtGetNextSetMethod();
// The next set method for this attribute declaration,
// relative to the previous call to this method or 
// somtGetFirstSetMethod.

#ifdef __SOMIDL__
  implementation {
    releaseorder: _get_somtIsReadonly, _get_somtAttribType, 
                  somtGetFirstAttributeDeclarator, 
		  somtGetNextAttributeDeclarator, 
                  somtGetFirstGetMethod, somtGetNextGetMethod, 
                  somtGetFirstSetMethod, somtGetNextSetMethod;


    //# Class Modifiers
    filestem = scattrib;
    dllname = "some.dll";
    callstyle = oidl;
    majorversion = 2;
    minorversion = 1;
  
    //# Method Modifiers
    somtSetSymbolsOnEntry: override;
    //somDumpSelfInt: override;
  
    //# Attribute Modifiers
    somtIsReadonly: nodata;
    somtAttribType: nodata;

  };
#endif /* __SOMIDL__ */
};


#endif  /* scattrib_idl */
