#
# Makefile for OS/3 loader bootsector.
# 06/10/03 valerius
#

DIRS = bs1 bs2 bs3

!include $(%ROOT)/mk/loader.mk

# this implies do $(MAKE) $(MAKEOPT) TARGET=all subdirs
TARGETS      = subdirs
TARGET       = all
