# $Id: makefile,v 1.1 2000/04/21 10:57:52 ktk Exp $
#
#  JFS Makefile for the src/jfs directory.
#

allall: all

all dep clean:
    @cd ifs
    @echo Entering directory: .\src\jfs\ifs
    $(MAKE) /nologo $@
    @cd ..\utils
    @echo Entering directory: .\src\jfs\utils
    $(MAKE) /nologo $@
    cd ..
    @echo Entering directory: .\src\jfs

