#
# A main Makefile for OS/3 boot sequence project
# (c) osFree project,
# valerius, 2006/10/30
#

# First directory must be UNI which produces C/C++ header files

DIRS = samples programs lzexpand

!include $(%ROOT)/mk/all.mk

TARGETS=subdirs
TARGET=all
