# Generated automatically from Makefile.config.in by configure.

#
# Makefile.config
#
# Bootstrap the makefile CONFIGURATION variables
#
# TWINDIR		where is the source tree
# TARGET		what OS are we running on 
# TWINCPU		what CPU are we running on
# TWINOPT		Debug or Release configuration
# TWIN_APISIZE		16 or 32 bits
# TWINLIB		where are libraries installed
# TWINBIN		where are executables installed

TWINDIR=/home/robf/src/twin/3.1.1
TARGET=linux

TWINCPU=X386

#
# TWINOPT=Debug   implies debugging information included
#        =Release implies full optimization
# TWIN_APISIZE=   implies 16bit library
#             =32 implies 32bit library:w!
#
#
TWINOPT=Debug
TWIN_APISIZE=

#TWINLIB=/home/robf/src/twin/3.1.1/$(TWINOPT)/lib
#TWINBIN=/home/robf/src/twin/3.1.1/$(TWINOPT)/bin
TWINLIB=$(TWINDIR)/$(TWINOPT)/lib
TWINBIN=$(TWINDIR)/$(TWINOPT)/bin

#
# Now load the makefile MAKEFILE variables
#

#include /home/robf/src/twin/3.1.1/makeinclude/Makefile.rules
include $(TWINDIR)/makeinclude/Makefile.rules
