#
# A Makefile for DEBUG
# (c) osFree project,
# author, date
#

PROJ      = comp
TRGT      = $(PROJ).com
DESC      = Binary comparison of files
#defines object file names in format objname.$(O)
srcfiles  = $(p)comp$(e)
COM = 1

!include $(%ROOT)/mk/appsdos.mk

$(PATH)comp.exe: .symbolic
