#
#
#

PROJ    = somc
TRGT    = $(PROJ).msg
DEST    = os2tk45$(SEP)som$(SEP)msg

!include $(%ROOT)tools/mk/appsos2.mk

TARGETS =  $(PATH)$(PROJ).msg $(PATH)$(PROJ).pl $(PATH)$(PROJ).ru

$(PATH)$(PROJ).msg:

$(PATH)$(PROJ).pl:

$(PATH)$(PROJ).ru:

$(PATH)$(PROJ).rsf: .always
 @$(MAKE) $(MAKEOPT) T=$^. rsf

