#
# A Makefile for LOGO.LGO
# (c) osFree project,
# author, date
#

PROJ        = country
srcfiles    = $(p)os2country$(e)
JWASM       = 1
RAW         = 1
NOLIBS      = 1
DEST        = os2

ADD_LINKOPT = DISABLE 1080

!include $(%ROOT)tools/mk/appsdos.mk

