#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ = label
TRGT = $(PROJ).exe
DESC = Change volume label
#defines object file names in format objname.$(O)
srcfiles = $(p)label$(e) #$(p)tcc2wat$(e)
# defines additional options for C compiler

!include $(%ROOT)/mk/appsdos.mk
