/* -*- c -*- */ 
import <l4/sys/types.h>
import <l4/l4vfs/types.h>

import <l4/l4vfs/common_io_notify.idl>

library l4vfs_term_server
{
    /* This interface describes the functions provided
     * by the term server for internal use only.
     */
    [uuid(62)]
    interface internal
    {
        /** Start read operation.        
         * 
         * This function is used to provide information
         * about a read operation to a worker thread. The
         * thread then starts this read and finishes by
         * sending the result back via the public read_notify()
         * function.
         *
         * /param fd       a local object handle
         * /param count    the number of bytes to read
         * /param mode     the rw mode flags
         * /param notifier the thread responsible for notifying
         *                 the client after work has been done
         * /param source   the client that initiated the request
         */
        [oneway]
        void start_read([in] object_handle_t fd,
                        [in] l4vfs_size_t *count,
                        [in] l4_threadid_t notifier,
                        [in] l4_threadid_t source);
    };
};
