#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

srcfiles = $(p)windowmgr$(e) $(p)WindowClass$(e)
ADD_COPT = -i=$(MYDIR)..$(SEP)include
DEST = none

!include $(%ROOT)/mk/appsos2.mk

TARGETS = $(OBJS)
