#
# A Makefile for pmmerge.dll
# (c) osFree project,
# author, date
#

srcfiles = $(p)WindowClass$(e) $(p)windowmgr$(e)
ADD_COPT = -i=..$(SEP)include
DEST =

!include $(%ROOT)/mk/appsos2.mk

TARGETS = $(OBJS)
