PROJ = spdx-lint
TRGT = $(PROJ).exe
DESC = SDPX lincense scanner
srcfiles = $(p)spdx-lint$(e)

ADD_COPT = -i=..$(SEP)include
ADD_LINKOPT = lib reuse_parser.lib, spdx.lib

!include $(%ROOT)tools/mk/tools.mk
