PROJ = spdx-lint
TRGT = $(PROJ).exe
#DESC = Sed language interpreter
srcfiles = $(p)spdx-lint$(e)

ADD_COPT = -i=..$(SEP)include
ADD_LINKOPT = lib reuse_parser.lib

!include $(%ROOT)tools/mk/tools.mk
