#
# A Makefile for freeinst
# (c) osFree project,
# valerius, 2010/07/14
#
# $Id: makefile,v 1.1 2004/08/16 06:27:30 prokushev Exp $
#

PROJ  = freeinst
DESC  = FreeLDR installer by Yoda
!include $(%ROOT)/mk/toolspas.mk
