#####################################################################
#
#  makefile for hlpdemo
#
#  Copyright (c) 1995, Willows Software Inc.  All rights reserved.
#
#####################################################################

include $(TWINDIR)/Makefile.config

project       = hyperoid
components    = hyperoid.o roidsupp.o hyperoid.res.o
resource      = hyperoid
 
include $(TWINDIR)/makeinclude/makefile.inc
 
clean-libs:
