# $Id: makefile.1 189 2001-04-12 00:09:06Z skaus $
#

all :

clobber : clean
	$(RM) $(RMFLAGS) *.exe *.com *.icd default.mk lastmake.mk *.cfg

clean :
	$(RM) $(RMFLAGS) *.lst *.map *.bin *.bak *.las *.obj $(CFG) *.dmp

