# $Id: makefile.1,v 1.3 2001/04/12 00:09:06 skaus Exp $
#

all :

clobber : clean
	$(RM) $(RMFLAGS) *.exe *.com *.icd default.mk lastmake.mk *.cfg

clean :
	$(RM) $(RMFLAGS) *.lst *.map *.bin *.bak *.las *.obj $(CFG) *.dmp

