#
# A Makefile for PM API DLLs
# (c) osFree project,
#

DIRS = shared PMMERGE PMDRAG PMWIN PMMLE PMSHAPI PMGRE OS2SM PMGPI
#       PMPIC PMSHLTKT PMSPL PMPRE &
#       PMVIOP PMWINX REGISTRY
#PMATM PMUNIF PMCLIP PMCTLS PMDDE PMDDEML PMGPI &

!include $(%ROOT)tools/mk/all.mk

#TARGETS = subdirs
#TARGET = all
