#
# A main Makefile for osFree OS/2 Personality BiDirectional National Language Support
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = bdcalls

!include $(%ROOT)/mk/all.mk

TARGETS = subdirs
TARGET = all
