# $Id: makefile,v 1.3 2004/08/21 14:49:03 prokushev Exp $
#

PROJ      = reuse_parser
ADD_COPT  = -i=$(MYDIR)..$(SEP)..$(SEP)include
TARGET_CLASS = LIBRARY
TARGET_SUBCLASS = STATIC
TARGET_API = HOST
TARGET_BITS = 32

!include $(%ROOT)tools/mk/build.mk
