# tools/shared/reuse/makefile
# $Id: makefile,v 1.3 2004/08/21 14:49:03 prokushev Exp $
#

ADD_COPT  = -i=$(MYDIR)..$(SEP)..$(SEP)include
TARGET_CLASS = LIBRARY
LIBS = dep5 toml git path omf res ccl git spdx ccl
!include $(%ROOT)tools/mk/build.mk
