#
# A Makefile for STUB
# (c) osFree project,
# author, date
#

PROJ = os2stub
TRGT = $(PROJ).exe
DESC = DOS Stub for OS/2 executables
#defines object file names in format objname.$(O)
srcfiles = $(p)stub$(e)
# defines additional options for C compiler

DEST = os2$(SEP)mdos

!include $(%ROOT)/mk/appsdos.mk
