#
# A Makefile for STUB
# (c) osFree project,
# author, date
#

PROJ = os2stub
DESC = DOS Stub for OS/2 executables
#defines object file names in format objname.$(O)
srcfiles = $(p)stub$(e)
# defines additional options for C compiler

!include $(%ROOT)/mk/dosapp.mk
