/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef sombacls_idl
#define sombacls_idl
#include <somobj.idl>
#include <somcls.idl>

interface SOMMBeforeAfter :
	SOMClass
{
	boolean sommBeforeMethod(
		in SOMObject object,
		in somId methodId,
		in va_list ap);
	void sommAfterMethod(
		in SOMObject object,
		in somId methodId,
		in somToken returnedvalue,
		in va_list ap);
#ifdef __SOMIDL__
	implementation
	{
#ifdef __PRIVATE__
		sequence<somMethodData> jump_table;
#endif
		releaseorder : sommBeforeMethod,sommAfterMethod;
		majorversion = 2;
		minorversion = 2;
		filestem = sombacls;
		callstyle = idl;
		dllname = "somu.dll";
#ifdef __PRIVATE__
		override : somClassReady,somUninit,somInit;
		functionprefix=sombacls_;
#endif
	};
#endif /* __SOMIDL__ */
};
#endif /* sombacls_idl */
