/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef somproxy_idl
#define somproxy_idl
#include <somcls.idl>
#ifdef __PRIVATE__
#include <somref.idl>
#endif

interface SOMMProxyFor : SOMClass
{
	SOMClass sommMakeProxyClass(
		in SOMClass targetClass,
		in string className);
#ifdef __SOMIDL__
	implementation
	{
		releaseorder : sommMakeProxyClass;
		callstyle = oidl;
		dllname = "somu.dll";
#ifdef __PRIVATE__
		functionprefix = "somproxyClass_";
#endif
	};
#endif /* __SOMIDL__ */
};

interface SOMMProxyForObject : 
#ifdef __PRIVATE__
	SOMRefObject
#else
	SOMObject
#endif
{
	attribute SOMObject sommProxyTarget;
	struct sommProxyDispatchInfo
	{
		somMethodData md;
		somMethodPtr dispatchFcn;
	};
	boolean sommProxyDispatch(
		out somToken returnBufferPointer,
		in sommProxyDispatchInfo dispatchInfo,
		in va_list ap);

#ifdef __SOMIDL__
	implementation
	{
		releaseorder : 
			_get_sommProxyTarget,
			_set_sommProxyTarget,
			sommProxyDispatch;
		callstyle = oidl;
		metaclass = SOMMProxyFor;
		dllname = "somu.dll";
#ifdef __PRIVATE__
		functionprefix = "somproxy_";
#endif
	};
#endif /* __SOMIDL__ */
};
#endif /* somproxy_idl */
