.SUFFIXES: .obj
CC=gcc
CFLAGS=-O2 -Zomf
#CFLAGS=-Wall -g -DDEBUG -Zomf
LIBS= -lm -los2me
INCLUDES= -Ilibvorbis-1.0rc2/include -Ilibogg-1.0rc2/include
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(CFLAGS)

all: mmiovorb.dll
                                                                 
.c.obj:
	$(COMPILE) -c $<

*.obj: mmiovorbis.h

mmioVorb.dll: mmioVorbis.obj 
	$(CC) $(CFLAGS) -Zdll -Zcrtdll $(LDFLAGS) $(INCLUDES) $^ libvorbis-1.0rc2/lib/*.obj libogg-1.0rc2/src/*.obj mmiovorbis.def -o mmiovorb.dll $(LIBS)

mmioVorbis.exe: main.obj mmioVorbis.obj
	$(CC) $(CFLAGS) $^ libvorbis-1.0rc2/lib/*.obj libogg-1.0rc2/src/*.obj -o mmiovorbis.exe -Zstack 65536 $(LIBS)

	
clean:
	-rm core *.obj mmiovorbis.exe mmiovorb.dll

