#
# A Makefile for OS/3 boot sequence project
# micro IIF drivers
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS =	&
#		some

!include $(%ROOT)/mk/all.mk

#TARGETS = subdirs
#TARGET = all
