#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ = critstrs
TRGT = $(PROJ).exe
DESC = Critical Error Strings compiler
srcfiles = $(p)critstrs$(e)
ADD_COPT = -i=..$(SEP)include

!include $(%ROOT)/mk/tools.mk

