#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ = critstrs
DESC = Critical Error Strings compiler
srcfiles = $(p)critstrs$(e)
ADD_COPT = -i=..$(SEP)include
TARGETS = $(PATH)$(PROJ).exe

!include $(%ROOT)/mk/tools.mk

