# $Id: makefile,v 1.2 2004/08/16 04:51:22 prokushev Exp $
#

ROOT=..\..\..
!include $(ROOT)\makefile.inc

all: stub.obj

# Clean all

clean: .symbolic
 -@del *.obj $(LOG)
 -@del *.sbr $(LOG)
 -@del *.map $(LOG)
 -@del *.err $(LOG)
