#
# A Makefile for WIN.COM
# (c) osFree project,
# author, date
#

PROJ       = win
TRGT       = $(PROJ).com
DESC       = Windows Loader
srcfiles   = $(p)execlogo$(e)
JWASM      = 1
COM        = 1

!include $(%ROOT)/mk/appsdos.mk
