/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifdef __PRIVATE__

#ifndef rhbtypes_idl
	#define rhbtypes_idl
	#include <somobj.idl>

	typedef SOMFOREIGN RHBORB;
	#pragma modifier RHBORB: impctx=C;
	typedef SOMFOREIGN RHBGIOPRequestStream;
	#pragma modifier RHBGIOPRequestStream: impctx=C;
	typedef SOMFOREIGN RHBInterfaceDef;
	#pragma modifier RHBInterfaceDef: impctx=C;
	typedef SOMFOREIGN RHBOperationDef;
	#pragma modifier RHBOperationDef: impctx=C;
	typedef SOMFOREIGN RHBObject;
	#pragma modifier RHBObject: impctx=C;
	typedef SOMFOREIGN RHBRequest;
	#pragma modifier RHBRequest: impctx=C;
	typedef SOMFOREIGN RHBServerRequest;
	#pragma modifier RHBServerRequest: impctx=C;
	typedef SOMFOREIGN RHBServerWaitingRoom;
	#pragma modifier RHBServerWaitingRoom: impctx=C;
	typedef SOMFOREIGN RHBProcessInfo;
	#pragma modifier RHBProcessInfo: impctx=C;
#endif /* rhbtypes_idl */

#endif /* __PRIVATE__ */
