/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef stexcep_idl
#define stexcep_idl
#include <somdtype.idl>
module StExcep
{
	#pragma prefix "omg.org/CORBA"

#define ex_body   { unsigned long minor; completion_status completed; }

    exception UNKNOWN       ex_body;    // the unknown exception
    exception BAD_PARAM     ex_body;    // an invalid parameter was passed
    exception NO_MEMORY     ex_body;    // dynamic memory allocation failure  
    exception IMP_LIMIT     ex_body;    // violated implementation limit
    exception COMM_FAILURE  ex_body;    // communication failure
    exception INV_OBJREF    ex_body;    // invalid object reference
    exception NO_PERMISSION ex_body;    // no permission for attempted op.
    exception INTERNAL      ex_body;    // ORB internal error
    exception MARSHAL       ex_body;    // error marshaling param/result
    exception INITIALIZE    ex_body;    // ORB initialization failure
    exception NO_IMPLEMENT  ex_body;    // operation implementation unavailable
    exception BAD_TYPECODE  ex_body;    // bad typecode
    exception BAD_OPERATION ex_body;    // invalid operation
    exception NO_RESOURCES  ex_body;    // insufficient resources  for req.
    exception NO_RESPONSE   ex_body;    // response to req. not yet available
    exception PERSIST_STORE ex_body;    // persistent storage failure
    exception BAD_INV_ORDER ex_body;    // routine invocations  out of order
    exception TRANSIENT     ex_body;    // transient failure - reissue request
    exception FREE_MEM      ex_body;    // cannot free memory
    exception INV_IDENT     ex_body;    // invalid identifier syntax
    exception INV_FLAG      ex_body;    // invalid flag was specified
    exception INTF_REPOS    ex_body;    // error accessing interface repository
    exception BAD_CONTEXT   ex_body;    // error processing context object
    exception OBJ_ADAPTER   ex_body;    // failure detected by object adapter
    exception DATA_CONVERSION  ex_body; // data conversion error
    exception OBJECT_NOT_EXIST ex_body; // non-existent object, delete reference
    exception TRANSACTION_REQUIRED ex_body;		// transaction required
    exception TRANSACTION_ROLLEDBACK ex_body;	// transaction rolled back
    exception INVALID_TRANSACTION ex_body;		// invalid transaction
    exception INV_POLICY    ex_body;			// invalid policy
    exception CODESET_INCOMPATIBLE ex_body;		// incompatible code set
};
#endif /* stexcep_idl */
