#
# A Makefile for OS/3 build tools
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = rexxutil rxmath rxuls rxsock # rxregexp

!include $(%ROOT)/mk/all.mk

TARGETS = subdirs
TARGET  = all
