PKGDIR	?= ../..
L4DIR	?= $(PKGDIR)/../..

# insert the binary name of the server to test
TEST_SERVER	=

# insert the binary name of the application testing the server
TEST_CLIENT	=

include $(L4DIR)/mk/runux.mk
