#
# A main Makefile for OS/3 boot sequence project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = rexxext interp rexx rexxapi libs cmd rexxinit

!include $(%ROOT)/mk/all.mk

#TARGETS = subdirs
#TARGET = all
