#
# A Makefile for ANSI
# (c) osFree project,
# author, date
#

PROJ = print
TRGT = $(PROJ).exe
DESC = PRINT utility
#defines object file names in format $(p)objname$(e)
srcfiles = $(p)print$(e)
# defines additional options for C compiler
ADD_COPT    = -i=$(MYDIR)..$(SEP)include
UNI2H = 0
STUB=$(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)os2stub.exe

!include $(%ROOT)/mk/appsos2_pm.mk
