#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

PROJ      = attrib
DESC      = Control file attributes
#defines object file names in format objname.$(O)
srcfiles  = $(p)attrib$(e) $(p)tcc2wat$(e)
# defines additional options for C compiler

!include $(%ROOT)/mk/appsdos.mk
