PROJ = spdx-annotate
TRGT = $(PROJ).exe
#DESC = Sed language interpreter
srcfiles = $(p)spdx-annotate$(e)

ADD_COPT = -i=..$(SEP)include
ADD_LINKOPT = lib reuse_parser.lib

!include $(%ROOT)tools/mk/tools.mk
