# DESCRIPTION = Sed language interpreter
TARGET_API = HOST
TARGET_BITS = 32

ADD_COPT = -i=..$(SEP)include
ADD_LINKOPT = lib reuse_parser.lib, spdx.lib, json.lib, sha1.lib, git.lib, omf.lib, res.lib

!include $(%ROOT)tools/mk/build.mk
