#
# A Makefile for libmmap
# (c) osFree project,
# valerius, 2006/10/30
#

PROJ      = libmmap
TRGT      = $(PROJ).lib

!include $(%ROOT)/mk/libs.mk

TARGETS   = $(PATH)$(TRGT)

$(PATH)$(TRGT): $(MYDIR)$(TRGT)
 @$(CP) $< $^@ $(BLACKHOLE)
