#ifdef __cplusplus
      extern "C" {
#endif

#define DDIM_INCLUDED

ULONG APIENTRY Gre32Entry2(ULONG,ULONG);
ULONG APIENTRY Gre32Entry3(ULONG,ULONG,ULONG);
ULONG APIENTRY Gre32Entry4(ULONG,ULONG,ULONG,ULONG);
ULONG APIENTRY Gre32Entry5(ULONG,ULONG,ULONG,ULONG,ULONG);
ULONG APIENTRY Gre32Entry6(ULONG,ULONG,ULONG,ULONG,ULONG,ULONG);
ULONG APIENTRY Gre32Entry7(ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG);
ULONG APIENTRY Gre32Entry8(ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG);
ULONG APIENTRY Gre32Entry9(ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG);
ULONG APIENTRY Gre32Entry10(ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG,ULONG);

#define INCL_GRE_DCS

#ifdef INCL_GRE_DCS
   #define GreOpenDC(a,b,c,d,e) (HDC) Gre32Entry7((ULONG)(HDC)(a),(ULONG)(ULONG)(b),(ULONG)(PSZ)(c),(ULONG)(LONG)(d),(ULONG)(PDEVOPENDATA)(e),0L,0x00000200L)
   #define NGreOpenDC 0x00000200L
   #define GreCloseDC(a) (BOOL) Gre32Entry3((ULONG)(HDC)(a),0L,0x00004201L)
   #define NGreCloseDC 0x00004201L
   #define GreEscape(a,b,c,d,e,f) (LONG) Gre32Entry8((ULONG)(HDC)(a),(ULONG)(ULONG)(b),(ULONG)(LONG)(c),(ULONG)(PBYTE)(d),(ULONG)(PLONG)(e),(ULONG)(PBYTE)(f),0L,0x000040D2L)
   #define NGreEscape 0x000040D2L
   #define GreQueryDeviceCaps(a,b,c,d) (BOOL) Gre32Entry6((ULONG)(HDC)(a),(ULONG)(LONG)(b),(ULONG)(PLONG)(c),(ULONG)(LONG)(d),0L,0x000040D1L)
   #define NGreQueryDeviceCaps 0x000040D1L
   #define GreQueryHardcopyCaps(a,b,c,d) (LONG) Gre32Entry6((ULONG)(HDC)(a),(ULONG)(LONG)(b),(ULONG)(LONG)(c),(ULONG)(PHCINFO)(d),0L,0x000040D3L)
   #define NGreQueryHardcopyCaps 0x000040D3L
#endif

#ifdef __cplusplus
      }
#endif

