PROJ = spdx-merge
TRGT = $(PROJ).exe
DESC = SDPX merger
srcfiles = $(p)spdx-merge$(e)

ADD_COPT = -i=..$(SEP)include
ADD_LINKOPT = lib reuse_parser.lib, spdx.lib, json.lib

!include $(%ROOT)tools/mk/tools.mk
