#  Makefile for shared objects
#
#  osFree project, 2007, prokushev

srcfiles = $(p)stub$(e)
ADD_COPT=-bm -od -mf -sg -d2 -mf
DEST     = none

!include $(%ROOT)/mk/appsos2.mk

TARGETS = $(OBJS)
