#  Makefile for shared objects
#
#  osFree project, 2007, prokushev

srcfiles = $(p)stub$(e)
ADD_COPT=-bm -od -mf -sg -d2 -mf

!include $(%ROOT)/mk/appsos2_cmd.mk

DEST    = none
TARGETS = $(OBJS)
