#
# A Makefile for ANSI
# (c) osFree project,
# author, date
#

PROJ = windemo
DESC = Simple Windows Application
#defines object file names in format objname.$(O)
srcfiles = $(p)msgcode$(e) $(p)windemo$(e)
# defines additional options for C compiler
ADD_COPT = -zW

!include $(%ROOT)/mk/win16app.mk
