#
# A Makefile for ANSI
# (c) osFree project,
# author, date
#

PROJ = windemo
TRGT = $(PROJ).exe
DESC = Simple Windows Application
#defines object file names in format objname.$(O)
srcfiles = $(p)MsgCode$(e) $(p)windemo$(e)
# defines additional options for C compiler
ADD_COPT = -zW

!include $(%ROOT)/mk/appsw16.mk
