#
# A Makefile for EXIT_VDM
# (c) osFree project,
# author, date
#

PROJ      = exit_vdm
TRGT      = $(PROJ).com
DESC      = Exit VDM
srcfiles  = $(p)exit_vdm$(e)
COM       = 1

!include $(%ROOT)/mk/appsdos.mk

