#
# A Makefile for SOM
# (c) osFree project
#

DIRS = 	port msg pdl sc somcpp somipc somenv somxh somstars somcorba somhh host somkpub idl somcprep genh genxh somc spp somopc somtk som

!include $(%ROOT)tools/mk/all.mk
