#
# A Makefile for SOM
# (c) osFree project
#

DIRS = 	port pdl sc somcpp somipc somenv somxh somstars somcorba somhh host somkpub idl somcprep genh genxh somc spp

!include $(%ROOT)tools/mk/all.mk
