/**************************************************************************
 *
 *  Copyright 2008, Roger Brown
 *
 *  This file is part of Roger Brown's Toolkit.
 *
 *  This program is free software: you can redistribute it and/or modify it
 *  under the terms of the GNU Lesser General Public License as published by the
 *  Free Software Foundation, either version 3 of the License, or (at your
 *  option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful, but WITHOUT
 *  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 *  more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

/*
 * $Id$
 */

#ifndef somap_idl
#define somap_idl
#include <somos.idl>
#include <somtdm.idl>
module somAttributePersistence
{
	interface Persist :	TypecodeDataManipulator, somOS::ServiceBasePRef
	{
		void load_attribute(
			in string attribute_name,
			out void * buffer,
			in TypeCode attribute_tc);
		void store_attribute(
			in string attribute_name,
			in void * buffer,
			in TypeCode attribute_tc);
#ifdef __SOMIDL__
		implementation
		{
			releaseorder : load_attribute,store_attribute;
			majorversion = 3;
			minorversion = 0;
			dllname = "somos.dll";
#ifdef __PRIVATE__
			init_for_object_creation : override;
			init_for_object_reactivation : override;
			init_for_object_copy : override;
			reinit : override;
			capture : override;
			uninit_for_object_move : override;
			uninit_for_object_passivation : override;
			uninit_for_object_destruction : override;
			functionprefix = "somap_";
#endif
		};
#endif /* __SOMIDL__ */
	};
};
#endif /* somap_idl */
