/* This file is part of osFree project */

import <l4/os3/gcc_os2def.h>

interface os2app
{
    /* Get LoadError */
    void app_GetLoadError([in, out,
                          ref,
                          prealloc_client,
                          prealloc_server,
                          size_is(cbLoadError)] char **uchLoadError,
                          [in, out] ULONG *cbLoadError,
                          [out] ULONG *retCode);

    /* Terminate itself */
    void app_Terminate(void);
};
