#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

DIRS = cmd # utils strings criter lib

!include $(%ROOT)/mk/all.mk

TARGETS=subdirs
TARGET=all
