# $Id: makefile,v 1.2 2004/08/16 04:51:11 prokushev Exp $

PROJ = pmrexxio
TRGT = $(PROJ).hlp
DEST = os2$(SEP)help

!include $(%ROOT)/mk/appsos2.mk

$(PATH)$(PROJ).hlp:

TARGETS = $(PATH)$(PROJ).hlp
