#
# A Makefile for MEM
# (c) osFree project,
# author, date
#

PROJ = mem
TRGT = $(PROJ).exe
DESC = Control file attributes
#defines object file names in format objname.$(O)
srcfiles = $(p)mem$(e) $(p)prf$(e) $(p)kitten$(e)
# defines additional options for C compiler

!include $(%ROOT)/mk/appsdos.mk
