#
# A Makefile for MEM
# (c) osFree project,
# author, date
#

PROJ = mem
DESC = Control file attributes
#defines object file names in format objname.$(O)
srcfiles = $(p)kitten$(e) $(p)mem$(e) $(p)prf$(e)
# defines additional options for C compiler

!include $(%ROOT)/mk/appsdos.mk
