
/*
 * xwpsetup.idl:
 *      SOM interface description file for the following
 *      XWorkplace classes (in this order):
 *          XWPSetup
 *      and the respective metaclasses.
 *
 *      See src\classes\xwpsetup.c for details.
 */

/*
 *      Copyright (C) 1999-2003 Ulrich M”ller.
 *
 *      This file is part of the XWorkplace source package.
 *      XWorkplace is free software; you can redistribute it and/or modify
 *      it under the terms of the GNU General Public License as published
 *      by the Free Software Foundation, in version 2 as it comes in the
 *      "COPYING" file of the XWorkplace main distribution.
 *      This program is distributed in the hope that it will be useful,
 *      but WITHOUT ANY WARRANTY; without even the implied warranty of
 *      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *      GNU General Public License for more details.
 */

#include <wpabs.idl>         // this is SOM for WPAbstract

/*
   CLASS: XWPSetup

   CLASS HIERARCHY:

       SOMObject
         ÀÄÄ WPObject
               ÀÄÄ WPAbstract
                     ÀÄÄ XWPSetup
*/

interface M_XWPSetup;            // forward reference to metaclass

interface XWPSetup : WPAbstract
{
    /*
     * New instance methods for XWPSetup:
     *
     */

    ULONG xwpAddXWPSetupPages(in HWND hwndDlg);

#ifdef __SOMIDL__
    implementation
    {
        releaseorder:
            xwpAddXWPSetupPages;

        /*
         * Class Modifiers:
         *
         */

        externalprefix = xwset_;
        externalstem = xwset;
        majorversion = 1;
        minorversion = 2;
        filestem = xwpsetup;           //# specifies the filestem for sc-generated files
        metaclass = M_XWPSetup;
        dllname = "xfldr.dll";
        callstyle = oidl;           //# forget CORBA stuff (*ev and such)

        /*
         * The following is forced into the .H file:
         *
         */

        passthru C_h =
"";

        /*
         * Internal instance variables for XWPSetup:
         *
         */

        /*
         * WPAbstract methods overridden by XWPSetup:
         *
         */

        wpFilterPopupMenu: override;

    //#    wpQueryDefaultHelp: override;    replaced with class method V0.9.20 (2002-07-12) [umoeller]
        wpQueryDefaultView: override;

        wpAddObjectWindowPage: override;

        wpAddSettingsPages: override;
    };
#endif
};

//#
//#
//# Now define Metaclass.
//# ---------------------
//#

interface M_XWPSetup : M_WPAbstract
{

#ifdef __SOMIDL__
    implementation
    {
        /*
         * Class Modifiers:
         *
         */

        externalprefix = xwsetM_;
        externalstem = xwsetM;
        functionprefix = xwsetM_;
        majorversion = 1;
        minorversion = 2;
        filestem = xwpsetup;           //# specifies the filestem for sc-generated files
        dllname = "xfldr.dll";
        callstyle = oidl;

        /*
         * Internal class variables:
         *
         */

        /*
         * M_WPAbstract methods overridden by M_XWPSetup:
         *
         */

        wpclsInitData: override;

        wpclsQueryStyle: override;
        wpclsQueryTitle: override;
        wpclsQueryDefaultHelp: override;

        wpclsQueryIconData: override;
    };
#endif
};


