#
#
#

DIRS    =
PROJ    = oso001h
TRGT    = $(PROJ).msg
DEST    = os2$(SEP)system

!include $(%ROOT)/mk/appsos2.mk

TARGETS = $(PATH)OSO001h.msg $(PATH)oso001h.pl $(PATH)OSO001h.ru

$(PATH)OSO001h.msg:

$(PATH)oso001h.pl:

$(PATH)OSO001h.ru:

$(PATH)oso001h.rsf:
 @$(MAKE) $(MAKEOPT) T=$^. rsf
