#
# A Makefile for MiniCMD
# (c) osFree project,
# prokushev, 2008
#

PROJ = minicmd
DESC = Minimalistic Command line processor
#defines object file names in format objname.$(O)
srcfiles = $(p)minicmd$(e) $(p)commands$(e)
STUB=$(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)os2stub.exe

IMPORTS = KbdStringIn        EMXWRAP.209

!include $(%ROOT)/mk/appsos2.mk
