PKGDIR  ?= ../../..
REP_DIR ?= $(PKGDIR)/../../..

include $(REP_DIR)/mk/osfree.mk

# the name of your library
TARGET	= libos2common.a

# list your .c files here
SRC_C	= path.c token.c string.c env.c

include $(L4DIR)/mk/lib.mk
