#  Makefile for shared objects
#
#  osFree project, 2007, prokushev

TRGT     = stub.obj
srcfiles = $(p)stub$(e)
ADD_COPT=-bm -od -mf -sg -d2 -mf
DEST    = none

!include $(%ROOT)/mk/appsos2_cmd.mk

#TARGETS = $(OBJS)
TARGETS = $(PATH)$(TRGT)
