#
# A Makefile for ATTRIB
# (c) osFree project,
# author, date
#

!include $(%ROOT)/build.conf
!include $(%ROOT)/mk/site.mk

#32_BITS  = 1

PROJ = basic
DESC = BASIC and BASICA programming language
#defines object file names in format objname.$(O)
OBJS = bwbasic.$(O) &
bwb_cmd.$(O) &
bwb_cnd.$(O) &
bwb_dio.$(O) &
bwb_elx.$(O) &
bwb_exp.$(O) &
bwb_fnc.$(O) &
bwb_inp.$(O) &
bwb_int.$(O) &
bwb_mth.$(O) &
bwb_ops.$(O) &
bwb_par.$(O) &
bwb_prn.$(O) &
bwb_stc.$(O) &
bwb_str.$(O) &
bwb_tbl.$(O) &
bwb_tcc.$(O) &
bwb_var.$(O) &
bwx_tty.$(O)
#bwx_ncu.$(O) # link this for ncurses use

#renum.$(O)

#bwx_iqc.$(O) &
# defines additional options for C compiler

ADD_COPT = -ml

!include $(%ROOT)/mk/all.mk


all: $(PROJ).exe $(PROJ).sym .SYMBOLIC

$(PROJ).exe: $(OBJS)
 @%create $^&.lnk
 @%append $^&.lnk SYSTEM dos
# @%append $^&.lnk SYSTEM os2v2
 @%append $^&.lnk NAME $^&
 @%append $^&.lnk OPTION MAP=$^&.wmp
# @%append $^&.lnk OPTION STACK=65535000
 $(ADDFILES_CMD)
 $(SAY) Linking $^@ $(LOG)
 $(LINKER) $(LINKOPT) @$^&.lnk $(LOG)
 @$(MAKE) $(MAKEOPT) install

.IGNORE
clean: .SYMBOLIC
 $(SAY) Making clean... $(LOG)
 $(CLEAN_CMD)

install: .SYMBOLIC
 $(SAY) Making install... $(LOG)
 $(CP) $(PROJ).exe $(FILESDIR)$(SEP)dos$(SEP)$(PROJ).com
 $(CP) $(PROJ).exe $(FILESDIR)$(SEP)dos$(SEP)$(PROJ)a.com
 $(CP) $(PROJ).exe $(FILESDIR)$(SEP)dos$(SEP)gw$(PROJ).exe
