#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

# before build command line tools build "shared" libraries
DIRS =        shared &
              ansi   &
              bldlevel &
              chkdsk &
              cls &
              cmd &
              dskxtrct &
              eject &
              e &
              fdisk &
              fdiskpm &
              format &
              help &
#              helpmsg &
              keyb &
              label &
              lvm &
              lvmgui &
              makeini &
              minicmd &
              mkdir &
              mode &
              more &
              recover &
              screenrs &
              sysinstx &
              syslevel &
              tedit &
              tshell &
              undelete &
              unzip &
              ver &
              vol &
              zip &
              newmbr &
              pmseek &
              print

#              diskcomp
#              network

!include $(%ROOT)tools/mk/all.mk

