#
# A main Makefile for osFree Command Line tools project
# (c) osFree project,
# valerius, 2006/10/30
#

# before build command line tools build "shared" libraries
DIRS =        shared &
              ansi   &
              attrib &
              bldlevel &
              chkdsk &
              cls &
              cmd &
              comp &
              diskcopy &
              dskxtrct &
              eject &
              e &
              fdisk &
              fdiskpm &
              find &
              format &
              help &
#              helpmsg &
              keyb &
              label &
              lvm &
              lvmgui &
              makeini &
              minicmd &
              mkdir &
              mode &
              more &
              newmbr &
              recover &
              screenrs &
              sort &
              sysinstx &
              syslevel &
              tedit &
              tree &
              tshell &
              undelete &
              ver &
              vol &
              xcopy &
              zip &
              print

#              diskcomp
#              network

!include $(%ROOT)/mk/all.mk

#TARGETS = subdirs
#TARGET = all
