# $Id: makefile,v 1.3 2004/08/21 14:49:03 prokushev Exp $
#

TARGET_CLASS = LIBRARY
SOURCES = ytab
!include $(%ROOT)tools/mk/build.mk

$(PATH)ytab.c: ytab.y

$(PATH)ytab.h: ytab.y

.c: $(PATH)

.h: $(PATH)
