#
# A Makefile for ANSI
# (c) osFree project,
# author, date
#

PROJ = chkdsk
DESC = CHKDSK front-end
#defines object file names in format objname.$(O)
srcfiles = $(p)chkdsk$(e)
# defines additional options for C compiler
ADD_COPT = -i=$(MYDIR)..$(SEP)include
#STUB=$(FILESDIR)$(SEP)os2$(SEP)mdos$(SEP)os2stub.exe
STACKSIZE = 40960
OPTIONS = MIXED1632

!include $(%ROOT)/mk/appsos2.mk
