DIRS = ufat32 util ifs fat32chk partfilt ifsinf

all: .SYMBOLIC
 @for %d in ($(DIRS)) do if exist %d @cd %d && wmake -f makefile.wcc

clean: .symbolic
 @for %d in ($(DIRS)) do if exist %d @cd %d && wmake -f makefile.wcc clean
