#
# A Makefile for APPEND
# (c) osFree project,
# author, date
#

PROJ      = edlin
TRGT      = $(PROJ).com
DESC      = Line editor
srcfiles  = $(p)defines$(e) $(p)dynstr$(e) $(p)edlib$(e) $(p)edlin$(e)
COM       = 1

!include $(%ROOT)/mk/appsdos.mk
